### ISSUE TITLE
medium-editor-toolbar-1 not being rehidden

### ISSUE THREAD

**Issue by chisholmd** [yabwe/medium-editor#1005]
Once I load a form containing the editor, "medium-editor-toolbar-1" becomes visible in the back ground of other pages.

![image](https://cloud.githubusercontent.com/assets/13528823/13621782/eec9a9e6-e54e-11e5-93ea-6f1fa661c493.png)

**Comment by nmielnik** [comment]
@chisholmd this looks like you haven't included the medium-editor css file on the page, can you verify that `medium-editor.css` is loaded?

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
