### ISSUE TITLE
Is there any way to know the order of nodes?

### ISSUE THREAD

**Issue by b84330808** [yabwe/medium-editor#1007]
If I select more than one node, the anchorNode and extentNode in selection will be different depends on the direction I select from (down-to-up or up-to-down). 
But just depending on the selection, I do not know which node is on the up and which is down. Is any way to know ?

**Comment by nmielnik** [comment]
@b84330808 I think what you're looking for is `anchorNode` and `focusNode` on the selection object.

I believe `anchorNode` will always be the the element the selection started at, and `focusNode` will always be element the selection ended in.

If you're just trying to figure out which direction the selection was based on the selection itself (left vs right) you'll also need to call `window.getSelection().getRangeAt(0)` to get a reference to the `Range` object.

On the Range, you can look at `startContainer` and `endContainer`. which will always be in the correct order in respect to the DOM.  `startContainer` will also be earlier in the DOM than `endContainer`, so you can compare that to the nodes in `anchorNode` and `focusNode` from selection and figure out if the selection was left to right (or top to bottom) or vice versa.

Does that answer your question?

**Comment by b84330808** [comment]
Thanks! 
This helps me.

**Comment by nmielnik** [comment]
:+1:
