### ISSUE TITLE
Several bugs in IE

### ISSUE THREAD

**Issue by vansosnin** [yabwe/medium-editor#1010]
1. Empty textbox (has class `medium-editor-placeholder`) looks ugly. It depends on `:after`. When I unset the `content` everything appears to be OK.
![ie1](https://cloud.githubusercontent.com/assets/8207551/13704463/f605b26a-e7bd-11e5-8072-8dda98c205bd.PNG)

2. Problem with word breaking.
![ie2](https://cloud.githubusercontent.com/assets/8207551/13704567/62c1a8fa-e7be-11e5-912e-00a43f523c6a.PNG)

**Comment by j0k3r** [comment]
Which version of IE are you using?

**Comment by vansosnin** [comment]
IE 11

**Comment by vansosnin** [comment]
Issue fixed #1043
