### ISSUE TITLE
Space in .medium-editor-toolbar-input breaks anchor preview

### ISSUE THREAD

**Issue by MichalSchwarz** [yabwe/medium-editor#1014]
If I add space inside a link, it is accepted and after that the link is no more editable through anchor preview.

**Comment by j0k3r** [comment]
Could you provide a jsfiddle with that behavior ? Thanks

**Comment by MichalSchwarz** [comment]
Go: http://yabwe.github.io/medium-editor/
Select any word and click link icon.
Write "aa aa" and confirm.
Anchor preview does not show up on hover over the link after that.

Link without spaces "aaaa" works as expected.

**Comment by j0k3r** [comment]
Hum right, but link aren't supposed to have space inside them.

**Comment by MichalSchwarz** [comment]
Yes, i think so. Should not be possible to enter them. Link is allready trimmed out of spaces around, is it possible to check for spaces inside and remove them or warn user? It looks weird that it stays as link, but i can't remove or edit it again.

**Comment by MichalSchwarz** [comment]
Only way to remove it is to select the exact phrase and click link again. It is not straightforward action.

**Comment by j0k3r** [comment]
Maybe instead of removing all spaces **inside** the link, we can convert them to be a valid url, like using encodeURIComponent

**Comment by MichalSchwarz** [comment]
Great. Thanks!

**Comment by nmielnik** [comment]
Sounds like a good enhancement, maybe this should be its own option, or something that is automatically enabled via the [ancho.linkValidation](https://github.com/yabwe/medium-editor/blob/master/OPTIONS.md#linkvalidation) option?
