### ISSUE TITLE
Inserting HTML manually

### ISSUE THREAD

**Issue by victor-ponamariov** [yabwe/medium-editor#1021]
Hi there!

I think I do not understand `pasteHTML()` method correctly. Basically in my case I have few already existing email templates and I want to be able to select a template (which I get through ajax) and fill medium editor with the template.

I tried to call `pasteHtml()` after I get template through ajax without any success. So, if I already have some html how can I completely clean everything and replace it with the html?

Thanks in advance, I think I'm missing something very obvious

**Comment by nmielnik** [comment]
@victor-ponamariov `pasteHTML()` will only replace the html that is within the current selection.  You can use helper methods like `MediumEditor.selection.selectNode()` or `MediumEditor.selection.select()` to help you select the part of the editor that you want to replace before you call `pasteHTML()`.

There isn't documentation for those selection helpers yet, but you can find the source code in [`selection.js`](https://github.com/yabwe/medium-editor/blob/master/src/js/selection.js)

If you just want to replace the entire contents of the editor, you can just call the [`setContent()`](https://github.com/yabwe/medium-editor/blob/master/API.md#setcontenthtml-index) helper method on the editor itself.

Will these help you accomplish what you're trying to do?

**Comment by victor-ponamariov** [comment]
It says that setContent it not a function.
Here is the code:

`let editor = new MediumEditor('#emailText', {
      targetBlank: true,
      placeholder: 'Email body'
    });

    editor.setContent('<b>test</b>');`

**Comment by nmielnik** [comment]
What version of medium-editor are you using?  It looks like this method was added in version [5.5.0](https://github.com/yabwe/medium-editor/releases/tag/5.5.0)

**Comment by victor-ponamariov** [comment]
Oh, indeed I had 4.* version. Updated to 5.5.4

However, the setContent method replaced entire contents of the editor, but related textarea (in my case '#emailText') is not filled. When I manually type something in the textarea it works fine, when I replace content with the function server says textarea is empty. Any clues?

**Comment by nmielnik** [comment]
Looks like the issue you're talking about was fixed in version [5.11.0](https://github.com/yabwe/medium-editor/releases/tag/5.11.0).

**Comment by victor-ponamariov** [comment]
Indeed. Thank you so much, looks like it works now!
