### ISSUE TITLE
When all text is a title, it cat get impossible to undo it

### ISSUE THREAD

**Issue by graciano** [yabwe/medium-editor#1027]
When making a test post in my application, **I made a ctrl+A and clicked in the `H2` button** (and other buttons that worked fine), resulting in this html:
```html
<h2><p>blsbdalsadbl<br><p><i>asskada</i></p></p><p><br></p></h2>
```
Now, when I try to select and click the `H2` button again, it doesn't work.
Not sure if it's a bug.
Any clues in how to solve it?

**Comment by litera** [comment]
It is a bug, as P also can't be nested withing P2. But it may not be a bug of ME per se, but rather browser DHTML capabilities as ME most often calls into `execCommand` expecting browser to do what it's supposed to.

**Comment by nmielnik** [comment]
Looks like some extra `<p>` got inserted in there as well, if you remove those extra `<p>` tags does the issue go away?

It's possible the pending work @harzzn has done in #997 combined with the work @nextend is doing in #1020 could help prevent those extra `<p>`s from getting inserted.

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
