### ISSUE TITLE
When pasting big text or image width automatically change.

### ISSUE THREAD

**Issue by shystruk** [yabwe/medium-editor#1034]
Hi all, 

have a small issue which wants to fix by editor core options, but haven't found.

So, when pasting big text or image width automatically change and when open content is too big the same behavior there. 
Can I prevent this, can disable re-sizing ?

Thank you!

**Comment by nmielnik** [comment]
Have you tried setting a width on the editor element via CSS?

**Comment by shystruk** [comment]
Yes, I've tried it works. But I support responsive and don't want do that in outside. 
I thought editor has in core options something for that.

**Comment by nmielnik** [comment]
The editor doesn't have any options like that, and I'm not sure we would want that sort of functionality to be handled by javascript within the editor. 

The editor is ultimately just another html element, so you should be able to treat it like any other element where you'd want to control the width of its content in a responsive way.  From what I've seen, this is almost always desirable through css and not javascript.
