### ISSUE TITLE
Hoe to show toolbar on certain elements?

### ISSUE THREAD

**Issue by psypersky** [yabwe/medium-editor#1037]
Hi, im trying to avoid the toolbar to show in embedded element captions with the medium-editor-insert-plugin, at the moment of creating the caption im setting 'mouseup' and 'select' events listeners to the element and doing e.stopPropagation and e.preventDefault but it always shows up, how could i catch that event before medium editor and stop it?

**Comment by orthes** [comment]
I think this is an issue of medium-editor-insert-plugin and not of medium-editor. The toolbar shouldn't be visible on embed's captions. Please, move this issue to medium-editor-insert-plugin and try to reproduce it on jsfiddle.net
