### ISSUE TITLE
Toolbar in ios

### ISSUE THREAD

**Issue by dcversus** [yabwe/medium-editor#1039]
When selecting text does not appear panel. Probably because does not fire checkState in mouseup event.
It can even be seen on https://yabwe.github.io/medium-editor/

iPhone 6S Plus 
iOS, v9

**Comment by j0k3r** [comment]
The lib isn't designed to work on iOS for the moment.

**Comment by dcversus** [comment]
I fix this problem local and I would like to share a solution.
Need add event on selectionchange that call checkState. Can I make PR with solution?

**Comment by j0k3r** [comment]
Yeah feel free to submit a PR :)

**Comment by orthes** [comment]
@rvetere is working on a mobile support - not only ios, but also android. I think he's close to creating PR himself.

**Comment by rvetere** [comment]
Hi @dcversus - that's true i'm working (when i find time) on a mobile support PR too. I went so far that the toolbar is now showing up on mobile, by using the additional event "onselectionchange" like you already mentioned ;)

You know what, i should have done this already.. i just create a new branch on the repo here, introducing my changes so far and i will come up with a new discussion thread for it to tear that down ;)

**Comment by dcversus** [comment]
ok, waiting branch with solution

**Comment by rvetere** [comment]
I've created a new issue as a follow-up: https://github.com/yabwe/medium-editor/issues/1040

There is also a new branch called "mobile-support" with all changes so far
