### ISSUE TITLE
Get node of current selection 

### ISSUE THREAD

**Issue by mike623** [yabwe/medium-editor#1041]
how to get node inside `handleClick` function ?

**Comment by orthes** [comment]
Have you tried this?

```javascript
handleClick: function (e) {
  var node = e.currentTarget;
}
```

**Comment by mike623** [comment]
e.currentTarget  is return the button I click.
I want to get the selection text similar `isAlreadyApplied` node

**Comment by orthes** [comment]
Then take a look here: https://github.com/yabwe/medium-editor/blob/master/src/js/extensions/anchor.js#L60

You can get selected range and out of range you can get the node. Let me know if it helped.

**Comment by mike623** [comment]
Yes, it helped. Thank you
