### ISSUE TITLE
Do not create new quotes on enter

### ISSUE THREAD

**Issue by psypersky** [yabwe/medium-editor#1054]
If you create a quotation and then click 'enter' it will create another one, im new to the codebase so suggestions of where to look in the code to fix it are welcome :)

**Comment by rishijain** [comment]
The way it works right now is if you press `enter`, it does create a new `blockquote`, but if you press `backspace` upon an empty `blockquote`, it changes to `p` tag.

You can find most of the handling of formatting around `blockquote` here https://github.com/yabwe/medium-editor/blob/master/dist/js/medium-editor.js#L920

**Comment by nmielnik** [comment]
Fixed via #1162
