### ISSUE TITLE
Emojis aren't parsed with this editor.

### ISSUE THREAD

**Issue by Kondra007** [yabwe/medium-editor#1055]
I've tried pasting some emojis from [official list](http://unicode.org/emoji/charts/full-emoji-list.html), however, Medium-Editor seems to skip them.

Am I doing something wrong or that's a feature? I've found this issue: #999, hovewer, it's still unclear, where's the problem.

**Comment by orthes** [comment]
As you pointed out, this question was already asked in #999. Please continue discussion there, so we could have everything related to emojis in one thread. Thanks.

**Comment by shyamal890** [comment]
@MasterGroosha Where you able to solve this issue. If so, could you please guide

**Comment by MasterGroosha** [comment]
@shyamal890 unfortunately, not
