### ISSUE TITLE
CSS word-break: break-all is intended but why oh why!?

### ISSUE THREAD

**Issue by thatdoorsajar** [yabwe/medium-editor#1057]
It appears from [medium-editor.scss](https://github.com/yabwe/medium-editor/blob/cb39b46318c7396c8fe7e2a19eb236d560cbb266/src/sass/medium-editor.scss#L13) that `word-break: break-all` is intended behavior. From the W3 spec on word-break, "break-all" means "Lines may break between any two letters". Why would this be the intended behaviour of any text editor? I thought it was initially a bug with my code, checked about, then checked medium-editor demo on both Chrome and Firefox to find it was the intended behaviour of `[data-medium-editor-element]`

This seems far to obvious to be an oversight, so what the devil am I missing!?

**Comment by orthes** [comment]
This was added only recently here: #1043

You're absolutely right, this is a wrong behavior and it would be replaced with `word-wrap: break-word;`

**Comment by thatdoorsajar** [comment]
@orthes great, I should have mentioned I would submit PR if necessary but fix is small and you seem to have sorted already. Only just started using medium-editor today, loving the community, documentation and maintenance around this package, will be using often from now on! Cheers

**Comment by Kondra007** [comment]
Well, it's still not working for me. For example "hello" word will be split as "hel" and "lo"

**Comment by j0k3r** [comment]
@Kondra007 Please provide a JSBin / jsfiddle containing a set of reproducible steps.

**Comment by Kondra007** [comment]
@j0k3r Sorry, I can't do this. Don't know how to put the whole "project", even small one to those websites. I can link you to "live" example with this issue.   
Url: http://kondra007.github.io/telegram-web-poster/  
Source code: https://github.com/Kondra007/telegram-web-poster  
Using medium-editor js file from `dist` folder from `5.21.0` release.

Here how it looks like right now.

![image](https://cloud.githubusercontent.com/assets/2780044/17546469/eacd64b6-5eea-11e6-9547-72365efe668c.png)

**Comment by orthes** [comment]
@Kondra007 It looks like you updated JS to the latest version, but not CSS. JS was updated 7 hours ago, but CSS 4 months ago.

**Comment by Kondra007** [comment]
@orthes My fault, thanks!
