### ISSUE TITLE
styling not coming in pasted items

### ISSUE THREAD

**Issue by Sandip-pal** [yabwe/medium-editor#1063]
I am using the below property in medium editor.
```js 
forcePlainText: false,
cleanPastedHTML: false,
cleanReplacements: [],
cleanAttrs: ['class', 'style', 'dir'],
cleanTags: ['meta']
```

But the styling from a word document is not coming in medium editor page while pasting.

**Comment by nmielnik** [comment]
@Sandip-pal can you share what browser + OS combination you're using, along with the full set of options you're passing the editor?

**Comment by Sandip-pal** [comment]
Now it is working. I probably missed something.
The working code is:
paste: {
                forcePlainText: false,
                cleanPastedHTML: true,
                cleanReplacements: [],
                cleanAttrs: ['class', 'style', 'dir'],
                cleanTags: ['meta', 'img']
    }
