### ISSUE TITLE
Not working on dynamically added elements

### ISSUE THREAD

**Issue by alvarotrigo** [yabwe/medium-editor#1065]
The plugin doesn't get applied to dynamically added elements
[Reproduction online](https://jsfiddle.net/ay9cLgab/3/)

We are forced to call it initialise it multiple times:
https://jsfiddle.net/ay9cLgab/4/

**Comment by nmielnik** [comment]
We're aiming to have this fixed by #1038 , which would allow you to dynamically add and remove elements from an already initialized instance...

**Comment by nmielnik** [comment]
@alvarotrigo in a similar vein to #1101 , you'd want to call `.destroy()` on existing instances of the editor before you initialize a new instance using the same elements.  

As an alternative, you can now call `.addElements()` on an existing instance of the editor and pass it the same selector, and it will find all elements on the page at that point, detect which elements are already have been added to the editor, and only re-initialize the ones that haven't.

**Comment by alvarotrigo** [comment]
Thanks the answer.

**Comment by oknoorap** [comment]
when I use addElements, buttons are not displaying

**Comment by nmielnik** [comment]
@oknoorap do you mind opening a separate issue with more repro steps?  Perhaps a jsfiddle?  I'm not sure what issue you're describing.
