### ISSUE TITLE
Prevent creating paragraphs outside <p> elements?  

### ISSUE THREAD

**Issue by alvarotrigo** [yabwe/medium-editor#1066]
By default medium-editor creates new paragraphs when pressing the enter key (by itself, without pressing shift at the same time).

It seems to me a bit undesirable for non experts users who are not used to use SHIFT + enter. 

[Reproduction online](https://jsfiddle.net/ay9cLgab/13/)

Isn't there a way to disable this feature to create a `<br />` instead? Or to enable it only inside other `<p>` tags?

**Comment by orthes** [comment]
We don't support this feature yet. @rishijain started working on it here: #912, but he never finished. Maybe you can take a look there and see if it's something you can pick up and build upon.

**Comment by nmielnik** [comment]
@alvarotrigo could you look at #70 and #251 to see if they are talking about the same functionality that you're talking about?

**Comment by alvarotrigo** [comment]
#251 is exactly what I'm reporting. I'll proceed to close the issue.
