### ISSUE TITLE
Doesn't allow selecting across multiple editors

### ISSUE THREAD

**Issue by kieraneglin** [yabwe/medium-editor#1069]
### Description

We are in a situation where we will have 2+ independent editors on the same page.  Right now, there doesn't seem to be a way to select across editors
### Steps to reproduce
1. Create two editor instances with same class selector
2. Try to highlight between editors

**Expected behavior:** You can highlight all the text intended (and tooltip shows up)

**Actual behavior:** You can only highlight in one editor or the other
### Versions
- medium-editor: 5.16.1
- browser: Firefox 45.0.2
- OS: OSX 10.11.4

**Comment by nmielnik** [comment]
@kieraneglin could you help describe the functionality you're trying to accomplish?  I'm not sure if I understand the expected behavior, or why you would want to have 2 instances of the editor applying to the same editable element.

**Comment by kieraneglin** [comment]
Our editors are being dynamically generated (the the possibility of another element being put in between two editors)

I was wondering if it's possible to be able to highlight between editors.  It's not a game-breaker, more of a curiosity.

**Comment by nmielnik** [comment]
Ok, so are you asking about something like this?

```html
<div class="editable1">
    <!-- some editable html content -->
</div>
<div class="not-editable">
    <!-- some static html content -->
</div>
<div class="editable2">
    <!-- some other editable content -->
</div>
```

Where the 1st and 3rd div are managed by 2 separate instances of MediumEditor, but the 2nd `<div class="not-editable">` is just static. Is that the scenario you're talking about?

I can tell you that in this scenario you wouldn't be able to have a selection that spans from the `<div class="editable1">` element to the `<div class="editable2">` element and it work correctly.  I'm not sure what exactly the behavior would be or if the browser would even allow you do make a selection like that.

If this isn't what you're describing, could you provide some sample html/js?  Depending on what you're trying to do we might be able to help suggest ways to leverage medium-editor to accomplish your goals.

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
