### ISSUE TITLE
Support for pull quotes.

### ISSUE THREAD

**Issue by abitdodgy** [yabwe/medium-editor#107]
Medium has two types of quotes, normal block quotes, and something usually referred to as pull quotes. Setting a pull quote centres it in the middle of the screen. It's done by clicking the quote button twice.

![screen shot 2013-12-05 at 01 21 40](https://f.cloud.github.com/assets/545430/1679795/7149d44a-5d5c-11e3-9ceb-e389a20a6acc.png)
![screen shot 2013-12-05 at 01 21 44](https://f.cloud.github.com/assets/545430/1679797/77cf9ca0-5d5c-11e3-80b2-c7743c798348.png)

**Comment by chenware** [comment]
+1

**Comment by nmielnik** [comment]
How much does this differ from #575 ?  Are these both referencing the same kind of functionality?

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
