### ISSUE TITLE
Click twice to get rid of toolbar

### ISSUE THREAD

**Issue by amosrichards** [yabwe/medium-editor#1072]
### Description

I've installed medium-editor in drupal 7, and I'm having to tap twice to get rid of the toolbar. 

Is there a way I can ensure the destruction of the toolbar after the first tap?

### Versions

- medium-editor:latest
- browser:all
- OS:mac

**Comment by nmielnik** [comment]
Can you give some clarifications regarding the repro steps?  Perhaps a jsfiddle or something where the issue can be reproduced?  I'm not familiar with drupal so I don't have an easy way to help investigate.
