### ISSUE TITLE
Incorrent behaviour in getSelectionStart() 

### ISSUE THREAD

**Issue by MikeDevice** [yabwe/medium-editor#1078]
### Description

`MediumEditor.selection` has a method `getSelectionStart`. In some cases it returns an empty `div` instead of `<p><br></p>`.

### Steps to reproduce

1. Type some text after editor initialize.
2. Select this text and wrap it inside H2 (or any other header element) using toolbar.
3. Move caret at the end of line.
4. Press `Enter` key.

**Expected behavior:**
`MediumEditor.selection.getSelectionStart(wysiwyg.options.ownerDocument)` method should return `<p><br></p>` because caret is in empty line.

**Actual behavior:**
`MediumEditor.selection.getSelectionStart(wysiwyg.options.ownerDocument)` returns `<div></div>`

**Note**
I've noticed this method works correctly if I wrap it with `setTimeout` method.

**Link to an example:**
[DEMO](https://jsfiddle.net/9zqjjpjx/5/)

### Versions
- medium-editor: 5.16.1
- browser: Google Chrome 50.0.2661.75 (64-bit)
- OS: Ubuntu 14.04 LTS

**Comment by orthes** [comment]
Hm I don't think this is a bug. To prevent cross browser problems, the editor replaces all empty `<div></div>` with `<p><br></p>`. So if you call `getSelectionStart` before this is done, you'll get `<div></div>`, but it will be replaced immediately. So if you wait a little (thus `setTimeout` works), you'll get correct response.

You can use `setTimeout(function () {}, 0)` and it should also work. `setTimeout` with 0 will move the function to the end of the queue and other tasks (like replacing `<div>` with `<p>`) will be executed before the function in `setTimeout`.
