### ISSUE TITLE
Change ToolBar Options for some elements

### ISSUE THREAD

**Issue by ankur0890** [yabwe/medium-editor#1080]
Is it possible to change toolbar options for some elements? 

Like for p element I want ['bold','italic','underline','h2','h3','link'] but for figure element I want only ['bold','italic','underline']. Is there a way of doing that. Not aware of it as of now.

**Comment by nmielnik** [comment]
@ankur0890 check out #797 as this specific behavior is discussed there and there is an existing in-progress extension would could definitely be iterated upon.
