### ISSUE TITLE
when edit the page again, the html tag will auto render

### ISSUE THREAD

**Issue by pengbo37877** [yabwe/medium-editor#1090]
### Description

I have two pages for create/edit the article content, one is create page, the other is edit page. when I created a article on create page which contents `<i>Abcd`. it shows "_Abcd_" on edit page.

### Steps to reproduce

1. on create article page. I input `<i>Abcd`, and save to my database. the database record shows `<p class="">&lt;i&gt;Abcd</p>`
2. on edit article page. I only get "_Abcd_"

**Expected behavior:** on edit page shows `<i>Abcd`

**Actual behavior:** on edit page shows "_Abcd_"

### Versions

- medium-editor: 5
- browser: chrome
- OS: mac os x 10.11.5 beta

### WTF

github editor has the same problem. so i add blank between `<` and i

**Comment by nmielnik** [comment]
@pengbo37877 When you say "edit article page" are you talking about a different editor where you provide the starting html to the editor?  How is the html getting passed back into the editor from you database?

**Comment by pengbo37877** [comment]
@nmielnik I fixed this by using `setContent` method. thx 4 u response.
