### ISSUE TITLE
Add custom class to links

### ISSUE THREAD

**Issue by Olgagr** [yabwe/medium-editor#1091]
This is just a question:

is this possible to add the custom class to link automatically ? (without letting user to choose to add one or not)

**Comment by rishijain** [comment]
I don't think there is any feature like this which works right out of the box. But you can look at [Capturing DOM Changes](https://github.com/yabwe/medium-editor#capturing-dom-changes)

Also you can try reading through these issues: https://github.com/yabwe/medium-editor/issues/1035 and https://github.com/yabwe/medium-editor/issues/914 . They are not exactly what you are looking for but are on similar lines.

**Comment by Olgagr** [comment]
@rishijain Thank you!

**Comment by nmielnik** [comment]
@Olgagr Another way you could do this is by overriding the `getFormOpts()` property of the anchor extension.

If you look at the code [here](https://github.com/yabwe/medium-editor/blob/5.14.0/src/js/extensions/anchor.js#L199-L220) you'll see this method checks to see if the user checked the 'button class' checkbox, and if they did, adds a `buttonClass` property to the `opts` object it returns.  Ultimately, this gets passed into the `createLink()` method [here](https://github.com/yabwe/medium-editor/blob/5.14.0/src/js/core.js#L1050) which will add a class name on to the anchor.

I haven't tested this exact code, but you could do something like this to override the anchor extension:

```js
var customAnchorExtension = MediumEditor.extensions.anchor.extend({
    getFormOpts: function () {
        // call the existing method
        var opts = MediumEditor.extensions.anchor.prototype.getFormOpts.call(this);
        opts.buttonClass = 'Whatever class name you want on all anchors';
        return opts;
    }
});
new MediumEditor('.editor', {
    anchor: new customAnchorExtension()
});
```

In the end, it might be better to do what @rishijain was suggesting, but this could be a way to add a class to all anchors created through medium-editor.

**Comment by Olgagr** [comment]
@nmielnik Yep, I also thought about overriding this method but in my case this is really important that all links get this class (even if user paste the text). Anyway, I really appreciate your help and advices :)

**Comment by nmielnik** [comment]
np 😄
