### ISSUE TITLE
exportSelection() not working correctly to get selected text.

### ISSUE THREAD

**Issue by sanket-hulle** [yabwe/medium-editor#1096]
### Description

I have added custom button to medium editor.I would like to get selected text for further operation so,I am using exportSelection and using resulting start and end indices I am getting text with the help of function- substring() .
It works correctly  for plain text, but when I apply Bold and Italic tags to selected text , I am getting incorrect indices.(I am using editor.exportSelection() to get indices.)

### Steps to reproduce

1. Apply bold and Italic class using editor buttons.
2. Get indices using editor.exportSelection().
3. editor text.substring(indices)

**Expected behavior:** Get actual Selected Text

**Actual behavior:** getting wrong text

is there any alternative to get selected text?
Thanks in advance.

**Comment by nmielnik** [comment]
If you're just trying to get the currently selected text, you can just get the current [`Range` object](https://developer.mozilla.org/en-US/docs/Web/API/Range) via `MediumEditor.selection.getSelectionRange(document)` where you pass the document in as a param.

Once you have the range, you can just call `toString()` on it and get the current text.  

`importSelection()` and `exportSelection()` are built more for trying to keep what the user has selected consistent when focus is moving around to different fields (like when you try to create a link and type the url in a new textbox).

**Comment by sanket-hulle** [comment]
Thank you so much.
