### ISSUE TITLE
Anchor-preview extension needs to be refactored too

### ISSUE THREAD

**Issue by gpetrov** [yabwe/medium-editor#1105]
Because of the refactoring of Anchor Extension's showForm to take "value" option instead of "url"  
https://github.com/yabwe/medium-editor/commit/50503d5e4de4f8bb9535e51bde5949a0e61f48a8#diff-20ab57acb9b766e8d29282b1d91c3d28

Also the Anchor-Preview should be changed:

https://github.com/yabwe/medium-editor/blob/master/src/js/extensions/anchor-preview.js#L158

to be "value" and not "url"

**Comment by nmielnik** [comment]
You are correct @gpetrov .  Just to confirm though, nothing is actually broken right now correct?  The change we made should support both `url` and `value` until we completely remove `url` in 6.0.0.

**Comment by gpetrov** [comment]
well the problem now is - that when inspecting an existing link - "undefined" is displayed in the edit link form.

**Comment by nmielnik** [comment]
Yes, you're right!  Thanks for pointing this out, this definitely needs to be fixed. Would you be interested in opening a PR?
