### ISSUE TITLE
Error: Unable to start Medium Editor in MeteorJS

### ISSUE THREAD

**Issue by ansonla3** [yabwe/medium-editor#1111]
### Description

I got error when I start the project in meteor. I install medium-editor via npm import it like 
import MediumEditor from 'medium-editor';

[Description of the bug or feature]
Not sure what is that means "document is not defined"
### Steps to reproduce
1. [First step]
2. [Second step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]
The console shown:
/.meteor/packages/meteor-tool/.1.3.2_4.us47lg++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160602-01:54:25.273(8)? (STDERR)                             throw(ex);
W20160602-01:54:25.274(8)? (STDERR)                                   ^
W20160602-01:54:26.582(8)? (STDERR) ReferenceError: document is not defined
W20160602-01:54:26.582(8)? (STDERR)     at Object.<anonymous> (webpack:///~/medium-editor/dist/js/medium-editor.js:10:1)
W20160602-01:54:26.582(8)? (STDERR)     at **webpack_require** (webpack:/webpack/bootstrap 7f19ab698e06628a1f5b:23:1)
W20160602-01:54:26.582(8)? (STDERR)     at Object.classListProp (webpack:///src/client/modules/news/components/create_news.jsx:3:1)
W20160602-01:54:26.582(8)? (STDERR)     at **webpack_require** (webpack:/webpack/bootstrap 7f19ab698e06628a1f5b:23:1)
W20160602-01:54:26.582(8)? (STDERR)     at Object.defineProperty.value (webpack:///src/client/modules/news/routes.jsx:9:1)
W20160602-01:54:26.582(8)? (STDERR)     at **webpack_require** (webpack:/webpack/bootstrap 7f19ab698e06628a1f5b:23:1)
W20160602-01:54:26.582(8)? (STDERR)     at Object.defineProperty.value (webpack:///src/client/modules/news/index.js:4:1)
W20160602-01:54:26.583(8)? (STDERR)     at **webpack_require** (webpack:/webpack/bootstrap 7f19ab698e06628a1f5b:23:1)
W20160602-01:54:26.583(8)? (STDERR)     at Object.<anonymous> (webpack:///src/client/main.js:12:1)
W20160602-01:54:26.583(8)? (STDERR)     at **webpack_require** (webpack:/webpack/bootstrap 7f19ab698e06628a1f5b:23:1)

**Link to an example:** [If you're reporting a bug that's not reproducible on our [demo page](https://yabwe.github.io/medium-editor/demo.html), please try to reproduce it on [JSFiddle](https://jsfiddle.net/), [JS Bin](https://jsbin.com), [CodePen](http://codepen.io/) or a similar service and paste a link here]
### Versions
- medium-editor: the latest one
- browser: Chrome
- OS: MAC

**Comment by nmielnik** [comment]
@ansonla3 have you tried using this: https://atmospherejs.com/mediumeditor/mediumeditor ?

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
