### ISSUE TITLE
Editor breaks in electron environment 

### ISSUE THREAD

**Issue by sajus** [yabwe/medium-editor#1123]
[Description of the bug or feature]
https://github.com/yabwe/medium-editor/blob/master/dist/js/medium-editor.js#L389
`if (typeof module === 'object') {
        module.exports = factory;
 }`

In electron environment, which use Nodejs, module is defined and editor tries to export itself. Which causes breaks to already exist electron code base.

**Comment by sajus** [comment]
https://github.com/sajus/medium-editor/commit/61046c9cef3d5754f15395d47dfffbb35b7ec821

**Comment by nmielnik** [comment]
@sajus is there something unique on the `module` object in electron that we could add to the detection here?  I'm not familiar with this at all, but it seems like we just need to differentiate between standard node and electron somehow inside the export logic.

**Comment by nmielnik** [comment]
Seems like a workaround would be to delete the reference to `window.module` and `window.exports` like what is mentioned here: http://electron.atom.io/docs/faq/#i-can-not-use-jqueryrequirejsmeteorangularjs-in-electron

**Comment by sajus** [comment]
@nmielnik you can detect electron environment from the below code.
`typeof module == "object" && process && process.versions && process.versions.electron`

Hope this resolves your query.

**Comment by nmielnik** [comment]
@sajus can you try changing that chunk of code in your fork to this:

```js
(function (root, factory) {
    'use strict';
    var isElectron = typeof module == "object" && process && process.versions && process.versions.electron;
    if (!isElectron && typeof module === 'object') {
        module.exports = factory;
    } else if (typeof define === 'function' && define.amd) {
        define(function () {
            return factory;
        });
    } else {
        root.MediumEditor = factory;
    }
}(this, function () {
```

If that works for you, either you or I can open a PR and get the fix in.

**Comment by sajus** [comment]
https://github.com/yabwe/medium-editor/pull/1125

**Comment by durgeshahire4** [comment]
Please check PR of Medium Editor Tables : https://github.com/yabwe/medium-editor-tables/pull/30

**Comment by sajus** [comment]
@j0k3r , @nmielnik can you please bump new version? Also NPM needs to be updated which is been used by medium-editor-tc https://github.com/tomchentw/medium-editor-tc-mention/blob/master/src/index.js#L1-L3

**Comment by nmielnik** [comment]
@sajus we might try to get #1128 in first, and then we'll cut a new release

**Comment by nmielnik** [comment]
@sajus 5.21.0 should now be available.

**Comment by dypsilon** [comment]
This breaks CommonJS environment without `process` variable. Please see #1221.
