### ISSUE TITLE
When I try to click out of the medium-editor it re-focuses its self

### ISSUE THREAD

**Issue by jcalfee** [yabwe/medium-editor#1132]
### Description

When I click away, I trap the a medium-editor's div attribute change.  This is the code that runs causing the element to re-focus preventing me from leaving to another input field:
```
                if (toFocus) {
                    // Trigger focus on the editable that now has focus
                    toFocus.setAttribute('data-medium-focused', true);
                    this.triggerCustomEvent('focus', eventObj, toFocus);
                }
```
### Steps to reproduce
1. 
```
import MediumEditor from 'medium-editor'
require('medium-editor-insert-plugin')($)
class ReactMediumEditor extends React.Component {
    componentDidMount() {
        const dom = ReactDOM.findDOMNode(this);
        this.medium = new MediumEditor(dom, {placeholder: false});
        $(dom).mediumInsert({
            editor: this.medium
        });
    }
    render() {
        const tagEl = React.createElement('div', this.props);
        return <div>
            {tagEl}
        </div>
    }
}
2. Add ReactMediumEditor and  <input type="text" /> to a root component.. 
3. Click in the ReactMediumEditor component then try to click away to the text component (does not work)
```

The chrome inspector has a feature called `Break on...`  `Attributes modified`.   This shows that Mediums code above is running and re-focusing when trying to click away.

### Versions

- medium-editor: 5.21.0
- browser: chrome 50.0.2661.102

**Comment by jcalfee** [comment]
This has to do with too much re-rendering in react..  As soon as I rendered the editor once this issue stopped.

**Comment by nmielnik** [comment]
@jcalfee you can also use `editor.selectElement()` to set focus within the editor, you can choose the element where you want the cursor to be as the argument you pass in to `selectElement()` and then collapse the selection.
