### ISSUE TITLE
Custom Toolbar - How

### ISSUE THREAD

**Issue by injectless** [yabwe/medium-editor#1133]
![screenshot_2016-06-29_18-18-41](https://cloud.githubusercontent.com/assets/12424545/16469434/4d12995a-3e27-11e6-835a-8fb3046b63d6.png)

Yes, that's one of the few extensions of this library, **medium-editor-insert-plugin**
Works amazing.

Now, I did went through the docs, but I am very confused about this subject: 
**How to build custom toolbars for elements like _img_, _video_, ...** They don't work with bold, underline and stuff.
The closes doc I found was the Anchor-Tag, but yet, it shows the rest of the toolbar.

So, 
I just need a custom toolbar for _img_ tags, but I am not going to use **medium-editor-insert-plugin**, because _I am writing a plugin for this library_ which involves MathJax, but I got that cover.

So, I could really use some code which when you click at a img#idhere (or .class) shows up a custom toolbar.

Thanks

**Comment by nmielnik** [comment]
@injectless I can think of at least 2 ways to approach what you're describing.

1. Hide/show buttons in the existing toolbar based on what is selected.  This is talked about in #797 and @davideanderson started building a plugin attempting to do just that [here](https://github.com/davideanderson/medium-editor-toolbar-states).  You can see our discussion about building this plugin in this [gitter channel](https://gitter.im/nmielnik/797ContextAwareToolbar).

2. Override the existing toolbar.  The toolbar itself is an extendable extension, just like any of our other built-in extensions.  If you override the default toolbar, you can really do whatever you want (ie have 2 separate toolbar elements that your toolbar knows about and chooses which one to hide).  You can extend the existing toolbar and override any methods you'd like by doing something like this:

```js
var MyCustomToolbar = MediumEditor.extensions.toolbar.extend({
    // add your own custom methods and/or override existing methods/properties here
    showToolbar: function () {
        // override showToolbar to do whatever you want
    }
});

var editor = new MediumEditor(".editor". {
    extensions: {
        toolbar: new MyCustomToolbar()
    }
});
```

Hope that helps.

**Comment by injectless** [comment]
I'm closing this for now until I have something solid to share as an open source extension

Thanks @nmielnik!

**Comment by gfmclean** [comment]
What about simply overriding the css as follows to hide the toolbar if you wish to call the actions from another element?

.medium-editor-toolbar-active {
            visibility: hidden;
}

Only started using this so please let me know if this is not a correct approach.  Also, if you have an example of calling for example bold and italics or any other functions from other buttons, please do let me know
