### ISSUE TITLE
Target Blank for Anchor tag not working properly

### ISSUE THREAD

**Issue by durgeshahire4** [yabwe/medium-editor#1135]
### Description

In option,

set  'targetBlank': true
set  'linkValidation': true

And try to click on link. Link not working  as expected. 

### Steps to reproduce

1. set  'targetBlank': true
2. set  'linkValidation': true
3.  click on link and see

**Expected behavior:**  Link should work as expected, click on link url should open in new tab.

**Actual behavior:** nothing happens. 

### Versions

- medium-editor: 5.21.0
- browser: Chrome 51.0.2704.103 (64-bit)
- OS: OSX

**Comment by durgeshahire4** [comment]
PR: https://github.com/yabwe/medium-editor/pull/1136

**Comment by rishijain** [comment]
@durgeshahire4 From what I understood: 
If you click on the link, it will not go to the actual href link. Double clicking on it will open the toolbar as it works with any other text and hovering over the link will open the pop up and then eventually you can edit the link from it. But clicking on the link will not go the actual page.

Please let know if this answers your query.

**Comment by durgeshahire4** [comment]
@rishijain No its different, When we set in Options as TargetBlank = true and LinkValidation = true. That means we want to open that link in another tab.
After that we create Link. when we single click on that link then nothing happen. It doesn't go to another tab. link not get open. 
If i use the above solution it works perfectly.

**Comment by rishijain** [comment]
@durgeshahire4  Links do open upon clicking on them in a tab as you mentioned but only in "non-edit" mode. Whereas when in "edit" mode, it will not open the links.

I think if you go through this https://github.com/yabwe/medium-editor/issues/918 issue, you will see the point I am trying to make.

**Comment by durgeshahire4** [comment]
@rishijain ohh that means its existing functionality. 
Thanks for the quick response. 
Closing the issue
