### ISSUE TITLE
Image button can only convert image without the protocol

### ISSUE THREAD

**Issue by francis6425** [yabwe/medium-editor#1138]
The image button can only convert text to image starting with double forward slash + the filename behind.

Most of the users who doesn't know that the protocol like http: or https must be removed from the text before trying to convert to <img>

Can the code be modified to include auto removing of the protocol and add the double forward slash if it is not inside the text.

It should be very easy to implement.

**Comment by francis6425** [comment]
I've tried to modify to modify the code as follows and it works.
        if (action === 'image') {
            var src = '//' + this.options.contentWindow.getSelection().toString().replace(/.*?:\/\//g, '').trim();
            return this.options.ownerDocument.execCommand('insertImage', false, src);
        }

Can someone help to update it to the next release. (I'm a noob and don't know how to do it but hope to see it get updated so that I can continue to link it thru CDN instead.)

**Comment by nmielnik** [comment]
@francis6425 I was able to insert an image into one of the demo pages that contained the protocol.

1) Navigate to https://yabwe.github.io/medium-editor/static-toolbar.html
2) Paste this url into the editor https://www.random.org/analysis/randbitmap-rdo.png
3) Highlight the text and click the `Image` button in the toolbar

The image url is converted to an image.  Does this not work for you?

**Comment by francis6425** [comment]
Hi,

I just tried it and it is now working.
Also tried linking it from CDN and it is also working.

Thanks
