### ISSUE TITLE
Override redo/undo

### ISSUE THREAD

**Issue by ankur0890** [yabwe/medium-editor#1139]
I need to remove some attributes of inserted html whenever undo/redo happens in the editor. Is this scenario possible in the editor? Searched a lot but not able to find a handler for the same.

**Comment by nmielnik** [comment]
You can detect whenever the keys are pressed to trigger an undo/redo (ie <kbd>CTRL</kbd> + <kbd>Z</kbd>) but beyond that I'm not sure of any other ways to detect undo/redo (ie undo/redo from the context menu).

I believe the custom `editableInput` event for medium-editor would also trigger after an undo/redo, but you would need to do some work to try to determine that something was undone/redone and not just normally edited.

There are lots of various libraries out there that have custom undo/redo functionality, it might be worth seeing if they've come up with ways to prevent built-in undo/redo from happening.

**Comment by ankur0890** [comment]
Yeah. I created my own stack to keep track the changes and then removed the aattributes on the text coming. Thanks for your help though :)
