### ISSUE TITLE
How to get multiple line selection node

### ISSUE THREAD

**Issue by ankur0890** [yabwe/medium-editor#1140]
Suppose I have two paragraphs

Paragraph1

Paragraph2

I selected both the paragraphs. I want to get what all nodes which has been selected. Focus node just returns me single paragraph. Ideally it should be two paragraphs as I have selected both. Is there any other way to get this?

<img width="898" alt="screen shot 2016-07-12 at 12 38 28 am" src="https://cloud.githubusercontent.com/assets/1263424/16743286/2cb1e548-47c9-11e6-9c59-77b9e263c8b1.png">

**Comment by nmielnik** [comment]
Are you attempting to get a reference to the actual nodes themselves, or just a copy of the html within the selection?

`MediumEditor.selection.getSelectionHtml(document)` is helper method that will return you all of the html within the selection as a raw html string.
For your example it would return the string `"<p>Paragraph 1</p><p>Paragraph 2</p>"`

`MediumEditor.selection.getSelectedElements(document)` is a helper method that will return you a reference to all of the elements within the selection.
For your example, it would return an array with 2 elements in it (the 2 `<p>` elements).

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
