### ISSUE TITLE
add rel='nofollow' attribute to links

### ISSUE THREAD

**Issue by rosbif-fr** [yabwe/medium-editor#1150]
I'd like to add rel='nofollow' to links added in the editor, but I can't see an easy way of doing this. Am I missing something or is this not currently possible? If not I can submit a pull request for this feature

**Comment by rosbif-fr** [comment]
Actually I realised that implementing this in the editor would be dangerous as the editor source could be easily modified, removing the nofollow. Better to do this on the backend once the form is submit

**Comment by nmielnik** [comment]
@rosbif-fr if you think the end-user might want to add the `rel='nofollow'` attribute to their links, this could still be a useful feature.

For the use case you're describing (where you want to enforce this attribute is on certain links) it seems like it's necessary to do this on the back-end.  However, there is a feature where you can enforce that `target="_blank"` is added to all links.  The user can technically change it, but it would mean editing the raw HTML somehow, so it's definitely not something easily done by the average user.

Anyway, just saying that if there's a somewhat normal use case where user's would want to enable this attribute, or if someone was ok with the attribute being added to all links by default (though the user can still technically change it) then this could still be worth doing.

**Comment by magistrula** [comment]
@nmielnik, I'm encountering a use case where I'd like to add `rel="nofollow"` to my links; could we open this issue back up? What do you think of the way [sanitize.js](https://github.com/gbirke/Sanitize.js) allows you to specify [attributes](https://github.com/gbirke/Sanitize.js#add_attributes-object) to add to various elements?

**Comment by rosbif-fr** [comment]
@magistrula see my original comment - it's of limited use doing this on the frontend, as a spammer can easily submit the form data directly, bypassing any input sanitisation in the editor. You will likely only nofollow legitimate users, and not stop spammers. Much better to do the input sanitisation in the back-end

**Comment by magistrula** [comment]
@rosbif-fr I definitely agree that the backend should enforce this as well, but it may be reasonable to allow this attribute to be added on the frontend to ensure the best experience for legitimate users. For example, I'm working on an Ember app in which we use `ember-cli-medium-editor`, and we autosave the medium-editor content as the user types. If the backend returns a value that is different from what the user typed in, I suspect the medium-editor component will rerender, which will disrupt the user's cursor position. It's fine if this happens to malicious users, but we wouldn't want this to happen to legitimate users.

**Comment by abhishekpandeykr** [comment]
@garethfr how you have added this feature  ``` rel='nofollow' ``` , I am stuck with this, please let me know.

**Comment by Ruudje87** [comment]
so is this implemented allready?
