### ISSUE TITLE
Placeholder text not working in Flat theme

### ISSUE THREAD

**Issue by chintanbanugaria** [yabwe/medium-editor#1156]
### Description

When flat theme is added, custom placeholder is not shown in the editor. If default theme is used placeholder appears back.

**Comment by wildanmuslim** [comment]
I think this problem can be solved by modifying flat.css. by default in flat theme, color for place holder is white (#fff). 

`.medium-editor-placeholder:after {
  color: #fff; }`

change the color with your fav color. 

sorry for my bad english
