### ISSUE TITLE
Getting Title and content separately

### ISSUE THREAD

**Issue by gmtproject** [yabwe/medium-editor#1157]
What is the best way to get Title and content separately?
editor.serialize(); returns all content.

Thanks

**Comment by nmielnik** [comment]
I'm not sure what you're referring to when you say 'Title' and 'content'.  What value of `editor.serialize()` would you like to be returned separately?

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
