### ISSUE TITLE
if pasting SVG when inside a <p> it should put the svg as a child of <p>

### ISSUE THREAD

**Issue by LeonRyan** [yabwe/medium-editor#1169]
### Description

When trying to add an SVG using the pasteHTML() function whilst inside a P, the SVG is added outside the P instead of as a child.
### Steps to reproduce
1. type some text
2. add an svg via pasteHTML()

**Expected behavior:** The inserted SVG should be added as a child of the P element (the same way an IMG is)

**Actual behavior:** The SVG is added after the P and subsequently winds up on the next line.
### Versions
- medium-editor: 5.21.0
- browser: Chrome
- OS: Ubuntu 14

**Comment by j0k3r** [comment]
Please provide a JSBin / jsfiddle containing a set of reproducible steps.
So we'll be able to reproduce the bug and test it on different browser.

**Comment by nmielnik** [comment]
@LeonRyan could you help us with getting a jsfiddle/JSBin?  Would love you try to help sort this out and perhaps try to get a fix in...

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
