### ISSUE TITLE
Embed button extension

### ISSUE THREAD

**Issue by orhanveli** [yabwe/medium-editor#1181]
Hi fellas

I developed an extension to embed social media oEmbed services into the MediumEditor.

Here is the repo. Please check and feedback to develop

https://github.com/orhanveli/medium-editor-embed-button

cheers.

**Comment by j0k3r** [comment]
Interesting!
Any demo page?

**Comment by orhanveli** [comment]
working on it.

**Comment by orhanveli** [comment]
you can see the demo page here

https://github.com/orhanveli/medium-editor-embed-button

**Comment by j0k3r** [comment]
You should add it to: https://github.com/yabwe/medium-editor/blob/master/src/js/extensions/README.md#examples-of-custom-built-external-buttons

**Comment by orhanveli** [comment]
links added and pull request has been sent
