### ISSUE TITLE
Documentation for createLink

### ISSUE THREAD

**Issue by alvarotrigo** [yabwe/medium-editor#1182]
### Description

Documentation for `createLink` doesn't specify its options, format and description of them.

> .createLink(opts): creates a link via the native document.execCommand('createLink') command

Looking at the code I have some trouble trying to understand what is expected as `textNodes` and how can I extract those from a selection. 

**Expected behavior:** 
Documentation for `opts` param.

**Comment by j0k3r** [comment]
I think you should use the method from the editor instead of from the util: https://github.com/yabwe/medium-editor/blob/master/API.md#createlinkopts

What do you want to achieve?

**Comment by alvarotrigo** [comment]
You are right.
