### ISSUE TITLE
setInteractionElements ? Keep editor options visible

### ISSUE THREAD

**Issue by alvarotrigo** [yabwe/medium-editor#1186]
### Description

I had to fork medium editor some time ago to manage to keep the medium editor options visible while using a [custom color picker](https://github.com/yabwe/medium-editor/issues/523#issuecomment-210934396). 

On the last update of medium-editor I I noticed a new function was added: `getInteractionElements`. Which seems to have a very similar purpose to what I was looking for. 

Is there any option to set one of those interaction elements?

**Comment by nmielnik** [comment]
@alvarotrigo [getInteractionElements()](https://github.com/yabwe/medium-editor/tree/master/src/js/extensions#getinteractionelements) is a function that allows extensions to keep the editor from triggering `blur` and from hiding the toolbar when the the user is interacting with the extension.

If you implement `getInteractionElements()` on your extension, have it return the root element(s) for the color picker.  When the toolbar is visible, if the user clicks any element which is a descendant of the elements returned by `getInteractionElements()`, the editor will consider that click as being 'within the editor' and won't hide the toolbar or trigger blur.
