### ISSUE TITLE
Bug: data-disable-preview="true"

### ISSUE THREAD

**Issue by pecuchet** [yabwe/medium-editor#1200]
### Description

When using `data-disable-preview="true"` on a link in the editor, errors are thrown while the editor tries to detach the mouseout event (in anchor-preview.js, line 203).
### Steps to reproduce
1. Insert a link with the toolbar in the [demo](https://yabwe.github.io/medium-editor/demo.html)
2. Add the attribute `data-disable-preview="true"` through your dev tools
3. Hover over the link, check your console

**Expected behavior:** No errors

**Actual behavior:** `Uncaught TypeError: Array.prototype.forEach called on null or undefined`

**Link to an example:** Go to [M-Embed demo](http://pecuchet.github.io/m-embed/) follow the instructions, hover over the embed and check your console
### Versions
- medium-editor: 5.22

**Comment by nmielnik** [comment]
I'm not able to get this to reproduce... @pecuchet does this issue still happen?  I used the link to the demo you provided in the issue, and I'm trying it in chrome but not seeing any errors in the console.

**Comment by brandonhall** [comment]
I'm seeing the same issue reported here. The issue occurs if you mouseover a link with `data-disable-preview` before mousing over a preview enabled link. The problem is that `activeAnchor` is `undefined`.

**Comment by brandonhall** [comment]
I think you just need a conditional [here](https://github.com/yabwe/medium-editor/blob/393677c79a86467873cedb24ce4e03c89e0bf810/src/js/extensions/anchor-preview.js#L205) to check for the existence of `activeAnchor`.
