### ISSUE TITLE
TypeError: a.attributes.href is undefined on Firefox

### ISSUE THREAD

**Issue by khanhlh** [yabwe/medium-editor#1212]
Error when create editor on a link without href attribute.

Here is the sample markup:

```
<a class="editable">This is empty href link</a>
<script>var editor = new MediumEditor('.editable');</script>
```

Open console window, you can see a lot of js error.

**Comment by nmielnik** [comment]
I was not able to reproduce this in any browser. I edited the demo to have the following html, and I was able to edit the text just fine without any errors in the console:

```js
<a class="editable">a link</a>
```

Further, I wouldn't recommend applying the editor the inline elements or elements that are styled by the browser by default.  Though you can likely do some basic editing, I've seen a lot of strange behavior occur once you start trying to style the text, add new-lines, etc. and the behavior can vary greatly from browser to browser.
