### ISSUE TITLE
linkValidaton encodes URL

### ISSUE THREAD

**Issue by cruzanmo** [yabwe/medium-editor#1218]
### Description

Not sure why `linkValidation` is encoding the URL? https://github.com/yabwe/medium-editor/blob/d8806857c07eac8d4781f35e49730d717aba1fd0/src/js/extensions/anchor.js#L246

### Steps to reproduce

1. add an `anchor` button with `linkValidation: true`
2. select text and add a link that has encoded characters, e.g. `http://site.com/?q=http%3A%2F%2Fsite2.com`
3. click checkmark to save link to text.

**Expected behavior:**
Text should have a link as entered: ```<a href="http://site.com/?q=http%3A%2F%2Fsite2.com">text</a>```

**Actual behavior:**
Link is encoded: ```<a href="http://site.com/?q=http%253A%252F%252Fsite2.com">text</a>```

### Versions

- medium-editor: 5.22.0
- browser: all
- OS: all

**Comment by j0k3r** [comment]
Might be related to https://github.com/yabwe/medium-editor/pull/1025

It's mostly to handle url that contains spaces.
Maybe we should go with `value.replace(/\s/g, '%20')` to only replace spaces?

**Comment by cruzanmo** [comment]
Looks like it used to be a regex like that: https://github.com/yabwe/medium-editor/commit/5a9f383fe87d6d4b6b0df617ccb5aebc20c1ca79

If spaces are encoded, then everything should probably be encoded.

Hmm, the solution might be to check if the URL was already encoded, and then only encode if it was not already encoded.
