### ISSUE TITLE
Can I get applied buttons currently?

### ISSUE THREAD

**Issue by LuoPQ** [yabwe/medium-editor#1220]
I want to select some text and get the applied buttons, can i do that?

**Comment by j0k3r** [comment]
Could you be more specific please?

**Comment by LuoPQ** [comment]
I want to get what buttons are already applied to the selected text. For example, I select some text, bold and blockquote buttons apply to the text, How can I get these two buttons apply to the text with the code

**Comment by j0k3r** [comment]
Currently the only detection is done if **the whole text** has the same style.

For example if you have : `<p><b>bold</b> is not <i>italic</i></p>` and you selected the whole content, none of the button will be active because **the whole text** doesn't have one style.

**Comment by LuoPQ** [comment]
@j0k3r thanks, how can I get to know which button is active

**Comment by j0k3r** [comment]
As far as I remember, detection is done [here](https://github.com/yabwe/medium-editor/blob/b7d500e14752cf19f3273eb025318dee8213c652/src/js/extensions/button.js#L196) and you can get an explation from the doc [here](https://github.com/yabwe/medium-editor/blob/008eb67ef942aea7f65ef2e2d9f6dfd94a7a3878/src/js/extensions/WALKTHROUGH-BUTTON.md#5-respond-to-selection).

**Comment by LuoPQ** [comment]
use the follwing code:
`$(editor.getExtensionByName('toolbar').toolbar).find("." + editor.options.activeButtonClass);`
to find current applied buttons
