### ISSUE TITLE
Build breaks in a CommonJS environment

### ISSUE THREAD

**Issue by dypsilon** [yabwe/medium-editor#1221]
The dist breaks any build which has a `module` object defined. This object is always defined in a CommonJS environment. The error I get is:

```
Uncaught ReferenceError: process is not defined
```

This error results from this check:

```javascript
var isElectron = typeof module === 'object' && process && process.versions && process.versions.electron;
```

`module` is an object because we have CommonJS but process is undefined because we are neither in node.js, nor in electron.

This issue is related to #1123.

**Comment by paradite** [comment]
looks like this just needs an additional check `&& typeof process !== 'undefined'` before `&& process`?

**Comment by j0k3r** [comment]
Yep think so!

**Comment by paradite** [comment]
I've opened a PR for this.
