### ISSUE TITLE
Colorise Specific Words while Typing 

### ISSUE THREAD

**Issue by xErik** [yabwe/medium-editor#1229]
Hello!

I like to colorise a specific group of words (house, mouse, ...) in a specific color (red).
Another word group (tree, apple, ...) should be coloured differently (green).

I'd like to checks the words for colouring while typing with the keyup() event. 
(keyup() will get debounced for some milliseconds.)

I gave it a shoot by using medium.value(colorizedString)but this causes the caret to jump around.

What would be the appropriate way to achieve this elegantly?

Would it be useful for me to modify the auto-link extension, or is there a simpler way?

**Comment by xErik** [comment]
To solve this, I created this monstrosity of an extension, it allows to define CSS styles, which get applied to certain words:

[https://github.com/xErik/medium-editor-auto-style-extension](https://github.com/xErik/medium-editor-auto-style-extension)

Preview:

[https://xerik.github.io/medium-editor-auto-style-extension/](https://xerik.github.io/medium-editor-auto-style-extension/)

**Comment by xErik** [comment]
Whops, I reopen it, in case someone is interested in linking the extension.

**Comment by nmielnik** [comment]
@xErik made a cool extension for this, check it out in the links earlier in this issue
