### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of undefined 

### ISSUE THREAD

**Issue by johnlim5847** [yabwe/medium-editor#123]
hey guys merry christmas, this error is keep showing up in my console and i don't know why is anyone have the same issue ? btw i'm using medium-editor with angularjs and  i'm using the directive provided in the readme file which is https://github.com/thijsw/angular-medium-editor

**Comment by cipo2008** [comment]
hello

**Comment by djl132** [comment]
QUILL IS GREAT!!!!
