### ISSUE TITLE
Wrong CDN URLs given on startpage

### ISSUE THREAD

**Issue by xErik** [yabwe/medium-editor#1231]
[https://yabwe.github.io/medium-editor/](https://yabwe.github.io/medium-editor/)

Missing: `http:`

```html
<script src="//cdn.jsdelivr.net/medium-editor/latest/js/medium-editor.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/medium-editor/latest/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
```

**Comment by j0k3r** [comment]
Shouldn't be a problem.
It's intentional.
http://stackoverflow.com/questions/4071117/uri-starting-with-two-slashes-how-do-they-behave
