### ISSUE TITLE
How to listen with Extension to unfocused editor.setContent(bla)

### ISSUE THREAD

**Issue by xErik** [yabwe/medium-editor#1232]
### Description

I wrote an extension that listens to `editableKeypress` and `editableBlur`.

Additionally, I set content programmatically of an editor that has **not** the focus at this moment.  Setting the content via setContent() works, but I am not able to catch this event with my extension.

I used several ways like  `editor.setContent('bla');`,  `cleanPaste()` and listening to an `editablePaste`-event with the extension. I also tried to focus the editor in question, but I didn't get it right.

A workaround is using jQuery to call `.focus().blur()`.  There has to be away to achieve this with MediumEditor alone.

I would appreciate any hint.

**Comment by nmielnik** [comment]
@xErik the `editableInput` event will fire whenever the content of an editor changes, including if it was changed via a call to `setContent()`.

There's a little bit of documentation around this [here](https://github.com/yabwe/medium-editor/blob/master/CUSTOM-EVENTS.md#editableinput).

Big apologies for this answer coming so late 😢  I just saw the awesome AutoStyle Extension you created as I've been catching up on all the medium-editor issues for the past few months, it's very cool!  

I'll be calling out your extension in various places in the documentation as well as adding it to the landing page in the coming days, I'll let you know when it's posted...thanks for sharing your work with everyone and apologies again for this answer coming so late!
