### ISSUE TITLE
Wrap Multiple P tags with Selection.

### ISSUE THREAD

**Issue by atebit** [yabwe/medium-editor#1236]
I've began to program an extension to wrap multiple elements in a `<section>` tag. But, it seems that what I'm doing only adds the tag inside of the default `<p>` tag, which definitely isn't want I want.

Is there a flag to set to do such a thing or is it something that would need to completely change the functionality?

Here's a gist of the extension so far.
https://gist.github.com/atebit/0d2d22b8109a2165e271cf5fcf3367c9

**Comment by nmielnik** [comment]
Please see #1195 , this has been a long-recurring issue and would require some digging/investigation/testing to be able to be fixed with confidence...
