### ISSUE TITLE
linkValidation escapes hash after a query string

### ISSUE THREAD

**Issue by websirnik** [yabwe/medium-editor#1237]
### Description

If I set `linkValidation: true` option, the hash in this valid URL `http://example.com?query=value#anchor` will be escaped, though it should not. This is not happening with these URLs though: `http://example.com?query#anchor` & `http://example.com?query1&query2#anchor`. So it feels like the `=` is causing the problem.
### Steps to reproduce
1. Initialise editor with `linkValidation: true` option
2. Select a word
3. Add this URL as hyperlink: `http://example.com?query=value#anchor`

**Expected behavior:** Hyperlink should point to `http://example.com?query=value#anchor`

**Actual behavior:** Hyperlink points to `http://example.com?query=value%23anchor`

**Link to an example:** 
Add this ULR as hyperlink `http://example.com?query=value%23anchor` here
http://codepen.io/websirnik/pen/NREQEZ
### Versions
- medium-editor: 5.22.1
- browser: Chorme 53
- OS: Mac OS

**Comment by nmielnik** [comment]
Fixed via #1257
