### ISSUE TITLE
As a user i should able to add list, URL & Image from toolbar

### ISSUE THREAD

**Issue by raashidA** [yabwe/medium-editor#1240]
Additional Features

As a user, i wish I able to add List, Image, URL from toolbar

**Comment by Olgagr** [comment]
@raashidA Both orderedlist and unorderedlist are available, adding link as well. Check docs:
https://github.com/yabwe/medium-editor#all-buttons

Image is also supported as button (the same docs). If you need something more sophisticated, check [medium-editor-insert-plugin](https://github.com/orthes/medium-editor-insert-plugin)

**Comment by nmielnik** [comment]
Thanks @Olgagr !
