### ISSUE TITLE
Question: Link Click

### ISSUE THREAD

**Issue by shyamal890** [yabwe/medium-editor#1241]
In the demo when I hover over a link, it shows the web address. Is there a way in which when a user clicks on that link a new tab with that address is opened? At the same time they also can edit the link if need be.

**Comment by Olgagr** [comment]
@shyamal890  Technically yes: he needs to right-click and choose 'Open Link in a New Tab'. On click, preview extension opens edition form.

**Comment by shyamal890** [comment]
Something similar to this would make a lot of sense. 

![i](https://cloud.githubusercontent.com/assets/6606965/20833649/c3be2cc2-b8b6-11e6-8163-d103b78b917e.PNG)

Currently being utilized in Gmail. Try selecting a link in compose mail form.

**Comment by nmielnik** [comment]
This has been mentioned via #1246 as well, but I'm hoping to combine all this into a single issue. 

@shyamal890 do you mind adding your feedback/suggestions into #901 ?
