### ISSUE TITLE
Anchor preview and edit enhancement

### ISSUE THREAD

**Issue by sudarsangp** [yabwe/medium-editor#1246]
### Anchor

Is there a need for a feature like shown in the below screenshot?
![image](https://cloud.githubusercontent.com/assets/2398969/20421387/7dbe5c74-ad9e-11e6-9941-9f4656e8a3ae.png)

Clicking on the link in the **anchor preview** extension would open the link and clicking on the **edit (pencil) icon** would open the anchor form.

**Comment by nmielnik** [comment]
@sudarsangp Could you add your suggestion into the discussion for #901 ?  There has been a fair amount of previous discussion about how link editing should work, and it'd be good to keep it all contained in the same place.  Thanks!
