### ISSUE TITLE
BACKSPACE, CTRL, SHIFT do not trigger "editableKeypress"

### ISSUE THREAD

**Issue by jamespacileo** [yabwe/medium-editor#1247]
### Description

From testing only ENTER + character keys trigger editableKeypress.

BACKSPACE, CTRL, SHIFT, ALT only trigger editableInput and editableKeyup

### Steps to reproduce

Create extension with below code

```
 let TestExtension = MediumEditor.Extension.extend({
      name: "test-extension",
      init: function(){
        console.log("init");
        this.subscribe('editableKeypress', this.onKeypress.bind(this));
        this.subscribe('editableKeyup', this.onKeyup.bind(this));
        this.subscribe('editableInput', this.onInput.bind(this));
      },
      onKeyup: function(ev:MouseEvent){
        console.log("key up");
      },
      onInput: function(ev:MouseEvent){
        console.log("Input");
      },
      onKeypress: function(ev:MouseEvent){
        console.log("key pressed");
      }
})
```

When pressing BACKSPACE Input and Keyup are triggered, but not Keypressed.
Other keys trigger Keypressed as expected.

### Versions

- medium-editor: 5 latest
- browser: Chrome 54
- OS: OSX

**Comment by nmielnik** [comment]
`editableKeypress` is simply a proxy for listening to the `keypress` events fired by any editable elements.  As per the events spec, `keypress` will only be fired by keys that insert characters into an element.  Thus, keys like <kbd>BACKSPACE</kbd>, <kbd>CTRL</kbd>, <kbd>DEL</kbd>, <kbd>SHIFT</kbd>, etc. can only be monitored via `keyup` and `keydown` event listeners.

[Reference](https://developer.mozilla.org/en-US/docs/Web/Events/keypress)
