### ISSUE TITLE
Ctrl+B bug in KeyboardCommands Options

### ISSUE THREAD

**Issue by Kleindberg** [yabwe/medium-editor#1254]
In Google Chrome there is a bug with Ctrl+B: it's not undo when I type Ctrl+B again (like on Italic, Underline).

**Comment by j0k3r** [comment]
Which Chrome version please?
I've tested on 54.0.2840.100 (64-bit) and it works great.

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
