### ISSUE TITLE
How to add a button to change the font

### ISSUE THREAD

**Issue by THPubs** [yabwe/medium-editor#1256]
Hi, can someone please show me how to use the fontName extension to add a button which will change the font? I was unable to figure out how to use that extension.

**Comment by THPubs** [comment]
Anyone?

**Comment by GEEKIAM** [comment]
Hi @THPubs  :v:

Seems `fontname` is a bult-in extension, so you can just override default toolbar options like this:
```javascript
var editor = new MediumEditor('.editable', {
  toolbar: {
    buttons: [
      'fontname'
    ]
  }
});
```

Here is more complex example on JSFiddle: https://jsfiddle.net/ypcgaomL/2/

**Comment by THPubs** [comment]
Cool is it possible to define the exact fonts we need?

**Comment by geekiam** [comment]
Yep, you can do this.

```javascript
var fontsList = ['', 'Arail', 'Open Sans', 'sans-serif', 'Your Font Name'];

var editor = new MediumEditor('.editable', {
  toolbar: {
    buttons: [{
      name: 'fontname',
      action: 'fontName',
      aria: 'change font name',
      contentDefault: '&#xB1;', // ±
      contentFA: '<i class="fa fa-font"></i>',

      fonts: fontsList
    }]
  }
});
```

**Comment by THPubs** [comment]
Perfect thanks!

**Comment by nmielnik** [comment]
Thanks @geekiam !

**Comment by geekiam** [comment]
@nmielnik you're welcome :wink:

**Comment by hayk94** [comment]
Guys adding custom fonts seems to not work for me please help.

https://jsfiddle.net/ypcgaomL/3/
