### ISSUE TITLE
stupid novice Installation question using npm

### ISSUE THREAD

**Issue by Droyk** [yabwe/medium-editor#1268]
I am new to this I just install npm and don't know if medium editor install correctly?

What I did was first install npm and then update it using this command `npm install npm@latest -g`
updated successfully and then run this command `npm install medium-editor` to install medium editor but now it giving me this 

```
C:\Users\Reek>npm install medium-editor
C:\Users\Reek
`-- medium-editor@5.22.1

npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Reek\package.json'
npm WARN Reek No description
npm WARN Reek No repository field.
npm WARN Reek No README data
npm WARN Reek No license field.
```
can someone tell me if it install correctly and now how should I use it

**Comment by hellocosmin** [comment]
Hi,

Sounds like you haven't setup your project to work with NPM. It needs a `package.json` config file, see [the docs](https://docs.npmjs.com/files/package.json) and [how to generate it](https://docs.npmjs.com/cli/init).

**Comment by Droyk** [comment]
okay thanx for the help
