### ISSUE TITLE
Add label-checkbox relation in CreateLink form

### ISSUE THREAD

**Issue by Dahkon** [yabwe/medium-editor#1275]
### Description

When adding the targetCheckbox:true option for anchor links, label is missing the FOR attribute, checkbox is missing also the ID attribute to enable clicking on the label. 

These attributes allow frameworks to replace the checkbox with a good looking one.

Here is my proposal :

```
                template.push(
                    '<div class="medium-editor-toolbar-form-row">',
                    '<input id="medium-editor-toolbar-anchor-target-field" type="checkbox" class="medium-editor-toolbar-anchor-target">',
                    '<label for="medium-editor-toolbar-anchor-target-field">',
                    this.targetCheckboxText,
                    '</label>',
                    '</div>'
                );
```

Thanks,

### Versions

- medium-editor: 5.22.1
- browser: All
- OS: All

**Comment by nmielnik** [comment]
For the `id` of the checkbox, we'd want to make sure we generate something unique.  The editor has its own `id` attribute it defines when the editor is instantiated which ensures that each editor has an id that is unique even if multiple editors are created on the same page, so we could just use that.

In fact, we're already using this unique identifier when we specify an `id` for the anchor extension `<div>` that holds the textbox, checkboxes, buttons, etc. for entering the href for links.   You can see how we use that [here](https://github.com/yabwe/medium-editor/blob/5.22.0/src/js/extensions/anchor.js#L322).  For this id, we should just follow the same pattern.

I think this makes sense and would be a nice and easy bug for anyone to make a simple contribution to medium-editor!
