### ISSUE TITLE
Editing the documetation/read-me

### ISSUE THREAD

**Issue by msaiyaff** [yabwe/medium-editor#1276]
### Documentation need a small update to set the path

Updating the documentation to state the linkable files are in **dist** folder.
For the JS and CSS files.
_Making it easy to newbies_

**Comment by nmielnik** [comment]
@msaiyaff i'm not sure I follow exactly what you're suggesting be changed about the documentation...would you mind just opening a PR and making the change yourself?  If not, could you at least clarify what should be changed?

**Comment by msaiyaff** [comment]
I think this issue has been solved through another PR and closing this issue.
