### ISSUE TITLE
Ability to have a separator in the toolbar

### ISSUE THREAD

**Issue by tkaravou** [yabwe/medium-editor#1281]
### Description

It would be nice to be able to have a separator as an option for the toolbar. I've checked the documentation and I don't see anything like this implemented yet.

**Example usage:** 
When defining the toolbar buttons, a pipe can serve as a separator which would create a blank styleable container
` buttons: ['bold', 'italic', 'underline', '|', 'anchor', 'h2', 'h3', 'quote'],`

**Comment by nmielnik** [comment]
Cool idea, I like it and it could be a pretty simple feature to add.

You could also consider a way to specify a specific class on certain buttons, which would all you to add a border to the right or left to simulate a divider, or perhaps even a pseudo element to act as a separator.

**Comment by nmielnik** [comment]
Closing this in favor of #1206.
