### ISSUE TITLE
pasteHTML doesn't work when the html contains a background-image

### ISSUE THREAD

**Issue by RobertMenke** [yabwe/medium-editor#1284]
### Description

I'm trying to paste html into the editor that contains a background-image. For example,
```javascript
const html_string = '<span style="background-image:url(\'http://pix.iemoji.com/images/emoji/apple/ios-9/256/thinking-face.png\');"></span>';

myeditor.pasteHTML(html_string);

```

When I attempt to paste the above html using the pasteHTML method, the editor seems to reject the string altogether. Nothing gets inserted into the editor. Other html strings seem to work just fine.

### Steps to reproduce

I've created a JS fiddle to demonstrate the issue here: https://jsfiddle.net/a9d9s3aj/2/

**Expected behavior:**
I would expect the HTML to be inserted and the image linked in the `background-image` property to be displayed correctly

**Actual behavior:**

Nothing is pasted into the editor.

### Versions

- medium-editor: Version 5
- browser: Chrome
- OS: Mac OSX/Windows 10

**Comment by j0k3r** [comment]
It's because the `style` attribute is removed by options. And I suspect the span to be also removed.
Update your options: https://github.com/yabwe/medium-editor/blob/master/OPTIONS.md#paste-options

**Comment by RobertMenke** [comment]
@j0k3r Thank you for the quick feedback - I can't believe I missed that before!! 

I did, however, try updating my options to basically disable any cleaning by the API at all and still got the same result https://jsfiddle.net/a9d9s3aj/7/.

Any thoughts on what might be going on here?

**Comment by j0k3r** [comment]
I think you can't paste empty node, I mean, there must be a text inside the span to get it work.
I guess.

**Comment by RobertMenke** [comment]
Alright, it looks like theres no way to add a background-image style. 

When I try that same string with the content `<span style="background-image:url(\'path/to/image.png\');">test</span>` the editor strips out the html and just leaves me with "test" even when `forcePlainText` and `cleanPastedHTML` are set to false.

I think I'll try converting to an actual image tag and using the insert extension. Thanks again for the feedback @j0k3r.

**Comment by nmielnik** [comment]
@RobertMenke as discussed in #1266 it looks like the editor will always remove `<span>` elements regardless of the settings.  Besides inserting actual `<img>` elements, some other things you could try:
1. Use elements other than `<span>` that have a background image
2. Modifying the Paste Extension to allow for the elements you want.  Some other issues where I've outlined ways to override the Paste Extension for various purposes are in #868 and #1159
