### ISSUE TITLE
plugin toolbar doesn't work on iphone safari

### ISSUE THREAD

**Issue by faustoct** [yabwe/medium-editor#1285]
### Description
plugin toolbar doesn't work on iphone safari

[Description of the bug or feature]
The toolbar doesn't appear.

### Steps to reproduce
select text so the toolbar doesnt appear.

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Link to an example:** [If you're reporting a bug that's not reproducible on our [demo page](https://yabwe.github.io/medium-editor/demo.html), please try to reproduce it on [JSFiddle](https://jsfiddle.net/), [JS Bin](https://jsbin.com), [CodePen](http://codepen.io/) or a similar service and paste a link here]

### Versions

- medium-editor: 5.22.1
- browser: Safari/602.1
- OS: iPhone OS 10_2
- User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 10_2 like Mac OS X) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0 Mobile/14C92 Safari/602.1

**Comment by j0k3r** [comment]
https://github.com/yabwe/medium-editor/issues/1164
