### ISSUE TITLE
destroy method does not work

### ISSUE THREAD

**Issue by nicolrx** [yabwe/medium-editor#1290]
### Description

When I call the destroy method in the console it returns undefined

```
var editor = new MediumEditor('.changeable');
editor.destroy(); 
```

My problem is that I save to my db the html and after the Medium Editor toolbar does not show up when I display the html with all the parameters from Medium Editor saved.

**Comment by nmielnik** [comment]
@nicolrx I'm having trouble understanding the issue you're describing.  I'm not sure why you're calling destroy, and what you expect the behavior to be.  `destroy()` will not return anything, it's just used to clean up MediumEditor from the DOM.

You can find the documentation for the destroy function [here](https://github.com/yabwe/medium-editor/blob/master/API.md#destroy) in the API.md file.  Can you read through that, and if you still have a question or are seeing a bug open another issue?
