### ISSUE TITLE
How to make the toolbar automatically visible when instantiate the editor?

### ISSUE THREAD

**Issue by faustoct** [yabwe/medium-editor#1299]

**Comment by faustoct** [comment]
done using 
`this.getExtensionByName('toolbar').getToolbarElement().classList.add('medium-editor-toolbar-active');`

if u have a more polite way pls share.

**Comment by nmielnik** [comment]
There's a function on the toolbar that will add this class itself:

`this.getExtensionByName('toolbar').showToolbar()`
