### ISSUE TITLE
How to escape @ when editing?

### ISSUE THREAD

**Issue by ppKrauss** [yabwe/medium-editor#1310]
### Description

Impossible to say "@X" with other semantic.

### Steps to reproduce

1. open a text to edit
2. try to write `@X`

**Expected behavior:** A HELP or indication about "how to escape" in the editor.

**Actual behavior:** no information, user can't edit what need.

### Versions
medium.com

**Comment by paradite** [comment]
Hi, this repo is for https://yabwe.github.io/medium-editor/ and not related to medium.com.

As stated on the website:

> Note: We're not affiliated with Medium.com, just fans!
