### ISSUE TITLE
Activate the toolbar on clicking an object (instead of selecting it)

### ISSUE THREAD

**Issue by shaanvaidya** [yabwe/medium-editor#1336]

**Comment by awingit** [comment]
Any feedback regarding this? It would be great to be able to show the toolbar upon clicking anywhere. For instance, if I click somewhere which focuses the cursor, I would want the toolbar to show. I understand that selecting would give an indication of what to change, but with regards to the many plugins, there are features to "add", such as the custom HTML extension. I would want to toolbar to show when I simply click anywhere in the text where I want to insert code.
