### ISSUE TITLE
Binding double click event. 

### ISSUE THREAD

**Issue by alisomay** [yabwe/medium-editor#1339]
I know that this is maybe not an issue or could belong to Stackoverflow. I couldn't get an answer from Stackoverflow and i am a bit desperate so i am posting here.
I am using medium editor with a free transform tool that i wrote. 
I want to initiate the edit mode with a double click rather than a click event. 
Is there a way to do this with custom events, or should i dive in to source ? 
If i need to dive in to source, would you give me a direction to override the editableClick with a double click event, or simply a way to override any default event, some insight about medium editor source which will speed me up.

Thank you very much.

**Comment by rishijain** [comment]
Hi, Can you explain what do you mean by 'edit' mode? Do you mean the edit mode is when the editor should get instantiated?

**Comment by codeurge** [comment]
I believe you attach to double-click by doing something like this:
```javascript
this.base.on(element, 'dblclick', callbackFn)
```
