### ISSUE TITLE
Medium Editor Angular 2 Integration

### ISSUE THREAD

**Issue by torretoo** [yabwe/medium-editor#1356]
Hello All
I am facing the issue on the integration of Medium Editor getting the error like this 
`ERROR in ./~/angular2-medium-editor/medium-editor.directive.ts
Module not found: Error: Can't resolve '@angular/forms/src/directives/shared' in 'E:\XXXXX-app\node_modules\angular2-medium-editor'
 @ ./~/angular2-medium-editor/medium-editor.directive.ts 3:0-73`

After debugging It seems to like that import { isPropertyUpdated } from '@angular/forms/src/directives/shared'; is deprecated in angular 2.
Is there any example repository for Integration of Medium Editor with Angular 2

**Comment by prakfirm** [comment]
import {
    Directive,
    ElementRef,
    EventEmitter,
    HostListener,
    Input,
    OnChanges,
    OnDestroy,
    OnInit,
    Output,
    ViewChild
} from '@angular/core';
import * as MediumEditor from 'medium-editor';
const mediumEditorColorButtons = require('./medium-editor-colorpicker-buttons').get(MediumEditor);
/*
    mediumEditorColorButtons: {
        TextColorButtonClass: TextColorButtonClass;
        ColorPickerFormAbstractClass: ColorPickerFormAbstractClass;
        version: string
    }
*/
const TextColorButtonClass = mediumEditorColorButtons.TextColorButtonClass;
/**
 * Medium Editor wrapper directive.
 *
 * Examples
 * <medium-editor
 * [(editorModel)]="textVar"
 *    [editorOptions]="{'toolbar': {'buttons': ['bold', 'italic', 'underline', 'h1', 'h2', 'h3']}}"
 *    [editorPlaceholder]="placeholderVar"></medium-editor>
 */
@Directive({
    selector: 'medium-editor'
})

export class MediumEditorDirective implements OnInit, OnChanges, OnDestroy {

    @Input() editorModel: any;
    @Input() editorOptions: any;
    @Input() toolbar: any;
    @Input() editorPlaceholder: string;
    @Input() editorDisabled: boolean = true;
    @Output() editorModelChange = new EventEmitter();

    @ViewChild('host') host: any;

    // private options: any = {};
    // private placeholder: string;
    private content: string;
    private lastViewModel: string;

    private factor: number;
    private element: HTMLElement;
    private editor: any;
    private active: boolean;

    @HostListener('keyup') onKeyUp() {
        this.updateModel();
    }

    @HostListener('mouseleave') onMouseLeave() {
        this.updateModel();
    }

    constructor(private el: ElementRef) {

    }

    ngOnInit() {
        this.element = this.el.nativeElement;
        this.element.innerHTML = '<div id="angularMediumEditor">' + this.editorModel + '</div>';
        this.active = this.editorDisabled;

        if (this.editorPlaceholder && this.editorPlaceholder.length) {
            this.editorOptions.placeholder = {
                text : this.editorPlaceholder
            };
        }

        /*
         * toolbar: {
         *           buttons: ['bold', 'italic', 'underline', 'anchor', 'h1', 'h2', 'h3', 'h4', 'textcolor']
         *       }
         */
        // Global MediumEditor
        if (this.editorDisabled) {
            this.editor = new MediumEditor('#angularMediumEditor', {
                toolbar: this.toolbar,
                /*textcolor?: {
                    colors?: Array<string>;
                    moreColorText?: string;
                    pickerCloseTimeout?: number;
                },*/
                extensions: {
                    textcolor: new TextColorButtonClass(/* options? */)
                },
                buttonLabels: 'fontawesome',
                imageDragging: false
            });
        }
    }

    refreshView() {
        if (this.editor) {
            this.editor.setContent(this.editorModel);
        }
    }

    ngOnChanges(changes): void {
        if (changes[this.lastViewModel] && this.editorDisabled) {
            this.lastViewModel = this.editorModel;
            this.refreshView();
        }
    }

    /**
     * Emit updated model
     */
    updateModel(): void {
        if (this.editorDisabled) {
            let value = this.editor.getContent();
            this.lastViewModel = value;
            this.editorModelChange.emit(value);
        }
    }

    /**
     * Remove MediumEditor on destruction of directive
     */
    ngOnDestroy(): void {
        if (this.editorDisabled) {
            this.editor.destroy();
        }
    }
}

**Comment by prakfirm** [comment]
Its working fin for us

**Comment by torretoo** [comment]
Okay Thanks. How you are using extesnion of Medium Editor like table/image etc..?

**Comment by prakfirm** [comment]
I am not using any of these table/image.
