### ISSUE TITLE
Autoreplace content with rich content (hashtags to links to hashtags)

### ISSUE THREAD

**Issue by mitar** [yabwe/medium-editor#136]
I am panning to implement a feature when editor autoreplaces content with ricth/HTML content as user types it in. For example, if user types in an URL, I would like that this URL automatically becomes a link. If user types in a hashtag, I would like to automatically create a link to list of posts with that tag on my blog. If user mentions another user with @ then I would like to make a link to that user's profile page on my site. Sometimes I would like that the output text is not the same as input, for example, when you on GitHub link to a ticket with full URL, only project name and issue number are displayed, while still linking to the full URL. Same with link shorteners.

What do you think? Would this be something of interest to add to medium-editor directly? I can probably make a pull request. I would make some API to allow this to be extended and not hard-coded.

Probably #17 is first needed though.

**Comment by nmielnik** [comment]
We now have support for auto-links as of #599 

Seems like we shouldn't be too far from having mentions or other types of auto-inserted content if anyone wants to keep the momentum going :smile:

**Comment by tomchentw** [comment]
@nmielnik [Medium 2.0](https://medium.com/the-story/taking-medium-to-the-next-level-cb7f223fad86) comes out today with `@mentions` support. I think it's a good time to integrate this feature into `medium-editor` as well. I would love to give it a try and create a PR eventually.

Since I'm new to this project, could you suggest me some starting point to implement mention feature here? Thanks for the great work.

**Comment by nmielnik** [comment]
That sounds great @tomchentw .  I know @epascarello has done something like this for a project so he could definitely have some tips / suggestions related to this feature.

Though the code may be a bit dense, I would take a look at the auto-link extension ([auto-link.js](https://github.com/yabwe/medium-editor/blob/master/src/js/extensions/auto-link.js)).  This extension looks for changes in the editor and checks to see if any of the text is a valid url, and if it is it inserts a link (`<a>`).

I'm assuming you'd want something like an auto-complete dropdown to appear when you type the `@`...I'm not sure how much the auto-link will help you with that, but it might be a good reference point and something you can start with and start modifying yourself.

**Comment by tomchentw** [comment]
Thanks @nmielnik . I took a look at the docs inside `src/js/extensions/` and read through the codes there. Very helpful. It looks like the implementation of `mention` will be mixing codes from `auto-link` and `anchor-preview`. So I had my first iteration in the PR:  https://github.com/tomchentw/medium-editor/pull/1 

Currently I have two issues around so it'll be great if you and @epascarello could take a look at this. Much appreciated!

* Inside `hidePanel ()`: `FIXME: it seems that cursor position changed after unwrap`
* Where to export this `Mention` class to?

**Comment by nmielnik** [comment]
So I haven't had time to read through the code, but I would definitely recommend creating your own repo for this Mention extension.  We'd be happy to link out to your repo in our external site and our documentation, and that way you can get all the credit for your work and maybe some other people will pitch-in!

**Comment by tomchentw** [comment]
@mitar thanks. As you suggested, I released as a individual package and updated the WIKI here: https://github.com/yabwe/medium-editor/wiki/Extensions-Plugins#tcmention-for-username-or-tags

I had my code and demo there on GitHub. If anyone wants to make it more official by adding default view for mention panel, feel free to do it. Right now I'm good with a customized panel.

**Comment by mitar** [comment]
Yea!

**Comment by j0k3r** [comment]
@tomchentw Sadly the demo doesn't work :disappointed: If I type `@` or `#` nothing happen.

**Comment by tomchentw** [comment]
It should show up. Here's the screenshot:

<img width="556" alt="screen shot 2015-10-14 at 9 36 22 pm" src="https://cloud.githubusercontent.com/assets/922234/10485244/b8dd4db6-72bb-11e5-9b78-dab3f546cb20.png">
<img width="551" alt="screen shot 2015-10-14 at 9 36 32 pm" src="https://cloud.githubusercontent.com/assets/922234/10485245/b8e36a66-72bb-11e5-8cc7-2bce1a09a401.png">

I have to admit that there might be some bug with it. Please let me know if it works.

**Comment by nmielnik** [comment]
You can now use [TCMention](https://github.com/tomchentw/medium-editor-tc-mention) to accomplish this!  Thanks @tomchentw !

**Comment by tomchentw** [comment]
:+1:
