### ISSUE TITLE
Save to changes made

### ISSUE THREAD

**Issue by Erick-Zanetti** [yabwe/medium-editor#1371]
I need to save the changes that each of my users will make

I have a form where users will fill it and based on that data I will complete an HTML structure.

I wanted to deploy a way for users to edit the HTML structure and save those changes in a database, and when they reopened the page all their changes would be saved.

The main would be the user can edit only the generated structure the data that are inserted dynamically could not be edited.

I'm a little beginner so forgive my ignorance.

**Comment by krishbhattacharyya** [comment]
Hi, @Erick-Zanetti 

var allContents = editor.serialize();
var elContent = allContents["element-0"].value;

you can save the data with elContent, you have to save this in your database;

**Comment by Erick-Zanetti** [comment]
Thanks a lot, this has helped me a lot, my only doubt is now, is there any way to save just the HTML structure leaving the Angular Expression.
Example: 

`<p class="c19"><span class="c0">Residente na cidade: {{vm.formContrato.cidade.NOME}}, ate a data: {{vm.formContrato.data_proposta_desc}}</span></p>`

I'm just getting the element like this:

`<p class="c19"><span class="c0">Residente na cidade: São Paulo, ate a data: 28/06/2019</span></p>`
