### ISSUE TITLE
One has to click on the textfield

### ISSUE THREAD

**Issue by alexkangethe** [yabwe/medium-editor#1377]
### Description

- For changes to be seen one needs to first click the textfield

### Steps to reproduce

1. Add a new custom toolbar button eg image
2. Before clicking the textfield click the custom button
3. Perform the action that you want in this case add image

**Expected behavior:** [What you expected to happen]
- See the image added
**Actual behavior:** [What actually happened]
- You can't see the image until you first click on the textfield then the button

### Versions

- medium-editor: 5.21.0
- browser: chrome
- OS: mac os

**Comment by krixano** [comment]
Would you expect it to insert the image at the bottom, because without the placement of the cursor, I would image it wouldn't know where to put the image. I could be wrong.

**Comment by orthes** [comment]
That's an expected behavior. Toolbar is visible only when you select some text, because all action in the toolbar are meant to manipulate the selected text. So adding an image button to the toolbar is not a good idea. Instead take a look here: https://github.com/orthes/medium-editor-insert-plugin
