### ISSUE TITLE
Converting paragraph into header lose structure

### ISSUE THREAD

**Issue by janhui** [yabwe/medium-editor#1381]
### Description

selecting multiple paragraph and changing them to a header and then changing them back to paragraph changes the markup.

**Expected behavior:** 
it should maybe be 
```
<p> one </p>
<p> two </p>
<p> three </p>
```
goes to 
```
<h1> one  </h1>
<h1>  two </h1>
<h1>  three </h1>
```
and then to 
```
<p> one </p>
<p> two </p>
<p> three </p>
```

**Actual behavior:** [What actually happened]
```
<p> one </p>
<p> two </p>
<p> three </p>
```
goes to 
```
<h1> one  <br/>
 two  <br/>
 three </h1>
```
and then to 
```
<p> one  <br/>
 two  <br/>
 three </p>
```

### Versions

- medium-editor:
- browser:
- OS:

**Comment by orthes** [comment]
This is an expected behavior. Whatever you select gets turned into ONE <h1> element and then this one <h1> turns back to <p>, but this time it's just one. That's an expected contenteditable behavior
