### ISSUE TITLE
How to insert text into mediumeditor in specific caret position?

### ISSUE THREAD

**Issue by mkawczynski07** [yabwe/medium-editor#1382]
### Is any way to insert text into mediumeditor in specific caret position? 

I have buttons out of medium editor which should add paragraphs to medium in the last caret position.

**Comment by orthes** [comment]
There is. First move caret to the desired position using [MediumEditor.selection.moveCursor()](https://github.com/yabwe/medium-editor/blob/master/src/js/selection.js#L647) function and then use [MediumEditor.util.insertHTMLCommand()](https://github.com/yabwe/medium-editor/blob/master/src/js/util.js#L443) to insert HTML.
