### ISSUE TITLE
Can you create a second row of toolbar buttons on click?

### ISSUE THREAD

**Issue by lindlymatt** [yabwe/medium-editor#1386]
Hey there,

I was hoping I could pick some brains about how to make this happen, just to see if I could get some inspiration while I work on it myself. Basically, I'm wanting to implement a "text" button that when clicked:

1. Opens a second row of toolbar buttons/options that directly effects the text that is selected. 
2. Shows a form for a portion of it, and "header options" for the second part of it. 

Here's a couple of examples of what I'm talking about: 

1. Before clicked, but text is highlighted: https://imgur.com/2WjrZqf
2. After clicking the "T" button: https://imgur.com/TdxR7hm
3. An example of the fontName drop-down: https://imgur.com/1RLeopv

Any help/ideas would be greatly appreciated!

**Comment by lindlymatt** [comment]
I'm using a max-width and hard-coded width values to get the second row to appear, but is there any way to basically have the fontName form on the left side of the buttons, or just to have it work inside of the toolbar itself (without closing/removing the rest of the toolbar on click) and basically just have the form itself nested in the toolbar?

Example: https://imgur.com/Yv6wVwG

**Comment by orthes** [comment]
No, currently there's no built-in way that I know of to do this
