### ISSUE TITLE
Deleting images

### ISSUE THREAD

**Issue by SVyatoslavG** [yabwe/medium-editor#1387]
### Description

Image is Being removed hitting BACKSPACE editing the caption. When caption is empty.

### Steps to reproduce

1. Add image to your article.
2. Click on the figcaption of the image.
3. Type anything then try to remove all characters.
4. Unselect image.
5. Select figcaption
6. Hit backspace.

**Expected behavior:** Nothing suppose to happen image is not supposed to be removed.

**Actual behavior:** Removing image

**Link to an example:** http://linkesch.com/medium-editor-insert-plugin/
### Versions

- medium-editor: latest
- browser: chrome
- OS: mac os

**Comment by orthes** [comment]
This is a bug in the insert plugin, not in the editor itself. Post this bug report there instead: https://github.com/orthes/medium-editor-insert-plugin
