### ISSUE TITLE
Edit Source Code Option (to add custom HTML/CSS)

### ISSUE THREAD

**Issue by movationdesign** [yabwe/medium-editor#1400]
Hi, this editor would be incredible if we could toggle between normal writing mode and access to source code with HTML and CSS — like you can in WordPress (Visual/Text) in writing mode.

This way we could write normally in the editor for most things but then add custom markup or classes to our source whenever we need it for our content.

**Comment by orthes** [comment]
@movationdesign That's a great idea, but out of the scope for this project. Feel free to use medium-editor for the WYSIWYG part and find a good open source code editor with syntax highlighting for the "text" mode and toggle between them.

**Comment by bhadaway** [comment]
I've actually got this started, if someone can help me complete it: #1507.
