### ISSUE TITLE
IE11 won't show anchor toolbar

### ISSUE THREAD

**Issue by spiderpug** [yabwe/medium-editor#1402]
### IE11 won't show anchor toolbar

One of the recent IE11 updates broke the anchor/link toolbar. Before version 11.0.48 it was working fine.

### Steps to reproduce

1. select any text
2. click the anchor icon in the open toolbar

**Expected behavior:** The anchor/link toolbar is now showing.

**Actual behavior:** The anchor/link toolbar is not visible. It does not show up as `medium-editor-toolbar-active` is missing in the DOM. You can only see the blinking cursor.

**Link to an example:** Medium Demo

![medium-ie11](https://user-images.githubusercontent.com/2295856/34555192-bef27a28-f130-11e7-8251-f9b8619b9fe1.gif)

### Versions

- medium-editor: 5.10.0, 5.23.0
- browser: IE 11, 11.0.9600.18837, 11.0.48
- OS: Windows 7 (TestDrive)

**Comment by surebert** [comment]
This is a temp solution till a fix is made.  

If you comment out line in the toolbar.js extension it fixes it

https://github.com/yabwe/medium-editor/blob/eef3ee0224a07121799f9d1389b3be4d1020937f/src/js/extensions/toolbar.js#L223   

In the dist src its on line 6041
https://github.com/yabwe/medium-editor/blob/eef3ee0224a07121799f9d1389b3be4d1020937f/dist/js/medium-editor.js#L6041

```js
//this.subscribe('blur', this.handleBlur.bind(this));
``

<img width="983" alt="screen shot 2018-01-08 at 23 29 50" src="https://user-images.githubusercontent.com/1123857/34705096-d86e38ae-f4cb-11e7-9cf8-4537c6a45004.png">

I tested in chrome, firefox and safari on Mac and on IE 11 and it seems to solve the IE 11 issue without causing any additional issues in the other browsers.

I would make a pull request but I am not sure how this project tests work yet.  FIgured this might help someone else in the meantime

**Comment by spiderpug** [comment]
This is now working again, without code changes, in IE11 `11.0.9600.18977` (11.0.56)
