### ISSUE TITLE
Delete quote on backspace

### ISSUE THREAD

**Issue by websirnik** [yabwe/medium-editor#143]
When the cursor is at the beginning of the quote, I see users trying to delete the quote by pressing backspace. I think this make sense and this flow should be enabled by default.

![](http://cl.ly/image/0c1j3W2y153Q/Screen_Shot_2014-02-11_at_16_56_05-4.png)

**Comment by rishijain** [comment]
I think it is already fixed for list. I have added a fix for quote in the PR https://github.com/yabwe/medium-editor/issues/879
