### ISSUE TITLE
Medium editor is wrapping <p> tag inside a <div> on pressing ENTER key in latest firefox(v60.0.2)

### ISSUE THREAD

**Issue by himanshuamoli** [yabwe/medium-editor#1450]
Note: This is a bug in latest firefox (v60.0.2)

Medium editor is wrapping the "p" tags inside "div" tags when ENTER key is pressed.
![image](https://user-images.githubusercontent.com/6461541/41652825-e0631c5e-74a1-11e8-9ec2-9af24c7d1f98.png)

**Comment by himanshuamoli** [comment]
This issue not replicable in medium editor version v5.23.3. Demo site still uses v5.23.0 in which this bug is present.

**Comment by zaiddabaeen** [comment]
I can replicate the issue on 5.23.3.
Also reported here: https://github.com/yabwe/medium-editor/issues/1459
