### ISSUE TITLE
How to implement html toggle button?

### ISSUE THREAD

**Issue by fpytloun** [yabwe/medium-editor#1456]
### Description

I am using medium-editor in Saleor project and I wonder if it's possible to implement `Toggle html editor` button and how?
I suppose it would be only simple Javascript call but I was not able to find any guidance in docs and I am not skilled at Javascript coding.

Relates to https://github.com/mirumee/saleor/issues/2347

### Steps to reproduce

1. Setup editor
2. Try to look for `toggle html` button

**Expected behavior:** Button or way how to enable/disable medium editor

**Actual behavior:** No button

### Versions

- medium-editor:
- browser:
- OS:

**Comment by stefanpejcic** [comment]
Hi @fpytloun I've used javascript to enable such a button on each post in WordPress.
Please take a look at [this example](https://github.com/PluginsBay/medium-editor/tree/master/).
