### ISSUE TITLE
how to preset H2 and Paragraph on an empy editor

### ISSUE THREAD

**Issue by buty619** [yabwe/medium-editor#1506]
a want to know if it's possible to preset an h2 and p on a empty editor just like when start a medium story, thanks team¡

**Comment by rdeprey** [comment]
Hi @buty619, Yes, you could preset an h2 and p on an empty editor like starting a Medium story, but the user would need to remove the placeholder text. I'm a new contributor to the project and don't think that we currently offer the placeholder text feature in the same way that Medium does. We will consider this for the future.

Here's a quick example of one option for doing something along these lines though: https://codepen.io/radiantsunrise08/pen/pmpXwp.
