### ISSUE TITLE
I write a new funtion, which can paste img from clipboard to data-uri, but I don't know how to pull it in.

### ISSUE THREAD

**Issue by pondahai** [yabwe/medium-editor#1508]
### Description

A new funciton. It is can paste image from clipboard and become the data-uri

### Steps to reproduce

I put my code here. 
https://gist.github.com/pondahai/fd068f2669e12e8dd83258697e431049

**Comment by stefanpejcic** [comment]
Hi @pondahai great to see you contributing to the medium editor.
Can you please join us on our [glitter channel](https://gitter.im/yabwe/medium-editor) Thanks
