### ISSUE TITLE
strike through

### ISSUE THREAD

**Issue by mandevx** [yabwe/medium-editor#1511]
### Description

[Description of the bug or feature]

### Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Link to an example:** [If you're reporting a bug that's not reproducible on our [demo page](https://yabwe.github.io/medium-editor/demo.html), please try to reproduce it on [JSFiddle](https://jsfiddle.net/), [JS Bin](https://jsbin.com), [CodePen](http://codepen.io/) or a similar service and paste a link here]

### Versions

- medium-editor:
- browser:
- OS:

**Comment by stefanpejcic** [comment]
@mandevx please add more information about this issue

**Comment by duke7able** [comment]
@mandevx since now more info is not provided I am closing the issue for now, you can create a new issue if this persist with some details in the issue, thanks
