### ISSUE TITLE
get content from multiple editor

### ISSUE THREAD

**Issue by shankar-bavan** [yabwe/medium-editor#1525]
### Description

I have more than one editor in one page. How do I get content from a specified editor.
for example, If I edit 3rd editor, I need to get that content

### Steps to reproduce
I tried below method. but, It always take 1st content. I need to get content from what I am editing.
How can I pass id from view file? 
```
    editor.subscribe('editableInput', function (event, editable) {
        var contents = editor.getContent();
    });
```

**Comment by rossb-mmt** [comment]
According the documentation: 

> .getContent(**index**): gets the trimmed innerHTML of the element at **index**

So if you want the 3rd editor, I presume that would be
```
editor.subscribe('editableInput', function (event, editable) {
        var contents = editor.getContent(3);
    });
```
