### ISSUE TITLE
We got sponsored by BrowserStack. Someone up for Tests?

### ISSUE THREAD

**Issue by sauravkhdoolia** [yabwe/medium-editor#1548]
Hey guys,

Wanted to tell yal, BrowserStack gave us their suites for FREE.

As our previous tests were failing due to sauce labs, and I trust BrowserStack way more than SauceLabs...

Can someone go ahead and port our project to BrowserStack, as i dont have much experience doing the same!

Also, I think we should start using Mocha instead of Jasmine!

Thoughts?

**Comment by arteconceito** [comment]
I could take it as a next todo but I will need some kind of access credentials to BrowserStack in order to set it up.

**Comment by sauravkhdoolia** [comment]
@arteconceito GIve me your email id, I'll add you there.
