### ISSUE TITLE
Unsorted node styles disobey the rules described in `Why ContentEditable Is Terrible`

### ISSUE THREAD

**Issue by zxch3n** [yabwe/medium-editor#1562]
### Description

In the post [Why ContentEditable Is Terrible](https://medium.engineering/why-contenteditable-is-terrible-122d8a40e480), it stated that:

> When we translate markup ranges into DOM nodes, we sort them by type: A, then STRONG, then EM. We will never print a STRONG tag containing an anchor. We break it up so that the anchor contains the STRONG tag.

However, I found that this editor doesn't obey this rule. May I ask why?

**Comment by sovkay** [comment]
no particular reason, When the editor was made idt the post was there...

And You can always get a PR up if you think it'll help.
