### ISSUE TITLE
It's possible to show toolbar ontop of the textarea ALWAYS?

### ISSUE THREAD

**Issue by komen205** [yabwe/medium-editor#1568]
### Description

Instead of having the toolbar showing when I select text. I want it to always show at the top.
Is there any setting for that?

**Comment by ahmedrafayat** [comment]
@komen205 Yes, there are a few options that might help you with this.
Referring to the options mentioned in [here](https://github.com/yabwe/medium-editor#toolbar-options),
In your toolbar options try setting `static: true` and `align: 'top'`.
