### ISSUE TITLE
I want to retrieve currently selected text after clicking a button

### ISSUE THREAD

**Issue by ct1735x** [yabwe/medium-editor#1579]
### Description

I want to retrieve currently selected text after clicking a button. 
Example when I click on the "bold" button, I want to get the text that has been bolded

I don't know which object or which accessor use
I tried MediumEditor.getFocusedElement() , editor.getFocusedElement() , both of them return like my whole html code which is not what I want to do. After clicking, the MouseEvent object has a lot of attributes and I cant seem to find the right one

Any help?

**Comment by 2klm** [comment]
Solved! Solution is : 

`this.getEditorElements()[0].childNodes[0].children[0].innerText`
