### ISSUE TITLE
Shift + Enter in Safari

### ISSUE THREAD

**Issue by porioli** [yabwe/medium-editor#195]
Hi,
in Safari (7.0.2) and Mavericks if I hit SHIFT + ENTER keys the editor creates a new paragraph instead of simply adding a `</br>`.

**Comment by nmielnik** [comment]
This should get fixed whenever #70 is resolved

**Comment by hellocosmin** [comment]
Does it do the same if you set `display: inline-block;` for your `.editable` element?

**Comment by sedletsky** [comment]
@hellocosmin yes

**Comment by mikebronner** [comment]
I am experiencing this as well in Safari 9.1.1 and 9.1.2. The behavior of SHIFT-ENTER vs ENTER is flawed (works fine in Chrome). If you start off pressing SHIFT-ENTER everything will be fine until you hit ENTER. That will add 

```
<br>
<p><br></p>
<br>
```

directly after the spot you hit enter, and it won't push the cursor to the end, but just before the opening `<p>` tag. If you start typing or hit SHIFT-ENTER everything is hopelessly messed up.

However, if you don't type, but move the cursor to then end, SHIFT-ENTER will continue behaving as normal -- until you hit ENTER again. Rinse and repeat.

Hopefully this helps somewhat in troubleshooting the issue and maybe coming up with a script that attempts to fix Safari's ill behavior. :)
