### ISSUE TITLE
IE10 misplaced cursor

### ISSUE THREAD

**Issue by musshush** [yabwe/medium-editor#206]
On IE10 while placeholder text is showing the cursor is misplaced above the placeholder text.
![previewscreensnapz001](https://cloud.githubusercontent.com/assets/864185/2730542/859ef2a4-c61b-11e3-83d6-dc09cc7bd29d.png)

And if you press a few enter key, the cursor is misplaced under the actual content editable area
![parallels desktopscreensnapz002](https://cloud.githubusercontent.com/assets/864185/2730548/a2196374-c61b-11e3-8e6a-cd59b7b0efd2.png)

These don't happen on IE9.

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
