### ISSUE TITLE
Double newlines getting removed on paste

### ISSUE THREAD

**Issue by timhaines** [yabwe/medium-editor#211]
Hi there,

In google chrome, I've tried pasting the following in to the example:

```
1

3


6
```

You'll note there's 2 empty lines between the 3 and the 6.  When this is pasted in to medium editor, the empty lines aren't maintained.  Is there an option I need to enable to maintain these, or is this a bug?

**Comment by nmielnik** [comment]
I believe this has been fixed, please comment if this is still an issue and we will re-open this.
