### ISSUE TITLE
header elements end up with internal <span> elements after certain editing sequences

### ISSUE THREAD

**Issue by adriand** [yabwe/medium-editor#232]
There is a predictable way to turn header elements, e.g.:

    <h3>Title</h3>

Into elements with internal spans, e.g:

    <h3>
      <span style="font-size: 22px;">Title</span>
      <br>
    </h3>

This is done as follows:

1. Create two lines of text.
2. Highlight the first line of text and make it an h1.
3. Move the cursor to the start of that line and press enter, moving that line down by a single line break. The h1 formatting will be removed.
4. Move the cursor back to the start of the first (now empty) line.
5. Press shift-delete or fn-delete or whatever, to "delete forwards", i.e. to delete in such a way that the second line moves back up to the top line position

When this line regains top line position, it will have re-acquired the header formatting, but will also have acquired a span element with a fixed, inline font-size declaration.

**Comment by sangsteroni** [comment]
I encountered this problem too and it was much more than an annoyance. When the <span> is created inside a <p> after a delete of the previous <p> and if it just happens that the content enclosed by the <span> is hyperlinked, the <a> is correctly nested inside the <span> when still in edit mode. 

But when the content is submitted, there appears to be some incorrect stripping of the enclosed <a> tag, leading to the <a> attributes merging with the content and showing up as gibberish. This was on Safari.

Using @steoo 's recommendation to unwrap <span> on submit worked really well. Thanks a bunch, @steoo.

**Comment by steoo** [comment]
@sangsteroni no worries :) 
By the way I must say that I did not used this hack then, beacuse it breaks the natural behaviour. I guess we have to find a cleaner solution to this problem.

**Comment by pedrosanta** [comment]
Hi there, +1 here with this annoyance.

From what I can see this is dependent of deep changes in the editor - that's a bummer.

Anyways, I've managed to have a similar awkward behaviour that turns a:

    <h3>Nice Header</h3>

Into:

    <h3>Nice&nbsp;<span style="color: inherit; font-family: inherit; line-height: 1.1; font-size: 14px;">Header</span><h3>

With nasty visible bug, the text in the span is smaller than the rest of the heading.

The way to get this is:

1. Write 'Nice Header';
2. Make it a H1;
3. Place the cursor before 'H';
4. Hit return, generates a second header below all right;
5. Hit backspace, merges the lines into a header but leaves behind a span with inline style;
6. Hit return, generates a *paragraph* below with the span with inline style inside;
7. Hit backspace, merges the lines into a header but leaves behind a span, this time with a `font-size: 14px` on the inline style;

If you continue to keep hitting return and backspace it remains cycling on the 6 and 7 steps.

**Comment by antoniobrandao** [comment]
@pedrosanta In which browser did you see that behaviour? Did you find any difference in other browsers?

**Comment by pedrosanta** [comment]
@antoniobrandao It was on Chrome 42. On Firefox works fine though. When we hit the backspace (5) it merges the two lines on a heading without the inline styled span. Also relevant, I'm using angular-medium-editor (https://github.com/thijsw/angular-medium-editor). I'll try to put in place vanilla medium editor when I can, and sort out if still happens.

**Comment by mywaiting** [comment]
+1 please

**Comment by shanetmoore** [comment]
+1

I just got hit too. Nasty little bug this one.

**Comment by steoo** [comment]
In my opinion this should be classified as **bug**,of `contenteditable` of course, but our mission is to fix bad behaviour of this bad guy or not? :)

**Comment by nmielnik** [comment]
I've created a 'htmlcleanup' label as a way to group together any cross-browser, contenteditable issues that we may want to try to fix via some markup cleanup in medium-editor.

This seems like a great candidate to try to cleanup.  There are also lots of other [browser inconsistencies](https://github.com/guardian/scribe/blob/master/BROWSERINCONSISTENCIES.md) we may want to fix moving forward as well.

**Comment by shanetmoore** [comment]
Feel like I just whacked the hive.

@steoo Here Here!

@nmielnik One other piece I don't see listed in that doc is the difference between text-align commands. Chrome interprets the command and uses text-align (which is what I would expect).
Firefox interprets this differently and uses an 'align' attribute which isn't respected on all browsers. 

So If you save the generated HTML as a document in firefox, it can't be opened by Chrome.
However vice versa works just fine.

Not sure if this is an inconsistency or not but thought it was worth mentioning.

**Comment by nmielnik** [comment]
Yeah, this is definitely and issue I've run into, especially while working with @steoo on #675 

I'm not sure if we have a specific issue opened to track this problem, if we don't would you be interested in creating one?

**Comment by steoo** [comment]
@nmielnik Great, I'm sure this will help

**Comment by steoo** [comment]
@nmielnik @shanetmoore I'm thinking about a solution to the `align` problem with the support of Rangy Class Applier Module ( https://github.com/timdown/rangy/wiki/Class-Applier-Module ). I think it can be an extension, if someone wants to join me, he's welcome.

**Comment by nmielnik** [comment]
Something I've been mulling is whether we could have our own implementation of the class applier.  There was a lot of code added as part of the autolink feature which actually gets us most of the way to our own custom class applier-like functionality, it just needs some additional love.

In the meantime, using another extension that has a dependency on rangy sounds like a great idea, and I'd be happy to help if time permits!

**Comment by steoo** [comment]
I made this gist, check it out
https://gist.github.com/steoo/6aa45e6c6d99974fbd2d

**Comment by j0k3r** [comment]
Here is an other issue about that point: https://github.com/yabwe/medium-editor/issues/543
And I've started something here, still not finished by the way: https://github.com/yabwe/medium-editor/pull/801
