### ISSUE TITLE
Cursor position bug in firefox

### ISSUE THREAD

**Issue by treblam** [yabwe/medium-editor#234]
Make an editor with empty text. Then focus the editor in firefox, the cursor position is higher than the placeholder. Then I input some text in it, the cursor position become normal.

**Comment by nmielnik** [comment]
I was not able to reproduce this anymore, please re-open and include more repro steps if anyone is still have this issue.

**Comment by balvig** [comment]
Unfortunately this still seems like an issue in 5.10.0 using Firefox and the placeholder `hideOnClick: false` option :cry: :

![demo](https://cloud.githubusercontent.com/assets/104138/11337627/a7ef8274-91ee-11e5-8cc7-a999e9b4f19b.gif)


Fiddle: https://jsfiddle.net/wooLksnx/

**Comment by enparticular** [comment]
any news regarding this issue? just found it and it's really really difficult to fix. our website uses lots of the editable function and it looks so strange in firefox.

**Comment by antoniobrandao** [comment]
I moved to Trix because of this issue.

**Comment by nmielnik** [comment]
The behavior in firefox is being tracked as a bug: https://bugzilla.mozilla.org/show_bug.cgi?id=904846, still looking through workarounds as it looks like a bunch of folks have run into this with contenteditable

http://stackoverflow.com/questions/27093136/firefox-contenteditable-cursor-issue
http://stackoverflow.com/questions/21986985/firefox-sets-wrong-caret-position-contenteditable-on-focus
