### ISSUE TITLE
How do I add a color picker button?

### ISSUE THREAD

**Issue by z115corporation** [yabwe/medium-editor#257]
Shall I create color picker button myself as an extension? Thanks

**Comment by Boycce** [comment]
Hey @Dayjo I can't seem to locate the forked repo.

**Comment by Dayjo** [comment]
@Boycce Here's how we do it; https://github.com/createdotnet/dyos_html/blob/master/_assets/js/page-builder/source/dependencies/medium-colour-picker.js#L32

However this is very specific to our colour picker plugin (not included), the line i've linked to is our own function, and the anonymous function is when you select a colour in our colour picker. 

Just a concept really, would need to find the colour picker you want to use and implement it.
