### ISSUE TITLE
Do not allow dragging images (or other content) into editor, or at least sanitze content dropped.

### ISSUE THREAD

**Issue by chanon** [yabwe/medium-editor#260]
While medium-editor with forcePlainText on doesn't allow pasting of images into the editor via Ctrl-C/Ctrl-V or browser menu copy/paste, it is still possible to drag images into the editor.

Actually, it isn't limited to just images, I just tried dragging this whole input form from Firefox into the medium-editor demo that I had open in Chrome and I had some text inputs and text areas inside the medium-editor!

Ideally medium-editor should sanitize the input the same way it does to a clipboard paste.

**Comment by nmielnik** [comment]
By default, dragging anything other than images into the editor is prevented.  Images can also be prevented by using the following option:

```js
new MediumEditor('.editable', {
    fileDragging: {
        allowedTypes: []
    }
});
```
