### ISSUE TITLE
Auto-capitalization

### ISSUE THREAD

**Issue by websirnik** [yabwe/medium-editor#262]
Not sure whether it should be a part of the editor.
I got requests from users that it would be great to have an auto-capitalization when you start a new sentence. Basically change a lowercase letter to a capital letter each time after `.`. Just like you have in MS Word.

**Comment by nmielnik** [comment]
I think this would be something to add in a custom extension.  If someone opened a PR which would enable this in the core editor, I think we'd consider taking it, but I don't think this is a realistic feature ask as of now.
