### ISSUE TITLE
When disableDoubleReturn: true, there is no way to get out of ordered/unordered list.

### ISSUE THREAD

**Issue by mingfang** [yabwe/medium-editor#273]
When disableDoubleReturn: true and you start an ordered or unordered list, you will not be able to press enter on an empty list item to exit list mode.

**Comment by cihad** [comment]
+1

**Comment by rishijain** [comment]
I think this has been covered in this. https://github.com/yabwe/medium-editor/issues/831

**Comment by j0k3r** [comment]
@rishijain Yup
