### ISSUE TITLE
Get the tab key to add whitespace instead of losing focus on the div

### ISSUE THREAD

**Issue by sferoze** [yabwe/medium-editor#274]
When the cursor is inside the content editable div and I press tab, the div loses focus and shift over to the next hyperlink on the page. 

When I try to intercept the key event and use 

```
'keypress .editable': (e) ->
    if e.keyCode is 9 
      e.preventDefault()
```

The div still loses focus and I also get a console error: 

Uncaught TypeError: Cannot read property 'tagName' of null 

So how can I get the tab key to work similar to a normal text editor like word or something?

**Comment by duncanmudulo** [comment]
Nice
