### ISSUE TITLE
Adding URLs does not work in Modals

### ISSUE THREAD

**Issue by hilem** [yabwe/medium-editor#284]
Using Medium-Editor in a modal.  Most everything works as expected except URLs.  Double-clicking a word to bring up the menu is fine.  Clicking the 'url' icon will bring up the 'paste a url' box, however it will not be focused and any attempt to click within the box will close everything.  This has been happening on all versions for at least roughly the past 5-6 months back.  Same behavior seen in latest Chrome & Firefox on Mac.  Using 'pause on exceptions' seems to indicate that everything is missing a generic getAttribute method.  Any advice?

**Comment by Padam87** [comment]
@chandrewz Thank you! tabindex removal FTW
