### ISSUE TITLE
Link on image

### ISSUE THREAD

**Issue by IonicaBizau** [yabwe/medium-editor#312]
Let's supposed I already have an image loaded in div editable area.

How can I attach a link on it?

I know that by selecting the image this is possible, but I'm searching for a *more friendly* way.

**Comment by nmielnik** [comment]
This was fixed in #904 and should be available since version 5.12.0

**Comment by IonicaBizau** [comment]
@nmielnik Thanks! :+1:

**Comment by nmielnik** [comment]
Yup, apologies for not updating this issue a few months back when it actually got fixed :stuck_out_tongue_winking_eye:

**Comment by IonicaBizau** [comment]
Hehe, no worries. :grin:
