### ISSUE TITLE
Link editor broken in bootstrap modal

### ISSUE THREAD

**Issue by FrivalszkyP** [yabwe/medium-editor#315]
Hello,

Here's a test link that speaks more than words: http://index.hu/demo/kepadminapp/app/index.html

If you open up the modal window and try to insert a link, it doesn't work. Here's what I've been able to find:

* for some reason the checkSelection event handler runs four times when I click the anchor button. 
* however if I try to debug it by inserting a breakpoint in the checkSelection function, it only runs once, making it impossible for me to determine which event triggers the checkselection

I can reproduce the bug any time in Chrome on Windows 7/8. Firefox sometimes seems to work, but I am unable to focus the achor input field. Maybe it is a totally different bug than what I checked in Chrome, but it also happens when I embed the editor in a bootstrap modal window. 

Can you help me please? Or should I just simply abandon using the editor in a modal window?

**Comment by cjch0** [comment]
I've had this issue as well. Turns out it was some bootstrap css that was causing weird behavior with the editor toolbar. Not sure exactly which css, I just stopped trying to run it in a modal

**Comment by FrivalszkyP** [comment]
Thanks! That was my solution too.

**Comment by nmielnik** [comment]
I'd like to point out @FrivalszkyP , the demo is very cool and I enjoyed playing around with it a bit.

We've made some changes around the anchor handling, if you have any time to try to reference the latest version, I would be curious if this issue still is reproducible.

If it is, I would like to investigate what could be causing this.

**Comment by sslover** [comment]
Hi all,

Just wanted to chime in that this is still happening on Bootstrap Modals. When you click to insert a link, you do get the input field:

<input type="text" class="medium-editor-toolbar-input" placeholder="Paste or type a link">

But it is impossible to focus the anchor input field.

I've been looking into solutions, but no success just yet.

**Comment by NikitaCh** [comment]
Hi all,

Have same issue as @sslover in FireFox (latest version).
 
And in IE anchor input not shown at all.

Have you found any workaround ?

Thanks.

**Comment by daviferreira** [comment]
Played around with this and one thing that fixed the behavior for me on FF was setting the elementsContainer to the modal element. Could you guys give that a shot and see if it fixes all the modal problems?

```
var editor = new MediumEditor('.editable', {
  buttonLabels: 'fontawesome',
  elementsContainer: document.getElementById('medium-editor-modal')
});
```

**Comment by NikitaCh** [comment]
Hi @daviferreira 

It works! Thanks! 

But position of toolbar calculates not good.

Thanks.
