### ISSUE TITLE
Unlink not working in any IE

### ISSUE THREAD

**Issue by hellocosmin** [yabwe/medium-editor#368]
Tested and confirmed on the demo page as well, in IE11:

- select text
- make a link out of it
- try to unlink your selection it as you would usually do, by clicking the link button again. It doesn't matter if you select something else or click elsewhere and then come back to re-select the text and unlink it.

As you can see, it just opens the add link input again, it does not detect that the selection is an anchor. Toolbar button state is also not updated.

Works as intended in Chrome/Firefox/Safari.

**Comment by nchase** [comment]
this is interesting. looks like the `getSelectedParentElement` method defined [here](https://github.com/daviferreira/medium-editor/blob/master/src/js/medium-editor.js#L1383-L1394) is returning an unexpected parent in IE.

Are you instantiating medium-editor with any particular options, or using the defaults?

**Comment by nchase** [comment]
So I no longer think this a bug in medium-editor (the same code paths get executed in either browser), but it is certainly a real issue.

Here's what is happening if you want to try to reproduce: when you double-click a word in IE, IE chooses to select a slightly different range of text. Notice that it selects your word _plus_ the adjacent whitespace character to the right of the word. This behavior is different from other browsers, and it confuses the code that figures out whether or not the user has a link selected. You and your users will notice that if they select some smaller range inside of the word, and then click the unlink button, it will work as you expect.
 
I've had reason to want to normalize this selection difference between IE and other browsers in the past. This makes me feel a little bit stronger to that end. I wonder to what degree (if any) this is something that Tim Down's Rangy does or if this kind of normalization could be a part of medium-editor.

**Comment by nmielnik** [comment]
This is the same issue as #259
