### ISSUE TITLE
How to define editor buttons dynamically?

### ISSUE THREAD

**Issue by hellocosmin** [yabwe/medium-editor#385]
Hi,

Let's say I have a div for which I want to specify the allowed editor buttons. Here's what I tried, mixing in jQuery:

`<div class="editable" data-editor-buttons="bold,italic,underline">...</div>`

Call Medium Editor:

<pre>var mEditor = new MediumEditor('.editable', {
                buttonLabels: 'fontawesome',
                buttons: allowedBtns,
                cleanPastedHTML: true,
                disablePlaceholders : true,
                checkLinkFormat: true
            });</pre>

When a user clicks an .editable div, I want to check for data-editor-buttons and update the mEditor object on the fly, so it shows only the buttons I want:

<pre>$(document).on('click', '.editable', function(e){

var specifiedBtns = $(this).data('editor-buttons');

		switch (specifiedBtns) {

			case undefined:
			case "":
				allowedBtns = ['strikethrough', 'subscript', 'superscript', 'bold', 'italic', 'anchor', 'orderedlist', 'unorderedlist'];
				break;

			default:
				allowedBtns = specifiedBtns.split(",");
			break;

		}

                mEditor.deactivate();		
		mEditor.options.buttons = allowedBtns;
		mEditor.activate();
});</pre>

It works if I deactivate() and activate() mEditor.

Problem: when testing this in Chrome, the editor toolbar seems to be losing its positioning coordinates and jumps to the top left of the screen. It works fine in Firefox/IE.

Is there any way to either fix this in Chrome, or update the object without using deactivate/activate? (seems to be that Chrome is doing this when I deactivate() )

Any insight will be appreciated, thanks for taking the time to read :)

**Comment by nmielnik** [comment]
Does a 2nd click into the div fix the position of the toolbar?

It's possible the cause is because medium-editor looks to `mouseup` and `click' events on the editable element for positioning the toolbar.  If you're deactivating, and activating medium-editor on a `click` event, the "activated' version of your toolbar will not have any events to trigger it to position itself.  Since the toolbar gets deleted from the DOM in `deactivate()` and re-added in `activate()` it seems likely the behavior of the toolbar could differ from browser to browser.

Perhaps deactivating and reactivating on `mousedown` instead of click could also fix this?

**Comment by hellocosmin** [comment]
Tried with mousedown as well, there was no difference.

A second click does hide it properly. I'll look into it more and post any results here...

**Comment by hellocosmin** [comment]
Messed around some more and seems I got it working :)

I deactivate() and set the new buttons in the `mousedown` event.
Then, in a separate code block, I activate() on `mouseup`. Problem solved for Chrome!

This is tied with enabling Medium Editor on dynamically inserted elements in my case, so I'll open a new issue for that. Thanks for the nice explanation and `mousedown` suggestion :)

**Comment by hellocosmin** [comment]
I actually need to reopen this, as it seems that manipulating the mEditor object like that results in certain actions not working in Firefox.

See Fiddle: http://jsfiddle.net/ongk3utq/5/

As you can see, setting the editor buttons dynamically like that, breaks the functionality of some toolbar buttons in Firefox. I've confirmed these to stop working: justify (all), ordered and unordered lists.

- it works perfectly fine in Webkit
- IMPORTANT: if the .editable is a `<div>`, then it works in Firefox too. But only if it's a div. Any other element, no matter if block or inline, won't work.

I admit I'm not that good with JS/jQuery, this is the only way I could think of in order to show custom toolbar buttons depending on the element that's being edited.

If anyone has any advice, I would surely appreciate it. :)

**Comment by hellocosmin** [comment]
Implemented a hackish workaround in the end : if the browser is Firefox, I'm first wrapping the editable's contents in a div and activate ME on that div. Cleaning the output for the user is just a matter of unwrapping this div's contents (using jQuery), seems to work fine.

I'll be leaving this open for any thoughts, though.

**Comment by nmielnik** [comment]
See #797 for an extension that creates the basis for this kind of functionality.  Others can use that extension as a starting point and/or fully build out an extension for supporting this (please let us know if you build any external extensions so we can link to it).
