### ISSUE TITLE
[Request] When hitting return key 2 or x times insert element and disable return-key

### ISSUE THREAD

**Issue by tkjaergaard** [yabwe/medium-editor#42]
Like on Medium when you hit the return key 2 times a `<hr>` element is inserted on the empty line just above and return-key are disabled until text has been typed.

The `<hr>` could perhaps be any element set through the options object and the number of allowed empty lines could be as well.

**Medium example:**
--

![Medumm Example](http://f.cl.ly/items/1T3o2N3k2H1g2j3q2w3L/Image%202013.10.03%2010.29.02.png)

--

It's helping the user to create nicely formatted and a schematic layouts.

**Comment by j0k3r** [comment]
@tkjaergaard I can't reproduce what you said about medium.com when I hit the return key 2 times, it does nothing like you say.

BTW there is now a `disableDoubleReturn` option that can disable mutliple empty lines.

**Comment by nmielnik** [comment]
Haven't heard back on this one, closing this issue for now.
