### ISSUE TITLE
Extra <p> content wrapper generated for headings

### ISSUE THREAD

**Issue by godlovesugly** [yabwe/medium-editor#484]
Hi,

It's the first time when working with this editor and can't figure out how to prevent it from wrapping the content of heading elements inside paragraph (`<p>`) tags.

Here's what I'm talking about: http://codepen.io/andreiamar/pen/Byqewb

```
<h1 class="editable" ... >Heading H1</h1>
```

turns into

```
<h1 class="editable" ... ><p>Heading H1 edited</p></h1>
```

I'd appreciate it if anyone would help me to correct this behavior.

**Comment by nmielnik** [comment]
@godlovesugly can you detail what behavior causes this to happen?  I see the codepen, but I'm not sure what actions resulted in the `<h1>` tag getting messed up.

**Comment by godlovesugly** [comment]
I'm also trying to figure that out. As you can see, I'm simply initializing the medium editor on all tags having the 'editable' class, then when editing the html, it gets wrapped in a <p> tag. I've decided to not use this plugin for now, but still the problem remains.

**Comment by daviferreira** [comment]
@godlovesugly You need to disable return: http://codepen.io/daviferreira/pen/zxyNGw

You can also use ```data-disable-return``` on the elements. But I will leave this open, I think we should handle it on our side.

**Comment by ArsalanBashir** [comment]
@daviferreira A quick ugly hack for fixing this is to manually style the <code>.yourClass p</code> tag to meet the styles and go ahead. I'll look into the <code>data-disable-return</code>.
