### ISSUE TITLE
Feature Request: links options

### ISSUE THREAD

**Issue by brazorf** [yabwe/medium-editor#501]
It would be great to set extra attributes on each link, such as "target" and "title".

**Comment by nmielnik** [comment]
So there is currently an option `targetBlank` which when set to true, makes every anchor created set target="blank".

There is also a `anchorTarget` option (which apparently is not documented), which when set to true, displays a "open in new window" checkbox (text is configurable via the `anchorInputCheckboxLabel` option) in the anchor form which the user can check and make the anchor open in a new window.

I'll add `anchorTarget` to the documentation, but you could extend this idea to try to make `target` be fully configurable and also use something similar to make `title` configurable.

**Comment by litera** [comment]
It would be great for links to auto detect selection as being a hyperlink and automatically put that in the link address input. Now that would be useful.

**Comment by nmielnik** [comment]
If hovering over a link, the anchor preview popover is displayed showing the URL of the link. If that's clicked, the anchor from input is displayed and prefilled with the href value.

If you select an already existing link and click the link button, the link should be unlinked. I believe this matches the behavior of medium.

Are you seeing issues with these behaviors?
________________________________

**Comment by phiggins42** [comment]
this is more

``` 
type -> I love http://google.com -> select `http://google.com` -> detect http://, assume selection wants to be a link, popup anchorform with http://google.com as the value
```

Lots of markdowny things auto-link a valid url with an anchor. the link-selection stuff is more for taking inline copy and making it a link. I have a thing/extension I use that monitors key activity and will inject markup parsed from markdown syntax. 

```
type -> I **love**[space] -> becomes -> I <b>love</b> [cursor] 
```

would auto-link too, or could I suppose.

**Comment by nmielnik** [comment]
@brazorf would you be able to clarify what you meant by allowing options for each link?  Are you suggesting changes to the anchor input form in the toolbar (where you type in the url), or are you talking about passing parameters to the `.createLink()` method on MediumEditor?

**Comment by litera** [comment]
I'm was talking about the process @phiggins42 mentioned.

1. User types in text with some URL within (starting with either *http* or *www*)

 > *Suppose *autoLink* if `false`, so URLs don't automatically get linked.*
2. User selects URL and clicks *link* toolbar button
3. Link toolbar should now display anchor form but instead of just showing it empty it first detects that selected text is a URL and pre-populates anchor form with this selected URL.

Sometime in its history medium editor implemented *autoLink* feature which somewhat make this obsolete when *autoLink* is enabled. If it's not, this would still be a good usability enhancement.
