### ISSUE TITLE
targetBlank = true does not work when complete line is hyperlinked

### ISSUE THREAD

**Issue by sangsteroni** [yabwe/medium-editor#508]
When the option targetBlank is set to true and a word or phrase is highlighted and linked, the corresponding a tag has the target="_BLANK" attribute set correctly. However, this does not happen when the entire line in the paragraph is highlighted and made into a hyperlink.

You can see it from the attached image. This behaviour was observed in Safari, Chrome and Firefox for the Mac.

![hyperlink](https://cloud.githubusercontent.com/assets/3511952/6851250/e87d3b50-d403-11e4-9d44-250cfb591266.jpg)

**Comment by j0k3r** [comment]
Should we really need to handle link across paragraphs ?

**Comment by sangsteroni** [comment]
@j0k3r It becomes a valid use case when you think not of entire paragraphs but something as simple as someone typing this on its own line:
Click here to view the full article. 

Hope this helps.

**Comment by j0k3r** [comment]
@sangsteroni I get it, thanks !

**Comment by filipkis** [comment]
+1 for this one

Also the targetBlank doesn't work for auto link option. Should I open a new issue for that case?

**Comment by j0k3r** [comment]
@filipkis yes please open an issue about that

**Comment by rishijain** [comment]
Is this fixed already ? I could set links with ```targetBlank:true ``` on paragraphs. I tried on different browsers on mac.

chrome 46.0
<img width="1280" alt="chrome 46 0" src="https://cloud.githubusercontent.com/assets/946527/10869184/05625ea0-80cd-11e5-91c5-0226b574d1d4.png">

firefox 41.0.2.
<img width="1280" alt="firefox 41 0 2" src="https://cloud.githubusercontent.com/assets/946527/10869185/05e5c0ce-80cd-11e5-8acd-b2627a1bf842.png">

safari 8.0
<img width="1280" alt="safari 8 0" src="https://cloud.githubusercontent.com/assets/946527/10869186/05f776c0-80cd-11e5-96b1-7e6b2639299f.png">

**Comment by nmielnik** [comment]
This probably was fixed as part of the effort to handle links within nested block elements.  Thanks for the investigation @rishijain
