### ISSUE TITLE
Safari error

### ISSUE THREAD

**Issue by marceloboeira** [yabwe/medium-editor#522]
Following the example at README.md I got this error:

![screenshot 2015-03-29 19 55 51](https://cloud.githubusercontent.com/assets/1898225/6888230/ad2ea5ec-d64d-11e4-82a7-ce983e003b2c.png)

**Comment by phiggins42** [comment]
doing what from the readme exactly? there is a case there where that error would throw if the keydowns function was unable to find a selection node, and this safety check 

```
            tagName = node && node.tagName && node.tagName.toLowerCase(),
```

might be worthwhile, but lots of stuff in there references `node` expecting it to have been a found node, and in this case it is not. steps to reproduce would be sweet.

**Comment by phiggins42** [comment]
(i have seen a similar error when pressing `tab` through a form that was _in_ the mediumEditor's "canvas", and a similar sanity-check as noted above solved the issue, though was not limited to safari)

**Comment by marceloboeira** [comment]
@phiggins42 testing again, I need to press: `cmd+a` and after `delete` to raise the error.

**Comment by j0k3r** [comment]
@marceloboeira could you test it again? I've tested on the 4.11.1 release and didn't get the error.
As far as I understand, you select all the content using <kbd>cmd</kbd>+<kbd>a</kbd> and then clear every thing with the return key (aka delete), right?

**Comment by marceloboeira** [comment]
@j0k3r Yes, I'll test and let you know soon

**Comment by nmielnik** [comment]
Closing this for now as it seems like it may have been fixed.  @marceloboeira if you are still seeing this please re-open the issue.
