### ISSUE TITLE
feature: dynamic toolbar buttons per block

### ISSUE THREAD

**Issue by phiggins42** [yabwe/medium-editor#527]
ability to define buttons that react to the content they are in, eg: disallow bold and underline while in heading element and access to the toolbar code might get me there faster

... 

something like defiing a header2 button to only show h1 and h2 buttons (only allowing the creation/change/removal of the heading tag, no styles inline)

would work as either explicit blacklist on the button type, or a whitelist of buttons to show in the toolbar when the selection is in a particular element.

**Comment by hellocosmin** [comment]
+1, I think this would be a great option.

In my case, I custom-coded something, see https://github.com/daviferreira/medium-editor/issues/385

**Comment by nmielnik** [comment]
See #797 for a repo that has some basic support for this, so others can either use to repo or build out their own extension to completely support this feature.
