### ISSUE TITLE
Copy and Paste Word 2013 

### ISSUE THREAD

**Issue by brunoksato** [yabwe/medium-editor#546]
when I cut and paste the word time this piece of code together and ends up giving bug when saving my content within the editor

           <script language="JavaScript"></script>       

there is a solution ?

**Comment by brunoksato** [comment]
My temporary solution

    $('.editable > p').each(function () {
                if ($(this).text().indexOf('msoBrowserCheck') != -1) {
                    $(this).remove();
                }
            });

**Comment by j0k3r** [comment]
I'm curious, which paste options did you defined?

**Comment by mrdoinel** [comment]
+1 I got the same issue

**Comment by j0k3r** [comment]
@mrdoinel Can you provide us a doc from Word so we can try to reproduce the problem?

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
