### ISSUE TITLE
Editor loses focus when anchor is directly injected into content.

### ISSUE THREAD

**Issue by NoelBaron** [yabwe/medium-editor#570]
I've successfully implemented At.JS with medium-editor, but there is one small wrinkle I have yet to iron out. Once a template (usually a non-editable span) is pasted into the editor, the editor loses focus and the user must click on the editor again to regain caret position.  

Have you exposed a way for us to programmatically refocus the user's last known cursor position? At.JS has an insert event, but I haven't figured out how to refocus on the editor.

At.js: https://github.com/ichord/At.js

Ps. If you know of a better tagging plugin that works well with medium, I'd appreciate a url! 

**UPDATE**
Discovered the cause of this behavior here: https://github.com/daviferreira/medium-editor/issues/570#issuecomment-94722862

**Comment by j0k3r** [comment]
Have you tried to fired `$pastedElement.trigger('input')` event on the pasted element ?

See https://github.com/daviferreira/medium-editor#capturing-dom-changes

**Comment by NoelBaron** [comment]
@j0k3r Very close... medium refocuses correctly now, but the cursor is reset to before the inserted element (not after). Does medium expose a "paste" method? Maybe I can override At.JS to respect medium's paste as opposed to directly injecting the new element.

**Comment by j0k3r** [comment]
paste have been improved recently (see https://github.com/daviferreira/medium-editor/pull/535).

Check the last 2 core methods https://github.com/daviferreira/medium-editor#core-methods

 - `.cleanPaste(text)`
 - `.pasteHTML(html, options)`

**Comment by NoelBaron** [comment]
pasteHTML seems to work well. The only issue is with white-space before & after the pasted element. 

Expected: "Here is the [link] I mentioned."
Actual: "Here is the[link]I mentioned."

I tried inserting <span>&nbsp;</span> but medium sanitizes it out of the string. Do you have a recommendation for proper spacing before & after the pasted element?

**Comment by nmielnik** [comment]
One possible workaround is to append a space on either side of the html that you're attempting to paste...I'm thinking that could work, but I doubt it can be generalized for you.

**Comment by NoelBaron** [comment]
@j0k3r @nmielnik Here's what I discovered: When you directly inject an anchor with contenteditable=false, the input trigger doesn't work and the editor is unable to set focus. Once I removed the contenteditable from the equation by using pasteHTML (which strips out that attribute), I was able to properly set focus, along with prefix & suffix white space.

However, I would like to insert links with contenteditable=false so that the entire link is deleted upon backspace. It would also be ideal if I could define a whitelist, so I could wrap a few contenteditable=false links within a parent span in order to provide an experience similar to Facebook's name tagging feature.

Do you see any viable path for me to make this work using medium-editor?

**Comment by nmielnik** [comment]
So I was able to hack something up to get this to work (except in Firefox) and here's what I found:

1. It's the browser that's removing the `contentedtiable=false`, not our code itself.
  * Internally we call `document.execCommand('insertHTML')` to have it replace the selection with custom HTML.
  * Not all browsers support this, so we have code to mimic insertHTML as a fallback.
  * To workaround this, I changed [this line of code](https://github.com/daviferreira/medium-editor/blob/master/src/js/util.js#L217).  I changed the `insertHTMLCommand` function to take an additional `manual` parameter, and if that parameter is `true`, skip over the `doc.execCommand` call and go straight to the fallback code.
  * This means you'll have to accept the `manual` parameter [here](https://github.com/daviferreira/medium-editor/blob/master/src/js/core.js#L884) and [here](https://github.com/daviferreira/medium-editor/blob/master/src/js/paste.js#L186) and then pass it into the call to `insertHTMLCommand` [here](https://github.com/daviferreira/medium-editor/blob/master/src/js/paste.js#L206).
  * This will allow you to call `editor.pasteHTML('yourHTML', null, true)` and then the `contenteditable=false` attribute will not be removed
2. This actually works pretty well in Chrome, Safari, and IE 9+, but the big outlier is **Firefox**.  
  * When I try this on OSX 10.10.2, if I try to move the cursor near the uneditable link, the cursor just disappears and I can't get it back.
  * Even worse, if I move the cursor near it and attempt to delete it, I just lose my cursor again, and the element remains!

@NoelBaron  You can try out these steps and see if you see similar behavior.  Let me know if you have any questions.

If you are able to find something to workaround firefox, definitely open a pull request with these changes.  Even if you don't find a firefox solution, this seems like useful functionality and you should still open a pull request if you're able to get it working :smile:

**Comment by NoelBaron** [comment]
Thanks Nate! I will play with this tonight to see where it takes me. I enjoy giving Firefox a good whooping every now and then.

**Comment by nmielnik** [comment]
@NoelBaron did you ever have any luck with this?

**Comment by NoelBaron** [comment]
@nmielnik We had to jump to some other priorities, but we're swinging back to this first thing next week. I definitely need a fix so expect a pull request soon.

**Comment by nmielnik** [comment]
@NoelBaron did you ever get a chance to come back and explore this?

**Comment by NoelBaron** [comment]
@nmielnik funny you should post this today, I'm smack in the middle of upgrading to 5.3 right now. Last progress is from April 21, ya?

**Comment by nmielnik** [comment]
I guess my v5 upgrade radar must have been going off :rotating_light:

Your last comment on this issue way May 6th, if that's what you are asking, so pretty close.

Definitely check out the [UPGRADE-5.md](https://github.com/yabwe/medium-editor/blob/master/UPGRADE-5.md) file, and let us know if you have any questions while upgrading!

**Comment by NoelBaron** [comment]
Alright @nmielnik, I was able to implement your fallback solution using 5.3.0 and it works splendidly well. However, we're at the mercy of the FF team to resolve their backspace issue, as I was unable to get the backspace key to trigger a full delete. Luckily, in FF 38.0.5+ I was able to highlight the link to delete it. The cursor issues you mentioned back in April appear to be resolved.

I added "fallback" parameters to insertHTMLCommand and pasteHTML in 5.3.0. Is this worth a pull request?

Also, I had an idea for how to resolve our FF issue using the editor:

* If browser is FF, listen for the delete/backspace key in Medium Editor
* Upon delete, if element to left of cursor has `contenteditable=false`, destroy the element.

Performance-wise, It's the "find element to the left of the cursor" part that worries me. Anyone feel like taking a stab at this?

**Comment by nmielnik** [comment]
Yeah, if you have a valid use case for it, I think it's definitely worth a pull request (with a few tests of course :smile: )

Regarding the functionality for delete/backspace on a contenteditable, I would say if you have an implementation that works, go with it.  If there are any performance concerns, we can always have an option that is by default `false`, but in your case you can turn on.  We can then try to iterate on top of it to improve performance, and then eventually turn it to `true` by default, or just get rid of the option altogether.

Either way, if you have anything work, definitely submit a pull request.  If you don't, could you open a separate issue explaining what needs to be done?

Thanks for the investigation!
