### ISSUE TITLE
Weird markup when aligning text

### ISSUE THREAD

**Issue by steoo** [yabwe/medium-editor#595]
Scenario: 
1) `JustifyCenter` one paragraph `p`, resulting markup 

`<p style="text-align: center;">Phasellus viverra nulla ut metus<br></p>`

2) `JustifyCenter` another paragraph `p`, in a way that the markup results: 

`<p style="text-align: center;">Phasellus viverra nulla ut metus<br></p>`
`<p style="text-align: center;">Phasellus viverra nulla ut metus<br></p>`

3) `H1` both the `p` so the markup looks like

`<h1 style="text-align: center;">Phasellus viverra nulla ut metus</h1>`

4) `JustifyLeft` the `H1` and the markup will look like

`<h1 style="text-align: center;"><div style="text-align: left;">Phasellus viverra nulla ut metus</div><div style="text-align: left;">Other text</div></h1>`

This is not a real clean markup sadly. I'm cleaning the markup e stripping tags so the `div` is breaking all of it.

**Comment by steoo** [comment]
@daviferreira I guess we have to start another fight with contenteditable eheh :)

**Comment by steoo** [comment]
@daviferreira I found out that the reason why the `divs` are created is that, to "*replicate*" ( I guess .. ) the `p`'s the browser creates a `<br/>` between the texts .

`<h1 style="text-align: center;">Phasellus viverra nulla ut metus <br> Phasellus viverra nulla ut metus</h1>`

This gets weirdly translated in two `div`s. 

I'm working on a branch feature, I'll make a pull request, if it works :)

**Comment by nmielnik** [comment]
Resolved by #675
