### ISSUE TITLE
Firefox pasteHTML not work

### ISSUE THREAD

**Issue by HuarenYu** [yabwe/medium-editor#644]
I found pasteHTML method not work in firefox 36.0.1 for mac.

**Comment by j0k3r** [comment]
I got the same problem. After a quick checkup, I found that the way to retrieve the HTML content from the clipboard in JS on Firefox only return the plain text.

When you say that `pasteHTML` doesn't work, did you mean:
- you got nothing pasted in your editor?
- you got the plain text instead of HTML?

**Comment by phiggins42** [comment]
I encountered a bug in firefox where paste magically wasn't coming through, but mine was limited to `<input type='text>`, when carat in there. paste is registered, and triggers handlePaste, but util.inserthtml -> document.execCommand("insertHTML", false, pastebody) resulted in nothing being pasted through. I have a thing in place where before handlePaste is called we check with extensions to see if they want to handle the paste instead, so I just made the extension that has the `<input>` nodes check if the focus element is an input and override default handlePaste, simply allowing the default paste-into-input behavior to pass through. 

other than that I've not seen any outright "paste doesn't paste" issues in firefox.

**Comment by HuarenYu** [comment]
I use uploadify upload image to server, then use `pasteHtml('<img src="...">')` to medium editor, But it not  work.

**Comment by j0k3r** [comment]
Could you provide a jsfiddle with an example of what "not work" ?
I've tried with that one http://jsfiddle.net/jhvzzp1c/2/ and it seems to paste the img correctly.

**Comment by HuarenYu** [comment]
http://jsfiddle.net/yuhuaren/1Lxssgjz/4/

**Comment by j0k3r** [comment]
It works for me on Firefox _but_ you need to focus on the editor first. Otherwise, we don't know where to paste HTML.
This behavior is exactly the same on Chrome.

What behavior are you expected ?

**Comment by HuarenYu** [comment]
I expect i can get the content editable cursor position before file input change. I want to insert the selected image to that position.

**Comment by phiggins42** [comment]
editor.saveSelection() during keydown on the input should give you the carat position before it focues the input node, then when upload complete/whatever editor.restoreSelection, then pasteHTML() should work?

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Comment by asselinpaul** [comment]
Unsure if this will help but for me the issue was that I was pasting a _div_ with an id but nothing inside. Adding a space inside the _div_ solved my problem.
