### ISSUE TITLE
Possibility of overwriting the anchor preview pop up ?

### ISSUE THREAD

**Issue by be-next-hotdog** [yabwe/medium-editor#649]
As question, i wonder how may i overwrite the anchor preview pop up, sort of adding a delete button ahead of the link address ? Any rewritten cases ? appreciate your tips @=@

**Comment by phiggins42** [comment]
you would set `{ anchorPreview: false }` in the options, and provide an extension that provides the same behavior as the core anchor preview. You _should_ be able to utilize the original if you are only wanting to shim in a few methods

```
var MyAnchorPreview = MediumEditor.extensions.anchorPreview.extend({
/* stuff */
});
```

might not even be as verbose as:

```new MediumEditor(..., {
         extensions:{
               "anchorPreview": new MyAnchorPreview()
         },
         anchorPreview: false
});
```

I have a similar thing in place to add an explicit edit label/icon + make preview link clickable to a new tab

**Comment by be-next-hotdog** [comment]
Cool, but as i still new in medium editor, i did not get how those lines worked ? 

var MyAnchorPreview = MediumEditor.extensions.anchorPreview.extend({
     /* stuff */
});

**Comment by be-next-hotdog** [comment]
Sorry, im still new in medium editor and didnt get how it works the <MediumEditor.extensions.anchorPreview.extend> , could you give a explicit example while you implement your personal features ? be grateful.

**Comment by nmielnik** [comment]
@be-next-hotdog I don't have any pre-existing examples, but you can find the definition of the `anchorPreview` extension object in [src/js/extensions/anchor-preview.js](https://github.com/daviferreira/medium-editor/blob/master/src/js/extensions/anchor-preview.js).

By calling `MediumEditor.extensions.anchorPreview.extend()` you can override any of the methods defined in the `anchorPreview` object that I pointed you towards above.  So, if you wanted to override the `getTemplate()` function to return your own custom HTML, and override the `destroy()` function to do some other things when the editor is being torn down, you would do this:

```javascript
var MyAnchorPreview = MediumEditor.extensions.anchorPreview.extend({
  getTemplate: function () {
    /* return your own custom HTML string here */
  },
  destroy: function () {
    /* do you custom tear-down logic here */
  }
});

// Now pass your custom extension into MediumEditor to override the default
new MediumEditor('.editor', {
  extensions: {
    anchorPreview: new MyAnchorPreview()
  }
});
```

Hope that's helpful.

**Comment by phiggins42** [comment]
I saw comments come in via email, but there were never actually here ... so not sure if real followup question, or what ... here is my sample:

```
var MyExtension = AnchorPreview.extend({

        // overide built in "look for place to put href value"
        anchorPreviewDisplaySelector: false, // not sure this is still accurate for 4.11.x?

        getTemplate: function(){
            // just return an empty string. we fill this from a hbs template
            // to avoid having to bind extra handlers/etc, so no need to fill
            // the preview just yet.
            return '';
        },

        showPreview: function(){
            AnchorPreview.prototype.showPreview.apply(this, arguments);

            // we have an activeAnchor we want to preview. draw the template for it.
            this.anchorPreview.innerHTML = template({
                href: this.activeAnchor.attributes.href.value
            });

            // also have to position the preview _after_ filling because the size
            // changed, and will be offset otherwise.
            this.positionPreview();
            return this;
        },

        handleClick: function(e){
            // if `e.target` was our external link, stop the event. otherwise just let
            // preview code handle the 'enter edit mode'
            if(e && e.target.classList.contains("external-link")){
                this.hidePreview();
                return false;
            }
            AnchorPreview.prototype.handleClick.apply(this, arguments);
        }

    });
```

the `template()` in there is just a handlebars compiled template:

```
<div class="medium-editor-toolbar-anchor-preview" id="medium-editor-toolbar-anchor-preview">
    <span class="preview-anchor-wrap">
        <a contentEditable="false" target="_blank" class="external-link medium-editor-toolbar-anchor-preview-inner" href="{{ href }}">{{ href }}</a>
        <a class="medium-editor-toolbar-anchor-preview-action">Edit</a>
    </span>
</div>
```

**Comment by be-next-hotdog** [comment]
Ohh, sorry, guys, I found the ways to make my extensions work just few seconds earlier before your responses and I deleted my question. But thanks all the same !!

Btw, I could extend anchor either by .extend() but I d better shift my anchor config elements to the same object in .extend( { MyNewAnchor obj } ).
