### ISSUE TITLE
Support for auto creation of list bullets

### ISSUE THREAD

**Issue by astoilkov** [yabwe/medium-editor#659]
Is there any plan or easy way to support auto insertion of list bullets when hitting Enter? In the cases when there are bullet on the current line.

The official Medium editor supports this feature.

**Comment by daviferreira** [comment]
It should work like that already. Not working for you? Can you provide a fiddle?

**Comment by astoilkov** [comment]
I just tried to create a JSFiddle example [here](http://jsfiddle.net/8huy00xq/) but without success. You could use the HTML below which for me runs successfully when running it locally.

I am typing:

* 1 (upon hitting enter key the next bullet is not created and instead blank line appears)

```html
<html>
  <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/medium-editor/4.10.1/medium-editor.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/medium-editor/4.10.1/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    <script>
      window.onload = function () {
        var editor = new MediumEditor('.editable');
      };
    </script>
    <style>
      .editable {
        margin-top: 100px;
        width: 100%;
        height: 100%;
      }

      p {
        margin: 0;
      }
    </style>
  </head>
  <body>
      <div class='editable'>
      </div>
  </body>
</html>
```

**Comment by j0k3r** [comment]
Well, I don't think it work atm.

What @astoilkov mean is auto-creation of:

 - an _orderlist_ when you type "1. uziaouzao <kbd>ENTER</kbd>"
 - an _unorderlist_ when you type "*. uziaouzao <kbd>ENTER</kbd>"

**Comment by astoilkov** [comment]
Yes. Exactly. If it doesn't work do you plan to implement it? If not can you give suggestions how I can implement it myself. General guidance will be really helpful.

**Comment by daviferreira** [comment]
More like markdown support for lists only then?

**Comment by astoilkov** [comment]
The Medium editor supports it. I believe it is useful for this editor to implement it. It makes it more easy to work with lists.

**Comment by j0k3r** [comment]
@daviferreira kind of, with a live preview.

@astoilkov You can do that using an extension.
For example, we have an auto-link extension. You can find inspiration inside this one.

My quick list:
 - check if the extension `orderlist` or `unorderlist` is enabled (using getExtensionByName) if not, do nothing
 - subscribe to `editableKeypress`
 - check that the current paragraph just contains `1. ` or `*. ` (depends on which extension is enabled).
 - convert the whole line to an ordered list or an unordered list (using `execAction('insertunorderedlist')` or `execAction('insertorderedlist')`)

**Comment by phiggins42** [comment]
I have an extension which monitors text for a subset of markdown ... eg:

```
# heading[enter]
``` 

will inject options.firstHeading tag, and

```
* words[enter]
```

will convert to UL. 

and stuff like typing

```
the *quick*[space]brown fox
```

will italic the word `quick` at the point of space being hit.

inline bold and italic all work ... good thought about making it detect available buttons/commands, I am kind of just allowing the markdown through. Though unfortunately the way I have implemented it breaks undo stack because I didn't want to be bothered with the nuances of selection and execAction('insertorderedlist') et al ...

i'm working towards getting approval to reduce some of the extensions we've created @work to easily consumable parts, but that is a bit in the future.

**Comment by astoilkov** [comment]
That sounds cool. Are you willing to share the code?

**Comment by phiggins42** [comment]
i would be happy to, but at this very moment the keyhandling and markdown aspects of monitoring are too tightly coupled with other unrelated functionality. I am planning on breaking these features apart and releasing them as standalone extensions, but don't have an ETA. It also has a jquery dependency I'd like to break out (just using it for ease of shorthand dom manip, nothing that can't be done with pure dom apis). the gist is basically as @j0k3r describes: 

* listen to editableKeypress
* check the content for special markdown characters
* react and replace line (`<p>` generally) with the parsed markdown dom

the main issue is how badly it breaks native undo. I am currently exploring implementing a managed undo stack for the editor instance, which will also be an extension. 

my extension also doesn't handle markdown in paste content, which would be nice to include in a generic `markdown` extension ...

**Comment by nmielnik** [comment]
If we can do this in a way that doesn't break native undo/redo, that would be awesome.  Even if it does break undo/redo, this would still be a great feature to have (potentially very similar to the auto-link extension)

**Comment by bkniffler** [comment]
Any news on this? Would be a great addition.

**Comment by nmielnik** [comment]
I think @tomchentw 's work for the [medium-editor-tc-menton extension](https://github.com/tomchentw/medium-editor-tc-mention) is another great starting spot if anyone wanted to take this on, either as a built-in extension or as an external extension that we can link to from our documentation :smile:

**Comment by tomchentw** [comment]
Thanks! The `medium-editor-tc-mention` extension supports mention panel triggered by `@ or #`. The trigger behavior is implemented to match the most common pattern as close as possible. https://github.com/yabwe/medium-editor/issues/136#issuecomment-148051481

For normal users, feel free to grab it and customize the panel content yourself (async loading, styling, limiting size of the list...it's all yours). Also glad to see it being integrated as build-in extension in the future. Please let me know if there's I could help with!

**Comment by oyeanuj** [comment]
@phiggins42 Any updates on your extension by any chance?

**Comment by varun-raj** [comment]
Check this extension : https://github.com/varun-raj/medium-editor-autolist.
So this creates
- an orderlist when you type "1. something <kbd>ENTER</kbd>"
- an unorderlist when you type "*. something <kbd>ENTER</kbd>"

**Comment by j0k3r** [comment]
@varun-raj interesting !
You should add it to https://github.com/yabwe/medium-editor/wiki/Extensions-Plugins

Also, I think you should check if the `orderlist` or `unorderlist` are enabled  too.

**Comment by varun-raj** [comment]
How to check if they are enabled ?

**Comment by j0k3r** [comment]
Like I said in my previous comment (https://github.com/yabwe/medium-editor/issues/659#issuecomment-107420284) using `getExtensionByName` for example

**Comment by varun-raj** [comment]
Done ! 
https://github.com/varun-raj/medium-editor-autolist/commit/48f86a2094bc6caba2c06370c283555544cc1c90

**Comment by nmielnik** [comment]
This is awesome, thanks @varun-raj!

Just added your extension to the [Extension README](https://github.com/yabwe/medium-editor/blob/master/src/js/extensions/README.md#examples-of-custom-built-external-extensions).

We'll work on getting the extension onto the landing page as well.

Closing this issue, as [medium-editor-autolist](https://github.com/varun-raj/medium-editor-autolist) seems to take care of it.

**Comment by varun-raj** [comment]
@nmielnik that would be great :) Thanks
