### ISSUE TITLE
Simple way to inactivate the list button while selecting Head Title ?

### ISSUE THREAD

**Issue by be-next-hotdog** [yabwe/medium-editor#668]
I m just seeking for simplest way to inactivate list button when I select specific kind of text (ex : header / quote ... ) ?

**Comment by j0k3r** [comment]
Is it to avoid this #617 ?

**Comment by be-next-hotdog** [comment]
I read the code but I dont think that would be the same as #617, I wonder how to disable the unordered list / ordered liste button while editing the "headers" but enable for the others ?

**Comment by nmielnik** [comment]
When you say disable, you mean make the button be unclickable correct?  It seems like you'll need to do some overriding to some of the buttons to make this work.  I know @phiggins42 has done something very similar to this, so he might be able to to shed some light on ways to approach this.

Off the top of my head, I would suggest overriding the `orderedlist` and `unorderedlist` buttons and implementing a `checkState()` method.

`checkState()` gets called for every button each time the toolbar is updated.  The code will look at the user's current selection, and climb up the selected element's parent nodes, calling `checkState()` for each element until the parent editor element is reached.

Your `checkState()` method for the list buttons could detect if any element along the way is a `<h1>`, `<h2>`, `<h3>`, etc.  If it encounters one, it would disable itself.  You would need to make sure the button is enabled during the first call to `checkState()` as well.

**Comment by phiggins42** [comment]
Entirely working-but-way-horrible `blacklist` extensions:

```js
define(["medium","jquery","underscore"], function(medium, $, _){

    // summary: A Toolbar actionBlacklist/actionWhitelist API

    return medium.Extension.extend({

        init: function(){

            var resetToolbar = this.resetToolbar.bind(this);
            this.subscribe("showToolbar", this.onShowToolbar.bind(this));
            this.subscribe("hideToolbar", resetToolbar);
            this.subscribe("positionToolbar", resetToolbar);

        },

        // reset toolbar i.e. show all actions, reset first/last classes
        resetToolbar: function(){
            var toolbar = this.base.toolbar,
                $actions = $(toolbar.getToolbarActionsElement())
            ;

            toolbar.getToolbarElement().classList.remove('medium-editor-toolbar-active');
            var $buttons = $actions
                    .find("button")
                    .removeClass("hide" + " " + this.base.options.firstButtonClass + " " + this.base.options.lastButtonClass)
            ;
            this._setToolbarBookendClasses($buttons);
        },

        _setToolbarBookendClasses: function($buttons){
            if ($buttons && $buttons.length) {
                // set button class on bookend buttons to display correctly
                $buttons[0].classList.add(this.base.options.firstButtonClass);
                $buttons[$buttons.length - 1].classList.add(this.base.options.lastButtonClass);
            }
        },

        headerWhitelist: ["header1","header2"],

        // hide blacklisted toolbar actions (or show whitelisted)
        onShowToolbar: function(){

            var el = this.base.getSelectedParentElement(),
                tag = el && el.tagName,
                token = $(el).closest("[data-export-token]").attr("data-export-token"),
                is_heading = /h[1-6]/i.test(tag) && (!token || !token.length),
                blacklist
            ;

            if(is_heading){
                // todo, maybe expand this tagname matching regexp to support a
                // hash of whitelists for various block-types instead?
                blacklist = _.filter(this.base.options.buttons, function(button){
                    return !_.contains(this.headerWhitelist, button);
                }, this);
            }else{
                if(token && this.base.options.extensions[token] && this.base.options.extensions[token].actionBlacklist){
                    blacklist = this.base.options.extensions[token].actionBlacklist;
                }
            }

            if(blacklist && blacklist.length){
                _.each(this.base.commands, function(cmd){
                    if (_.contains(blacklist, cmd.name)){
                        cmd.getButton().classList.add("hide");
                    }
                });
                // get the visible buttons in order to make sure the bookend actions have the correct style
                this._setToolbarBookendClasses($(this.base.toolbar.getToolbarActionsElement()).find("button:visible"));

            }

        }

    });

});

```

sadly it uses jquery and underscore in very limited ways. it would be trivial to break those deps away and just rewrite the few sections using them. this also only handles heading elements, and has a weird looking thing called 'tokens' in there. Tokens are "blocks" (div-wrapped special containers) in my world, and this allows each extension/button to define an `actionBlacklist` array of buttons to not show based on the current selection. I plan on making it a) jquery-less, b) underscore-less, c) more generic, to where the blacklist extension could have a series of tagName/selectedParent checks to cover more cases than just headings. this also doesn't disable the buttons, it adds a class "hide" (which is just `display:none`). Also, crudely, the extensions can provide an `actionWhitelist` to define an inverted list to include istead of exclude

the above `headerWhitelist` is the one hardcoded for header tags. I would definitely rework this code before actually attempting to use it. Ideally I would find the time to clean this up further and make the blacklist/selection-context smarter. I had meant to investigate @nmielnik suggestion of using queryCommandState which does the walking for you. Currently it is a little fragile. but hope it helps.

**Comment by be-next-hotdog** [comment]
yepp, your tips did left me a clear track. Thx, I'll get rid of the "$" & "_" dependancies on my own.
