### ISSUE TITLE
Question : could we always stick the toolbar on the top of a DIV (or the other tags) ? 

### ISSUE THREAD

**Issue by be-next-hotdog** [yabwe/medium-editor#673]
I reopened this subject cos I wonder to know this option/possibility for now and I observed that we were not able to extend the toolbar features naturally. Wish someone to render me all your tips about this topic, and of course I'd like to contribute to the toolbar extension.

**Comment by be-next-hotdog** [comment]
Related to #664

**Comment by nmielnik** [comment]
So you could potentially start messing around with the toolbar extension, which you can override and customize however you want.

If you go off of the `v5` branch, the toolbar is current extendable, so you can can do `MediumEditor.extensions.toolbar.extend({})` and override whatever methods you want.

If you were supporting appending the toolbar to a specific element, and not to the `<body>`, you'd likely want to use the `static` option or just skip all the logic that attempts to position the toolbar since I'm assuming you don't want it to move around.

**Comment by be-next-hotdog** [comment]
I tried, directly, to run showToolbar() and positionToolbarIfShown(), it did displayed on the left top but still wait for selection focus to position/stick to the aim div ? In fact, all I need is merely to create the toolbar and stick it on the top of aim container from page load, in additional, it should be visible all the time.  

btw, when you expect to release v5 ?

**Comment by nmielnik** [comment]
We have an alpha release of 5.0.0 available now:

https://github.com/yabwe/medium-editor/releases/tag/5.0.0-alpha.0
https://www.npmjs.com/package/medium-editor

**Comment by be-next-hotdog** [comment]
I forked v5 alpha, it seems as if you changed the stickybar behaviors. Now the toolbar sticks merely on the top of chosen Div and will disappear while scrolling down. Nevertheless it woundn't disappear but stick to the top of navigator window until the chosen Div entirely crossed over.

Could you give an example @override that makes toolbar remain displaying from the start ? Thx.

**Comment by nmielnik** [comment]
What options are you passing to medium-editor to get the sticky toolbar behavior?

The way to pass options related to the toolbar has changed in v5.0.0.

**Before v5.0.0**
```js
var editor = new MediumEditor('.editor', {
  staticToolbar: true,
  stickyToolbar: true
});
```

**v5.0.0+**
```js
var editor = new MediumEditor('.editor', {
  toolbar: {
    static: true,
    sticky: true,
  }
});
```

Make sure you're passing the options in the latter example, where `static` and `sticky` are options inside the `toolbar` sub-option.

**Comment by be-next-hotdog** [comment]
No, you misunderstood totally my questions. I need just an example to override toolbar behaviors by extensions.extend(), which makes toolbar ***remain displaying from the start***. I couldn't position toolbar at all later.

**Comment by nmielnik** [comment]
So one quick and hacky way to make sure the toolbar stays visible is to add some custom css that does this:
```css
.medium-editor-toolbar {
  visibility: visible;
}
```

If you want it to appear in a specific spot, you could override the current `init()` method:
```js
init: function () {
    Extension.prototype.init.apply(this, arguments);

    this.initThrottledMethods();
    this.getEditorOption('elementsContainer').appendChild(this.getToolbarElement());
},
```
If you look at the method, you can see the last line is where the toolbar gets appended to the `'elementsContainer'`, which is `document.body` by default.  You could change this code to append the toolbar somewhere else.

You could do this by creating a new toolbar via extend():

```js
var myToolbar = MediumEditor.extensions.toolbar.extend({
  init: function () {
    Extension.prototype.init.apply(this, arguments);
    this.initThrottledMethods();

    var toolbarElement = this.getToolbarElement();
    // append the toolbarElement to the place you want it here 
  }
});
var editor = new MediumEditor('.editor', {
  extensions: {
    toolbar: new myToolbar();
  }
);
```

You could also do this by adding the method into the toolbar options:

```js
var editor = new MediumEditor('.editor', {
  toolbar: {
    init: function () {
      Extension.prototype.init.apply(this, arguments);
      this.initThrottledMethods();

      var toolbarElement = this.getToolbarElement();
      // append the toolbarElement to the place you want it here 
    }
  }
});
```

Hopefully this can get you pointed in the right direction.  If you want to find a less hacky way to prevent the toolbar from disappearing, you could look into overriding `hideToolbar()` or look for places in the code that call `hideToolbar()` and try overriding those methods.

Hope that helps.

**Comment by be-next-hotdog** [comment]
Yep, thx a lot for details.
