### ISSUE TITLE
Inject the global dependancies in extensions

### ISSUE THREAD

**Issue by be-next-hotdog** [yabwe/medium-editor#684]
Heyy, I m looking for suggestions while extending the components( ie. toolbar, anchor form and etc) via " MediumEditor.extensions.XXXX.extend() ".

In order to factorize the my extensions scripts, I did just in main script :

options = { XXXX : new MediumEditor.extensions.XXXX.extend(MyExtensions)}  before instantiation.

So I try to find a better way to inject the Util, Selection global classes in my extensions cuz obviously I didnt define them in my extensions objects, or any tips to facilitate the refactoring ?

**Comment by nmielnik** [comment]
So there currently isn't a way to inject the dependency, but these utility functions are exposed via the MediumEditor object.

`MediumEditor.util // Same as global 'Util'` 
`MediumEditor.selection // Same as global 'Selection'`

So you can access the helper methods that way.  Does that answer your question?

**Comment by be-next-hotdog** [comment]
Of course, that does helps me a lot. Thx, Mr Athlon ; )

**Comment by be-next-hotdog** [comment]
And I noticed that for the modules possessing their own constructor, I have to override their behaviours by prototype (ie. Button), extensions.button.extend() doesn't work in this case ? So I used currently : 
MediumEditor.extensions.button.prototype.handleClick = function(e); Or still have a "cleaner" method ? Thx for your patiences.

**Comment by nmielnik** [comment]
Could you be more specific about what you're attempting to do?  This is an example of using `.extend()` for a custom button:

```js
var MyCustomButton = MediumEditor.extensions.button.extend({
  name: 'custom-button',
  handleClick: function (evt) {
    // custom code
  }
});
var editor = new MediumEditor('.editor', {
  buttons: ['bold', 'italic', 'custom-button'],
  extensions: {
    'custom-button': new MyCustomButton()
  }
});
```

**Comment by be-next-hotdog** [comment]
But if I aim to change the default click behavior handleClick() for all or if I'd like to add more than a button ? What should I do then ?

**Comment by nmielnik** [comment]
If you want to change the default behavior for all of the buttons you're enabling, overriding the button prototype is definitely an option, although it's a bit of a hacky one.

Another option (**which is now exposed in v5.0.0-alpha.0**) is overriding the `handleClick` method by passing additional options in the buttons array.

```js
var customHandleClick = function () {
  // your custom code
};
var editor = new MediumEditor('.editor', {
  toolbar: {
    buttons: [{
      name: 'bold',
      handleClick: customHandleClick
    },
    {
      name: 'italic',
      handleClick: customHandleClick
    },
    ...
    // all other buttons and the methods you want to override
    ]
  }
});
```

**Comment by be-next-hotdog** [comment]
1. Used to code kinda above but it didn't work for me. 
Don't worry, I'm always working on the basis of version 5-alpha and will find out my prob. 

2. Searching the way to add a customized form binding to my customized button. 
Found an instance : button => form extensions => anchor / anchor form, but still trapped for now, any tips ? 

Thx,

**Comment by nmielnik** [comment]
1. Let me know what didn't work for you, if it's something in our code I'd like to fix it before we cut the official v5.0.0

2. The `MediumEditor.extensions.form` is basically a class that defines the methods that need to exist for MediumEditor to support displaying a custom form in the toolbar.  The Anchor extension and the FontSize extension both extend the `MediumEditor.extensions.form` base class.  You can see the code here: [form.js](https://github.com/yabwe/medium-editor/blob/v5/src/js/extensions/form.js)

If you're looking to have your extension behave similar to the anchor form or font size form, you can extend either of those for your extension:

```js
var MyAnchor = MediumEditor.extensions.anchor.extend({ /* overrides */ });
var MyFontSize = MediumEditor.extensions.fontSize.extend({ /* overrides */});
var editor = new MediumEditor('.editor', {
  toolbar: {
    buttons: ['anchor', 'fontSize']
  },
  extensions: {
    anchor: new MyAnchor(),
    fontSize: new MyFontSize()
  }
});
```

You can then start adding or removing methods to mess around with modifying the behavior.  Eventually, you'll probably just want to use `MediumEditor.extensions.form.extend()` to define your custom extension so that you won't have a dependency on the anchor/fontSize, but extending from those existing extensions could be a good way to figure things out.

**Comment by be-next-hotdog** [comment]
1. No, I tried testing, that wasn't a bug I think, just cause by ignoring to type the button name so that neither of existent / defined buttons wouldn't work with my extension.

2. Really feel little confounded when implementing a customized form binding to my button cuz I lost the medium editor context "this" which also means losing lots of utility methods, for instance, hideToolbarDefaultAction. Perhaps it'd better to enable "Form" of being totally extendable and binding to specific button's event ? sort of : 
 
   while left click button A => launch default functional form; 
   while doucle click button => form to personalize your button text;
   while right click => scroll-bar to change button's color, etc.

**Comment by be-next-hotdog** [comment]
@nmielnik, have you an example in detail (a customized form linking to customized button's actions) ? Or just a "first taste" script who tested the new extensions features in ver 5.    (= . =)

**Comment by nmielnik** [comment]
Our anchor extension is implemented in this way: `https://github.com/yabwe/medium-editor/blob/master/src/js/extensions/anchor.js`

You could do the same thing, but instead of using `FormExtension.extend()` you would use `MediumEditor.extensions.form.extend()`

If you could create a jsfiddle and explain the problem you're having, it might be easier for me to help that way.

**Comment by be-next-hotdog** [comment]
Forgive me, my fault, I made a mistake to type extensions.button but not extensions.form. Shame on me ... ...

**Comment by nmielnik** [comment]
No prob, let me know if you have any other questions.  If you end up with a working example, I would love to try to use all or part of it in the Wikis for example on creating custom form extensions!

**Comment by be-next-hotdog** [comment]
Of course, that would be a pleasure.

**Comment by be-next-hotdog** [comment]
Need little dev tips again, if I wanna conserve the "form.init" in my form extensions,
 
1. how could I inject FormExtension (currently undefined in my form extension). 
2. Could we add also "showToolbarDefaultActions" as a default behavior in FormExtension ? The main philosophy of Medium Editor is to react to "text selection". So how I might take "shortcut" method to hide my form & show toolbar, in case that no text selected / edited ?

**Comment by nmielnik** [comment]
1. You can reference the FormExtension via `MediumEditor.extensions.form`, so if you need to call init from your init just call `MediumEditor.extensions.form.prototype.init.apply(this, arguments)`

2. If you think that this helper method would help you with your form extension creation, I would recommend you add it to the `form.js` code and open a PR so we can merge it in!  We already have a `hideToolbarDefaultActions()` method, so it seems logical to have a `showToolbarDefaultActions()` as well, and your form extension can help validate that it's actually useful.  What do you think?

**Comment by be-next-hotdog** [comment]
I also altered little the button & toolbar modules in mostly adding conditions to verify/guarantee selection range. Cuz the medium editor's main philosophy is to be triggered / activated by text selection. Therefore, if we make deliberately toolbar display from the beginning and click the buttons, that generates errors sort of "cant find node/range blabla" ... 

Will commit/PR later.

**Comment by nmielnik** [comment]
Awesome, I look forward to seeing the PR!
