### ISSUE TITLE
Editor starts focused?

### ISSUE THREAD

**Issue by lorenkp** [yabwe/medium-editor#685]
Hey everyone—

(I have a question about using the library, and I'm really sorry if this is the wrong place to ask it. This is a great library, and thanks so much to everyone.)

I'm trying to have the editor de-collapse when clicking "Type your text", a la Medium. So far my solution is to use Bootstrap's collapse to reveal the editor when clicking a div with "Type your text." However, with this approach, I'd need the editor to start selected, i.e. cursor blinking already.

I've tried a click event that applies focus to the editor, but no luck.

What do you all suggest, or is there a completely different approach I should try?

Thanks!

**Comment by nmielnik** [comment]
So I'm not sure if I fully understand what you're attempting to do, but I'm guessing you want a programatic way of causing the editor to be focused (have cursor enabled)?

If that's the case, you should be able to use the `MediumEditor.selectElement(element)` method and pass any child element of the editor element:
```js
var editableElement = document.querySelector('.editableElement');
var editor = new MediumEditor(editableElement);
editor.selectElement(editableElement.firstChild); // Put focus inside the element
```

What's good about `MediumEditor.selectElement()` is that if there's any pre-existing text, calling this would select whatever element you pass into it and cause the toolbar to appear as well.

Let us know if there's something else you're attempting to achieve.

**Comment by nmielnik** [comment]
Let us know if there are any other issues that should be addressed for this. Closing for now.
