### ISSUE TITLE
HTML placeholder

### ISSUE THREAD

**Issue by MartyIX** [yabwe/medium-editor#689]
Hi,

can I use an HTML placeholder? I mean something like: 

    "<p>Type your text here</p>"

I tried it and it did not work. I would just like to confirm that it is not possible.

Thank you

**Comment by epascarello** [comment]
The placeholder uses the [CSS content property](http://www.w3.org/TR/CSS21/generate.html#propdef-content) which supports plain text or an image using `url(path)`.

**Comment by MartyIX** [comment]
Thank you

**Comment by j0k3r** [comment]
What is the real HTML you would like to use a default placeholder?

**Comment by MartyIX** [comment]
My use case is highly uncommon. I have <p> styled as list-items and I allow users to write their "checklist". I would like to add default value:

   <p>Please add your checklist</p>

However, I think I can work around the issue.

**Comment by j0k3r** [comment]
You can hack it using CSS, using `.medium-editor-placeholder:after`

**Comment by MartyIX** [comment]
I'll give it a try.

**Comment by nmielnik** [comment]
@MartyIX were you able to work around this?

**Comment by MartyIX** [comment]
Hi, I used a CSS style rule for `.medium-editor-placeholder:after` and I'm satisfied with the result. Thanks
