### ISSUE TITLE
Support for Heading Tags <h1> through <h6>

### ISSUE THREAD

**Issue by sathishmanohar** [yabwe/medium-editor#69]
While the current `header1` and `header2` for heading tags makes sense in situations where I have to give options for users to create headings but want them to use only few headings.

But, there are some limitations to current approach.
* Currently only two headers are supported
* It nags me everytime I click on H1 knowing its really `<h3>` that I'm entering

While I actually think `header1` and `header2` approach has its advantages, I have two suggestions that may improve current situation

1. Increase the number of `headers` supported to about four.
2. Give access to low level heading tags with different set of option labels, probably like `<h1>` `<h2>` `<h3>` etc.

PS: I love this project. Thanks a ton for making this wonderful editor.

**Comment by andreygrehov** [comment]
Medium supports the h3 (which is translated to h4 in the html) now.

**Comment by j0k3r** [comment]
We can add a `H3` button like `H1` & `H2` but is that really interesting to add all possible headers?

**Comment by phiggins42** [comment]
i vote get rid of `header1` and `header2` options, and provide a default of 

```
headers:["h2","h3"]
```

allowing people to incllude as many or few heading buttons for different depths they choose. the two heading options are identicial minus a number.

**Comment by nmielnik** [comment]
This has been added in #677 and released in v5.0.0
