### ISSUE TITLE
Changelog for 5.0?

### ISSUE THREAD

**Issue by jesperbjerke** [yabwe/medium-editor#692]
Is there one?

**Comment by j0k3r** [comment]
There'll be :wink:

**Comment by nmielnik** [comment]
It'll come with the 5.0.0 release.

For now, we have an UPGRADE.md for upgrading to v5.0.0:
[https://github.com/yabwe/medium-editor/blob/v5/UPGRADE-5.md](https://github.com/yabwe/medium-editor/blob/v5/UPGRADE-5.md)

**Comment by nmielnik** [comment]
[CHANGES.md](https://github.com/yabwe/medium-editor/blob/master/CHANGES.md) has been updated, some more additions may still be added between now and when we release, but this should be close.
