### ISSUE TITLE
.destroy() question

### ISSUE THREAD

**Issue by johngoldenlane** [yabwe/medium-editor#702]
Hi,

the .destroy() call should remove all extra stuff the editor bind to the editable DOM element?
Because for me the
role="textbox"
aria-multiline="true" 
medium-editor-index="0"

Stays inthe code (I tried on the demo page via console and there I had the same result).

Is it a feature ( because of course I can remove them manually) or some minor bug?

Thx.

John

**Comment by j0k3r** [comment]
I guess it's a minor bug. On which browser did you tried? Have you tried on other browsers too?

**Comment by nmielnik** [comment]
I don't believe our existing code adds `role="textbox"` or `aria-multiline="true"` onto the element.  Or code definitely does add the `medium-editor-index` and it not being removed during a call to `.destroy()` is a bug.  Do you have any of the browser info @j0k3r asked about?  Any interest in opening a PR to fix the issue?

**Comment by johngoldenlane** [comment]
Hi all,

if I opening this site:
https://yabwe.github.io/medium-editor/

(it works with a simple blank setup too)

even in Chrome (43.0.23....) either in Firefox ( 38.0.5) / using dev tool to check /
The div with the editable class has these attributes:

contenteditable : true
spellcheck : true
data-medium-editor-element : true
role : textbox
aria-multiline : true
medium-editor-index : 0
data-placeholder : Type your text

After calling the destroy() the following attr still on:

role : textbox
aria-multiline : true
medium-editor-index : 0

Both in Firefox and Chrome.

I most likely a copy & paste coder :) but if there any good article you could link to me, how should I open a "PR" and how can I make a proper fix I can try to fix :) but first please confirm that these fields are necessray parts or just some leftovers.

(oh and yes the op is Win 7, if it is necessary I can test in ie11 too )

**Comment by j0k3r** [comment]
Hum you're right, after `destroy`, I got on Chrome & IE9 on Win:

```html
<div class="editable" role="textbox" aria-multiline="true" medium-editor-index="0" data-medium-focused="true">
```

On Firefox Win:

```html
<div class="editable" role="textbox" aria-multiline="true" medium-editor-index="0">
```

**Comment by nzifnab** [comment]
I can confirm, mac Chrome behaves the same.  It doesn't seem to actually *effect* what the user sees, but it does cause some extra junk to be saved that's a little unnecessary
