### ISSUE TITLE
Textarea attribute not carried over to Div

### ISSUE THREAD

**Issue by mattpickle** [yabwe/medium-editor#711]
When the `textarea` is hidden and `div` element is created, we are losing a custom attribute that styles the element.  Is there anyway we can attach custom attributes to the `div`?

![screen shot 2015-06-28 at 8 58 41 pm](https://cloud.githubusercontent.com/assets/8332157/8414282/0953782a-1e65-11e5-9c73-5d8a3190feb0.png)

**Comment by j0k3r** [comment]
You're right, we didn't keep attributes from the textarea when we create the contenteditable div ([see here](https://github.com/yabwe/medium-editor/blob/master/src/js/core.js#L286-L317)).

I think we can easily provide a way to re-create all attributes from the textarea. And to avoid problem, we shouldn't override attributes we already defined, like `class`, `id`, `role`, etc ..
