### ISSUE TITLE
SelectAllContents isn't always selecting all contents

### ISSUE THREAD

**Issue by gerherz** [yabwe/medium-editor#712]
I'm using selectAllContents() to replace the entire content of the editor:
```
update(value) {
    this.state.editor.elements[0].focus();
    this.state.editor.selectAllContents();
    console.log(this.state.editor.exportSelection());
    this.state.editor.pasteHTML(value);
    this.state.editor.elements[0].blur();
}
```

On an apparently random behaviour, the logged value returned by exportSelection() when the issue appears is:
Object { start: 13, end: 13 }

When this happens, the pasted string 'value' is appended to the content, as if nothing was selected.

**Comment by j0k3r** [comment]
Could you provide a step by step guide to reproduce?

**Comment by gerherz** [comment]
Sorry, I tried to reproduce from scratch but it seems it was content-related, as I can't reproduce it anymore.
