### ISSUE TITLE
Links broken if no protocol provided

### ISSUE THREAD

**Issue by filipkis** [yabwe/medium-editor#714]
When inserting links using the anchor toolbar button and typing for instance only www.google.com (instead of full path http://www.google.com) the href of the anchor will only be set to the typed value, which in turn will cause the links to be broken (directing to http://yourapp.com/www.google.com).

The protocol (http://) is nicely added to links that are created automatically (autoLink = true), but not for the ones created from the toolbar.

**Comment by j0k3r** [comment]
We should add `http://` by default if the inserted link doesn't start with `https?://`.

**Comment by filipkis** [comment]
On further inspection, the adding of protocol works if the `anchor: { linkValidation: true }` is set, so the question is should the protocol also be added when the validation option is turned off?

I'm guessing there should be some consistency between how autoLink and anchor work.

**Comment by j0k3r** [comment]
In fact, the `linkValidation` is actually doing what you asked for. It adds `http://` on anchor link if it doesn't start with a protocol

See https://github.com/yabwe/medium-editor/blob/master/src/js/extensions/anchor.js#L208-L211

I think the question is more, should `linkValidation` be turned `true` by default ?

And you're right about consistency about these two extensions.

**Comment by nmielnik** [comment]
The problem here is that `linkValidation` is an implicit requirement of auto-link.  Auto-link can only do something if it actually detects a valid link, so there can't really be a concept of turning off link validation for auto-link.

So, I don't think these options can be synchronized, however I do think it could be valid for `linkValidation` to be `true` by default...as long as we can convince ourselves that this doesn't require a major release to do :sweat_smile:

**Comment by j0k3r** [comment]
Thinking about it, why this kind of feature is disabled by default and why this is an option at all.

Since anchor is about to insert a link, why people should insert relative link instead of absolute one?

**Comment by filipkis** [comment]
I'm guessing having it as an option would still be good. Maybe in some cases you want relative links because the content is supposed to run on different domains (e.g. local and production), or you might be just creating hash links.

**Comment by j0k3r** [comment]
So we'll switch `linkValidation` defaut value to `true`. But we just need to allow hash url to be valid too.

@filipkis you're more than welcome to submit another PR about that :smile:

**Comment by nmielnik** [comment]
For now, I think it will be better to leave things as there are currently, and not have linkValidation turned on by default.  I don't think the fact that auto-link requires valid links is a strong reason to make the link extension require protocols on urls.

We can definitely revisit this later when there's a better case to be made in favor of it, but for now I'm going to close this issue.  Thanks a bunch for raising this, it was definitely worth discussing.
