### ISSUE TITLE
Unexpected behavior when adding a link inside a list 

### ISSUE THREAD

**Issue by sebastiannm** [yabwe/medium-editor#732]
Hi,

When adding a link inside a list I get a H2 wrapping the UL list for some reason.

I created a fiddle to show it:

http://jsfiddle.net/sebastiannm/9n1rw7tp/

Example:

Select 'W Korea' and add a link to it

**Comment by nmielnik** [comment]
Wow, that is a very strange behavior. Thanks for the jsfiddle, I'll look into this as soon as I can.

**Comment by patrick-webs** [comment]
in firefox a different bug happens, this may be related to the Selection in firefox which is 

    Selection { anchorNode: <li>, anchorOffset: 0, focusNode: <li>, focusOffset: 1, isCollapsed: false, rangeCount: 1 }

compared to in Chrome where it's:

	Selection {}
	anchorNode: text
	anchorOffset: 7
	baseNode: text
	baseOffset: 7
	extentNode: text
	extentOffset: 0
	focusNode: text
	focusOffset: 0
	isCollapsed: false
	rangeCount: 1
	type: "Range"
	__proto__: Selection

**Comment by nmielnik** [comment]
This fix for this should be available in v5.6.1

**Comment by sebastiannm** [comment]
Thank you for the good work
