### ISSUE TITLE
Trigger manually

### ISSUE THREAD

**Issue by seminice** [yabwe/medium-editor#742]
Hi, Is it possible to trigger editing mode manually, a more like a click to edit style?

**Comment by nmielnik** [comment]
You can use the `.selectElement()` method on the editor to cause some text to be selected, and the toolbar to be shown.

`selectElement()` takes in the element you want to be selected, so you can pass in a text node or something from within the editor, or you could just pass the whole editor element itself:

```js
var elements = document.querySelectorAll('.editable');
var editor = new MediumEditor(elements);
editor.selectElement(elements[0]);
```

If you have empty content, you won't be able to get the toolbar to be displayed (unless you're using the `toolbar.static` & `toolbar.updateOnEmptyContent` [options](https://github.com/yabwe/medium-editor/blob/master/OPTIONS.md#updateonemptyselection)), but you'll still be able to get the editor focused.
