### ISSUE TITLE
"Editor.isReady" event

### ISSUE THREAD

**Issue by MartyIX** [yabwe/medium-editor#745]
Hi,

is there an event indicating that the editor was fully initialized?

Thanks

**Comment by j0k3r** [comment]
As far as I know, there is now event like that.
Why do you need this ? In fact, I understand why, I just want to know your use case :)

**Comment by MartyIX** [comment]
I have a modified editor (CSS) so that the toolbar is supposed to be visible all time. However, I would like to display it after all extensions are loaded.

**Comment by nmielnik** [comment]
The toolbar is always the last of the extensions to be initialized, this is enforced in the code, so when the `init()` method runs for the toolbar it's safe to assume all the other extensions have been initialized.

However, if you're looking for a time when you can update your CSS externally, you can just do this immediately after your instantiate MediumEditor.  After the MediumEditor constructor has completed, all the extensions have been initialized, and all of the elements should have been created.

```js
var editor = new MediumEditor('.editor', { ... });
// from this point on, you can assume all extensions are initialized
```

This does present a potentially useful custom event for people to use (`extensionsInitialized`), could make for a good pull request!
