### ISSUE TITLE
Pasting into Medium-Editor in IE removes the editor element from the DOM and replaces it with a text node

### ISSUE THREAD

**Issue by wallylawless** [yabwe/medium-editor#748]
If I open the Medium-Editor demo here: https://yabwe.github.io/medium-editor/ in IE11 and clear it's contents before pasting in text, the Medium-Editor itself is removed from the DOM and no longer available.

For example, say this is the HTML for my editor:
```html
<h1 class="title">My article title</h1>
<div class=".editable .my-article">
    <p>Here is my article text...</p>
</div>
```

and Medium-Editor is initialized:
```js
var myEditor = MediumEditor('.editable');
```

This causes my HTML above to be slightly modified like this:
```html
<h1 class="title">My article title</h1>
<div class="editable" contenteditable="true" spellcheck="true" data-medium-editor-element="true" role="textbox" aria-multiline="true" medium-editor-index="0" data-placeholder="Type your text" data-medium-focused="true">
    <p>Here is my article text...</p>
</div>
```

However, if I now select all the text in my editor instance and delete it, and then paste in text from the clipboard (copied from Word, Notepad, wherever). This is what happens to the DOM:
```html
<h1 class="title">My article title</h1>
<p>This is my pasted text...</p>
```

You'll notice that the entire `.editable` div that `myEditor` was bound to is now gone from the DOM. Highlighting text no longer causes the toolbar to appear, the editor instance is completely wiped out.

As I mentioned, this is reproducible on IE11 using the Medium-Editor public demo at https://yabwe.github.io/medium-editor/.  I also tried with the latest version 5.5.1 (the demo is at 5.1.0) and the same issue was still present.

**Comment by j0k3r** [comment]
I've tested on IE9 and didn't got the problem (ie: the contenteditable now is still here after removing everything). I need to test on IE11 now..

*I'm downloading the ModernIE VM with IE11 :)*

**Comment by hellocosmin** [comment]
Tested the demo page in IE11 (v11.0.9600.17914) and was not able to reproduce the issue. 

I've tried: 

- selecting all and deleting with <kbd>Delete</kbd>, then pasting
- selecting all and deleting with <kbd>Backspace</kbd>, then pasting
- selecting all, hitting <kbd>Enter</kbd>, then pasting
- selecting all and pasting directly, without deleting first.

In all tests, the `.editable` element was not removed.

**Comment by wallylawless** [comment]
I've been able to break down my reproduction steps to be more specific. Also, for completeness sake this is being done on Windows 8.1 in IE11(v11.0.9600.17905) which Windows Update seems to tell me is the latest version for this OS.  Is it possible .17914 is the Windows 10 version?

Here is a screenshot of what the DOM around my editor looks like when I'm starting:
![screen shot 2015-07-30 at 1 21 15 pm](https://cloud.githubusercontent.com/assets/1714627/8990301/44a40af8-36bf-11e5-8a59-4728251b40cf.png)

**Reproduction steps:**
* Select all the contents in the MediumEditor
* Backspace/Delete to remove the text
* Click outside of the MediumEditor so that it loses focus
* Click back into the MediumEditor and paste from the clipboard (keyboard vs. mouse seem to have the same effect)

This is the resulting DOM:
![screen shot 2015-07-30 at 1 23 57 pm](https://cloud.githubusercontent.com/assets/1714627/8990302/44a67cde-36bf-11e5-8b2e-9938a4aef2cb.png)

**Note:** If I don't remove focus from the MediumEditor, or if once I get focus back I type a single character, then pasting the text will work as expected with no loss of functionality.

**Comment by NoelOC** [comment]
I can confirm the same issue.

Win 8 / IE11

Steps to repoduce:
- Select all text in the editor and delete
- Unfocus the editor (this is must)
- Focus the editor and paste the content

Editor is removed and the pasted text is there just as a node.

**Comment by nmielnik** [comment]
@NoelOC @wallylawless the fix for this should be in version 5.6.3, let us know if there are any issues and thanks a ton for reporting this!

**Comment by wallylawless** [comment]
Worked like a charm, hopefully next time I can contribute with some code.

**Comment by nmielnik** [comment]
And if you're looking for some simple ways to contribute, feel free to look at some of the [Easy First Bugs](https://github.com/yabwe/medium-editor/issues?q=is%3Aopen+is%3Aissue+label%3A%22easy+first+bug%22).  I haven't looked much at them recently, but some of them should be low barrier for entry (hopefully) :wink:
