### ISSUE TITLE
Canceling anchor form breaks selection

### ISSUE THREAD

**Issue by kostia** [yabwe/medium-editor#750]
Hello,

I recently discovered a bug making the editor incorrectly determine the current selection after the anchor form has been canceled.

Version: 5.5.1
How to reproduce:

1. Create an editor with anchor extension enabled and present in the toolbar.
1. Try to edit following peace of HTML: `start text <a href="spam">start link end link</a> end text`.
1. Select `start link end link`.
1. Check `MediumEditor.selection.getSelectionRange(document).startContainer` in the JS console.
1. Result: `start link end link` (as expected).
1. Open anchor form and cancel it afterwards.
1. Check `MediumEditor.selection.getSelectionRange(document).startContainer` again.
1. Result: `start text `.

If in step 3. you select only a part of the link text instead of the whole link text (e.g. only `start link` instead of `start link end link`), then everything will work as expected.

Thanks a lot for any advice!

Kind regards.
Kostia

**Comment by nmielnik** [comment]
@kostia when you select text within a link, and then click the anchor form, it should unlink the text.  So, step 6 in your repro steps should cause the link to first be unlinked, and you would have to click the anchor button again in the toolbar to be able to have the anchor form display in the toolbar.  Are you leaving that part of the repro steps out intentionally?

**Comment by kostia** [comment]
@nmielnik Kind of...
I faced the bug for the first time in a custom extension, which was simply a copy of the anchor extension, but with lines https://github.com/yabwe/medium-editor/blob/master/src/js/extensions/anchor.js#L66-L68 removed in order to allow URL editing of an existing link without first unlinking it and losing the current URL. Since I would also have to fill the input with the current URL, I first played with `MediumEditor.selection.getSelectionRange(document).startContainer` and realized that the returned value was changing after cancelation depending on the initial selection. So basically there should be a step 0, which removes lines https://github.com/yabwe/medium-editor/blob/master/src/js/extensions/anchor.js#L66-L68.

**Comment by nmielnik** [comment]
@kostia we have added some fixes around selection when dealing with the anchor form.

Could you verify if your issue still occurs in the most recent code, or in version 5.5.3 (which was just released)?

**Comment by kostia** [comment]
@nmielnik Unfortunately the problem still exists in `5.5.3` :disappointed:

**Comment by nmielnik** [comment]
@kostia so this is an issue of restoring selection.  With our current implementation, there isn't a clear way to distinguish between whether we should restore the selection back to the end of the `start text` node, the beginning of the `<a>` tag, or the beginning of the `start link end link` text node.

There is an option you can enable which will give you the behavior you're expecting: [toolbar.standardizeSelectionStart](https://github.com/yabwe/medium-editor/blob/master/OPTIONS.md#standardizeselectionstart).

You can enable this option by passing it like this:
```js
var editor = new MediumEditor('.editor', {
    toolbar: {
        standardizeSelectionStart: true
    }
});
```

We should probably think about enabling this selection standardization feature in general, and expanding it to not just fix the front of the selection, but the end of the selection as well (and possibly address the inconstancy of double clicking a word to select it in Windows vs Mac #259)

Closing this issue for now, if you run into something else please request this to be re-opened create a new issue.  Thanks!

**Comment by kostia** [comment]
@nmielnik Thanks a lot, it works!
