### ISSUE TITLE
Editor refuse to create links if there is already a link positioned in the very beginning.

### ISSUE THREAD

**Issue by mrdoinel** [yabwe/medium-editor#751]
Hello!

The bug can be reproduced here with latest Chrome : https://yabwe.github.io/medium-editor/
Create a link on "My father" and then try to create another one after. It fails and refuse to create new links.

![screen shot 2015-07-29 at 10 42 27](https://cloud.githubusercontent.com/assets/546129/8953437/b90ad7c8-35de-11e5-93a9-518f9cad637f.png)

The script think that there is already a link so refuse to create a new one. 
Here is the part of the code that seems to be wrong :

```js
            var selectedParentElement = Selection.getSelectedParentElement(Selection.getSelectionRange(this.document)),
                firstTextNode = Util.getFirstTextNode(selectedParentElement);

            if (Util.getClosestTag(firstTextNode, 'a')) {
                return this.execAction('unlink');
            }
```

**Comment by nmielnik** [comment]
This appears to be related to #738, thanks a ton for helping points us in the right direction!
