### ISSUE TITLE
remove the placeholder from UI when setting the content throught setContent method

### ISSUE THREAD

**Issue by ebengtso** [yabwe/medium-editor#768]
i'm using the function setContent and it, in my opinion, should call
yourElement.classList.remove('medium-editor-placeholder')

@nmielnik
> I agree that setting the content should trigger the placeholder to go away, but we'll have to think a bit about the way to implement it. We wouldn't want the setContent method to remove the placeholder attribute directly, since the placeholder logic is in it's own extension and we want to make sure we keep separation of concerns. We'll just need to change around the placeholder extension a bit to know whenever the content changes.

suggestion capture an event on setContent

**Comment by nmielnik** [comment]
The fix for this is now available in version 5.7.0.  Thanks for opening the issue!
