### ISSUE TITLE
Microsoft Edge Support

### ISSUE THREAD

**Issue by nmielnik** [yabwe/medium-editor#771]
We need to:

- [x] Fix tests which are broken in Microsoft Edge browser on Windows 10 (~48 failures as of now)
- [x] Sanity check to make sure things look fine and working as expected in Edge
- [x] Add IE 11 + Windows 10 support into our SauceLabs test runs (Edge isn't supported yet)
- [x] Updated our list of supported browsers (if there's anywhere where we call this out)

#955 includes all the work needed for us to 'support' Edge, we'll cut a new minor release once that work is good to go.

**Comment by j0k3r** [comment]
Is there any way to do 3. stuff in SauceLabs in a way that it doesn't mark the test as fail in case of failing test on Edge ? I don't know enough SauceLabs but with Travis you can define some case where you allow test to fail ([see here](http://docs.travis-ci.com/user/customizing-the-build/#Rows-that-are-Allowed-to-Fail)).

**Comment by nmielnik** [comment]
I don't think there is a way with our current setup, but I'm not completely sure.  Looking through SauceLabs, it looks like they don't support Microsoft Edge yet, but they have lots of Windows 10 combinations so we might want to just start running the tests in Chrome, Firefox, and IE11 on Windows 10 to start with.

**Comment by jdalton** [comment]
SauceLabs supports Edge 12 at the moment.

I noticed Edge 12-13 still don't support the Input event from `document.execCommand` so the sniff will need to be adjusted. Instead of a sniff though I have an inference that works well.

```js
document.execCommand = (function(_execCommand) {
  var isBuggy = true;

  function complete(element, result) {
    if (result) {
      var event = document.createEvent('Event');
      event.initEvent('input', true, false);
      element.dispatchEvent(event);
    }
    return result;
  }

  function getEditable(node) {
    while (node &&
        !(node.nodeType == 1 && node.hasAttribute('contenteditable'))) {
      node = node.parentNode;
    }
    return node;
  }

  function restore() {
    isBuggy = false;
    document.execCommand = _execCommand;
  }

  function exec(cmd, ui, arg) {
    return _execCommand.call(document, cmd, ui, arg);
  }

  function shimExec(selection, cmd, ui, arg) {
    return complete(editable, exec(cmd, ui, arg));
  }

  function shim(selection, cmd, ui, arg) {
    var editable = getEditable(selection.anchorNode);
    editable.addEventListener('input', restore, true);

    var result = exec(cmd, ui, arg);
    editable.removeEventListener('input', restore, true);

    if (isBuggy) {
      shim = shimExec;
      return complete(editable, result);
    }
    return result;
  }

  function wrapper(cmd, ui, arg) {
    var selection = document.getSelection(),
        editable = getEditable(selection.anchorNode);

    return (editable && editable.isContentEditable)
      ? shim(selection, cmd, ui, arg)
      : exec(cmd, ui, arg);
  }

  return wrapper;
}(document.execCommand));
```

**Comment by nmielnik** [comment]
@jdalton before Edge, IE didn't have support for input on contenteditable at all, so it was beyond just calls to `document.execCommand`.  

We actually _did_ have feature inference for detecting input at one point ([commit](https://github.com/yabwe/medium-editor/commit/3205a80006d18c5510695515adb82596bfb8ab0a)), which was similar to the method you're suggesting, but it attempted to detect this as soon as the js loaded instead of the first time someone called execCommand.  Ours was buggy because it required appending a contenteditable element to the page, which is not a good idea when the script could be loaded well before the body even exists, so it got removed in favor of just browser sniffing IE.

So 2 questions:
1. If we switch to feature inference for detecting input when calling `document.execCommand`, is there a good way to detect whether the contenteditable supports `input` for the general edit case? Or would we still need to browser sniff IE<=11 to know that we need to manually detect user modifiations to the editable via things like `keypresss` or `MutationObserver`?

2. When in the page load lifecycle should this feature inference code run?  Wouldn't an actual contenteditable element need to exist in the body and some valid selection exist within that element in order to call `document.execCommand()`?  I suppose you could use the full shim code that you provided, and wait until something calls `document.execCommand()` to then run the feature inference code, but that could potentially be problematic if other code wanted to get a reference to the `document.execCommand` method, since the real method would not be accesible (like a test case for instance).

**Comment by jdalton** [comment]
@nmielnik Super good questions. I don't have a super thorough answer though. I cobbled together a shim that fit my scoped needs for a markdown editor. I didn't have to wire-up keypress handlers so that seemed to be working in Edge.

The issues I ran into were the Input event not firing for `execCommand`, blockquotes not being replaced, and text in containers like h1's not being un-bolded (is that a word?) when the "bold" command is executed (Chrome will wrap text in a `<span style="font-weight: normal;">${ text }</span>`)

It looks like you're digging in over at #955. Are you using [a vm to test](https://dev.windows.com/en-us/microsoft-edge/tools/vms/mac/)? There's also a way to test EdgeHTML remotely (though in an IE shell) with [this](https://dev.windows.com/en-us/microsoft-edge/tools/remote/).

**Comment by nmielnik** [comment]
@jdalton So I've been mostly doing my digging in my Windows 10 machine at home, but I recently grabbed a VM from the exact page you linked to (earlier today actually), and have used that source for all of my other IE testing...it's an awesome resource.  I was a developer at Microsoft for 6 years so I'm more than pleased to see them making these kind of investments to help external developers, something that wasn't nearly as prevalent when I worked there :smile: 

I've also updated the SauceLabs config to run our suite of tests in Edge, thanks for pointing that out I hadn't checked since last fall!

The reason I asked those questions is because before Edge, browsers either fully supported `input` for contenteditable (Chrome, FF, Safari, etc.), or they didn't support it at all (IE<=11).  When I say 'fully supported' I mean `input` is triggered for each of these 3 cases:

1. User adds something
2. User deletes/pastes over something
3. `document.execCommand()` is executed

We created 2 different shims, one to handle 1) & 2) (via monitoring `keypress` and `selectionchange`), and one to handle 3) (via a similar method that you described).

Since browsers either supported all 3 cases, or none of the 3 cases, we could just use feature inference to see if the browser supported 3).  If it's supported, we don't use any shims.  If it's NOT supported, we use both sets of shims.  This would work fine before Edge.

Now with Edge, we don't want to add the shim for 1) and 2), since that would mean `input` would be triggered twice each time, once by the browser and once by our custom code.  However, since Edge doesn't trigger `input` on `execCommand`, we still need the shim for 3).

Thus, if we want to avoid user agent sniffing for Edge, we need to be able to tell if the browser supports `input` for 1&2 vs 3 separately, and right now we just have a way to detect 3) (via inference like what you provided).

So...is there any way to use feature inference to detect whether `input` is triggered when a user adds/deletes text from a contenteditable?  Or, will we just be destined to have to special case via user agent for 'Edge' vs anything else?  I'm not just asking @jdalton, does anyone have any ideas?

**Comment by phiggins42** [comment]
just a driveby to welcome @jdalton to the mix.

**Comment by jdalton** [comment]
PETER HIGGINS!

**Comment by nmielnik** [comment]
Yeah, @phiggins42 helped us significantly with designing our extensions to be easier to implement, and now is just occasionally does drivebys...

Unfortunately @jdalton it looks like Edge doesn't trigger `input` when you paste into a contenteditable, so looks like that's another shim that needs to be added.

**Comment by nmielnik** [comment]
Edge also doesn't trigger `input` when undo/redo are used on contenteditable...I think for now we should probably just use the faked `input` event logic that we used for IE, and just hope that `input` is supported a bit more by Edge in future (at which time we can turn off the shim).

**Comment by jdalton** [comment]
I've filed these bugs on our end (Edge's end).

**Comment by jdalton** [comment]
In Edge 13 I can get the input event to trigger on cut/paste and redo but not undo (ctrl+z).

**Comment by nmielnik** [comment]
Are you just creating a contenteditable element and then using something like: 

```js
<element>.addEventListener('input', function() { 
    console.log('Input Happened'); 
});
```

I tried using Edge 13 on my Windows 10 PC at home (25.something), and wasn't able to get input to fire on paste (I'm not sure if I tried cut or not)...If so I'll need to re-test and will have wasted a lot of time last night trying to build a shim for paste (doh)

**Comment by jdalton** [comment]
Using 
https://jsbin.com/facoho/1/edit?html,js,output

Edit the text in the output pane (it will trigger an alert). Then ctrl+z to undo and notice the alert does --not-- fire.

**Comment by nmielnik** [comment]
Yup, you're right, this was me screwing up my testing. Paste triggers `input` so that's definitely not a bug. Sorry about that.

**Comment by jdalton** [comment]
No worries. I filed a bug on not firing for undo. Thank you for digging into this.

**Comment by nmielnik** [comment]
:+1: 

Out of curiosity are there any bugs open related to `input` not firing for `document.execCommand`?  Is there any way we can keep an eye out for anything on these issues so we can get rid of the shim code for Edge or will it just be easier to manually check periodically after new version updates?

**Comment by jdalton** [comment]
> Out of curiosity are there any bugs open related to input not firing for `document.execCommand`?

Yes, I filed those too.

> Is there any way we can keep an eye out for anything on these issues so we can get rid of the shim code for Edge 

I filed these internally but our issue tracking may be improving sooner than later.

>  will it just be easier to manually check periodically after new version updates

That and I'll try to stay on top of it.

**Comment by nmielnik** [comment]
Thanks a ton @jdalton ! I've wrapped up work for getting all our tests passing in Edge in #955 so we should be able to say we support Edge very soon and can actively keep it that way. Your comments helped motivate me to finally make that happen after 6 months of the branch sitting idly.

After spending so much time living with so many bugs with contenteditable in all browsers, I can't help but get pretty damn excited over the idea that some contenteditable bugs might actually get fixed in even 1 browser!

It's awesome you're out here trying to help, big kudos to yourself and the Edge team(s).

**Comment by nmielnik** [comment]
Some test cases that failed due to some issues with `document.execCommand('insertHtml')` in Edge:
* Remove leading whitespace from the inserted html.
  * "Content TestCase should insert a space when hitting tab key within a pre node" in [`content.spec.js`](https://github.com/yabwe/medium-editor/blob/master/spec/content.spec.js#L529-L538)
    * The code that actually fails is [here](https://github.com/yabwe/medium-editor/blob/master/src/js/core.js#L38) where we try to insert 4 spaces to mimic a 'tab' within a `<pre>`
  * Another example was "Pasting content text with/without linebreaks should be handled consistantly" in [`paste.spec.js`](https://github.com/yabwe/medium-editor/blob/master/spec/paste.spec.js#L390-L430)
    * The test that fails uses [these params](https://github.com/yabwe/medium-editor/blob/master/spec/paste.spec.js#L73-L75), but the resulting output is `<div id="editor-inner">supercalifragilisticexpalidocious </div>` where the leading space at the beginning of the `<div>` has been removed.
* Inserting a `<font size="2">` tag for some reason
  * "Pasting content using cleanPaste should respect custom replacements when passed during instantiation" in [`paste.spec.js`](https://github.com/yabwe/medium-editor/blob/master/spec/paste.spec.js#L271-L286).
    * The code attempts to insert text containing `<label>` tags, which should be converted into `<sub>` tags as part of the test case, but the resulting html is:
```
Before&nbsp;<span id="editor-inner"><sub><font size="2">div one</font></sub><sub>div two</sub></span>&nbsp;after.
```

**Comment by jdalton** [comment]
@nmielnik  Are you seeing the `supercalifragilisticexpalidocious ` bug in Edge 13?

**Comment by jdalton** [comment]
I'm having trouble reproing it. See [this jsbin](https://output.jsbin.com/tubege/3). Once it loads click after the `e` on `spaces` (within 2 seconds of the page loading) and notice the sub string is added and it detects the trailing space. (if the alert fires before you click just refresh the page and try again).

**Comment by nmielnik** [comment]
@jdalton I was able to get this to repro in a [jsbin](https://jsbin.com/hefedosopa/edit?html,js,output).

When you click the button, it selects the contents of the editable and calls `insertHTML` with a string that has leading and trailing spaces.  The leading spaces are removed, the trailing spaces are preserved.

I'm using:
Microsoft Edge 25.10586.0.0
Microsoft EdgeHTML 13.10586

**Comment by jdalton** [comment]
Ah thank you!

**Comment by nmielnik** [comment]
Yeah, no problem.  I've added another [jsbin](https://jsbin.com/paneduxopa/edit?html,js,output) where it shows the innerHTML to better illustrate what happens (since what the various browsers render in the `contenteditable` is a bit-misleading).  I wasn't able to double-check that the issue still repros in Edge though, I'll update this comment when I do.

**Comment by jdalton** [comment]
>  I wasn't able to double-check that the issue still repros in Edge though, I'll update this comment when I do

It still repros.

**Comment by nmielnik** [comment]
Closing this issue, but please let us know if there's any update on any of those Edge bugs!

**Comment by jdalton** [comment]
Rock, will do!

**Comment by studds** [comment]
Raised a public issue to track this: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9886636/

Also created a jsbin to demonstrate the issue along with a bowser + typescript adaptation of @jdalton's shim: https://jsbin.com/tolopuzoke/edit?html,js,console,output
