### ISSUE TITLE
Anchor preview tooltip top position is consistently 140px over what it should be

### ISSUE THREAD

**Issue by jakerichan** [yabwe/medium-editor#774]
![screen shot 2015-08-11 at 3 52 15 pm](https://cloud.githubusercontent.com/assets/991316/9211714/2741769a-4041-11e5-869a-2934eb7b19db.png)

My toolbar diffTop setting is set to -80. When using the default skin, this puts the toolbar directly above my selection.

**Comment by jakerichan** [comment]
I'm not ruling out something on my page, but I haven't been able to find anything.

**Comment by jakerichan** [comment]
Sorry, we had a problem on our end.

**Comment by nmielnik** [comment]
ok, thanks for opening the issue and don't hesitate to bring up any other issues you might be seeing!
