### ISSUE TITLE
ProseMirror and the contenteditable community

### ISSUE THREAD

**Issue by scripting** [yabwe/medium-editor#777]
I came across the ProseMirror project earlier today, and realized there's a contenteditable community that isn't communicating and might be duplicating work. So I wrote a blog post, hoping to gather more pointers, and be able to compare projects. Here's the post.

http://scripting.com/2015/08/12/theresAContenteditableCommunity.html

I'm going to close this "issue" right away. But I wanted to make people in the medium-editor community were aware. Keep on truckin! :-)

**Comment by nmielnik** [comment]
Thank @scripting !
