### ISSUE TITLE
Editing text in inline element with href="#" make text disappear

### ISSUE THREAD

**Issue by maciekmp** [yabwe/medium-editor#781]
jsfiddle: http://jsfiddle.net/65d6duwc/

To recreate: select all text in button and try to add new one.

**Comment by j0k3r** [comment]
Wow interesting.
On a side node I don't think a `<p>` is allowed inside a `<a>`.

**Comment by maciekmp** [comment]
You are right but we need to allow our users to edit content of button links. Do you know if we can replace p tag with span for example?

**Comment by nmielnik** [comment]
So to create editable buttons at my org, we do this:

```html
<a href="#" class="button">
    <div class="editable">Text</div>
</a>
```

```js
editor = new MediumEditor('.editable');
```

Having a `<div>` inside the anchor which is actually editable has allowed things to work as expected. Can you give that a shot?

**Comment by nmielnik** [comment]
@maciekmp were you able to work around the issue?

**Comment by maciekmp** [comment]
Yes, it works for me now if we put div inside anchor. http://jsfiddle.net/65d6duwc/1/ Thanks!

**Comment by nmielnik** [comment]
No problem, thanks for raising the issue!
