### ISSUE TITLE
Static Toolbar - Click Button - Placeholder still visible with content insertion

### ISSUE THREAD

**Issue by epascarello** [yabwe/medium-editor#783]
I am thinking this is related to issue #194 

When I click an h1 button in the static toolbar it adds content to the editor. The problem is the placeholder text is still visible until you type. The screenshot shots the blinking cursor and the custom placeholder text.

![screen shot 2015-08-17 at 10 17 16 am](https://cloud.githubusercontent.com/assets/773311/9306898/385ce252-44c9-11e5-9df8-962598e53f93.png)

Live example: http://jsfiddle.net/u0L6xcuu/ , the h1 button is labeled "Lead" in the fiddle.

**Comment by nmielnik** [comment]
Thanks for opening this, a fix is coming via #787

**Comment by nmielnik** [comment]
Fix is available via version 5.7.0
