### ISSUE TITLE
Auto Link creates links with parts of different <li> tags

### ISSUE THREAD

**Issue by niftykins** [yabwe/medium-editor#790]
I've found if you have an `li` that ends in `.`, and the next `li` starts with a TLD, then auto link creates a link with the end of the first tag, and the start of the second.

[Codepen](http://codepen.io/anon/pen/LVwYXO) to illustrate the issue.

**Comment by nmielnik** [comment]
@niftykins I believe I have a fix for this.  Thanks a ton for opening the issue and creating the codepen! I was able very quickly make a test case to reproduce your issue [here](https://github.com/yabwe/medium-editor/pull/811/files) so thanks again!
