### ISSUE TITLE
Have H1 or bold pressed by default

### ISSUE THREAD

**Issue by sobanhameed** [yabwe/medium-editor#795]
I am assuming there is an easy answer to this. I have looked the documentation but havent found the answer. Is there a way to have some of the toolbar buttons pressed by default? I would like to implement edit on a heading and when empty apply h1, h2 or h3 on it.

Appreciate the help.

**Comment by nmielnik** [comment]
Have you tried starting with a `<h1>`, `<h2>`, etc. tag in the initial content?

```html
<div class="editable">
    <h1></br></h1>
</div>
```

You can always set the initial content via the [`setContent()`](https://github.com/yabwe/medium-editor/blob/master/API.md#setcontenthtml-index) method.

Similar for bold, you might try starting with the initial content wrapped in a `<b>` or `<strong>` tag.

**Comment by sobanhameed** [comment]
I was just adding <h1></h1> earlier and it wasnt working. Adding br helped. Any ideas on why its needed?

Thanks,

**Comment by nmielnik** [comment]
If the text is empty, you need a `<br />` so that there is some kind of inline content to click into.  Otherwise the the contenteditable `<div>` would be empty, and have no height, so you wouldn't be able to get focus into it.  That's my understanding at least.

**Comment by litera** [comment]
@nmielnik Would it then also help if we set CSS
```css
h1 {
    min-height: 1.2em;
}
```
This would also give headings minimum height hence `<br />` wouldn't be needed?

**Comment by nmielnik** [comment]
yeah, that seems like it could work too
