### ISSUE TITLE
Keyboard command shortcuts should first check button extensions

### ISSUE THREAD

**Issue by csarven** [yabwe/medium-editor#802]
If an existing `KeyboardCommands` command key e.g., `B` (for bolding), is overridden when the editor is initialized, e.g:
```
 {
  command: 'strong',
  key: 'B',
  meta: true,
  shift: false,
  alt: false
}
```

it should first check to see if there is a button extension set with the same action value, i.e., `strong`. If it exists, it should trigger that before leaving it to `execAction`.

This is based on the use case where `<strong>` is used instead of `<b>`.

**Comment by nmielnik** [comment]
So the 'command' property that you're passing in to keyboard commands is just the value for the argument that's passed to `execAction(command)`.  So, all the possible buttons exist for medium-editor can be mapped to keyboard commands via this mechanism (`bold`, `indent`, `outdent`, `justifyCenter`, `removeFormat`, etc.).  You can see all of these buttons in [buttons.js](https://github.com/yabwe/medium-editor/blob/master/src/js/defaults/buttons.js).

The `bold` command/action just calls the browser's built in `document.execCommand('bold', false, null)`, which tells the browser to bold/unbold text.  Thus, it's up to the browser how the text is bolded. In Internet Explorer, it will add a `<strong>` tag, in all the other browsers, it will add a `<b>` tag.

Was there something else you were asking for?

**Comment by csarven** [comment]
I was under the impression that the keyboard commands are what could be set for any keyboard shortcut for some action, and not necessarily have any dependency on execAction. Is there a particular reason why a keyboard command should only trigger a built-in command?

I am extending the buttons so that I actually use `<strong>` in place of `<b>` across browsers. Putting more emphasis on the semantics of "bolding" than the visual formatting alone. I would like to be able to carry this out via the keyboard command as well as the `B` command is fairly common across text editors, so when the user triggers the command, while it "bolds" the text, the underlying semantics is aligned with how I'd like to preserve the HTML document.

**Comment by nmielnik** [comment]
So the built-in keyboard commands is currently optimized to allow for mapping any set of keyboard shortcuts to any of the existing actions you can have in medium-editor.  It's just a convenience extension, but you can definitely turn it off or make sure it doesn't do anything whenever keys are pressed. 

If you want to develop your own custom action or custom keyboard shortcut, you could add your own extension which attaches a listener to the `editableKeydown` event, and whenever command/ctrl + <kbd>B</kbd> are pressed, executes your own custom logic.

Another option is to extend the keyboard-shortcut extension, and override the `handleKeydown()` method to do your own custom logic whenever command/ctrl + <kbd>B</kbd> is pressed.

**Comment by willianvazz** [comment]
Hi nmielnik,

Is there a way to use keyboard commands for "h1", "h2", "unorderedlist", "orderedlist", "indent", "outdent"?

I tried to map my keyboard commands like that:

`keyboardCommands: {
            commands: [
              {
                command: "bold",
                key: "B",
                meta: true,
                shift: false,
                alt: false
              },
              {
                command: "italic",
                key: "I",
                meta: true,
                shift: false,
                alt: false
              },
              {
                command: function noop() {},
                key: "U",
                meta: true,
                shift: false,
                alt: false
              },
              {
                command: "h1",
                key: "1",
                meta: true,
                shift: true,
                alt: false
              },
              {
                command: "h2",
                key: "2",
                meta: true,
                shift: true,
                alt: false
              },
              {
                command: "unorderedlist",
                key: "8",
                meta: true,
                shift: true,
                alt: false
              },
              {
                command: "orderedlist",
                key: "7",
                meta: true,
                shift: true,
                alt: false
              },
              {
                command: "indent",
                key: "]",
                meta: true,
                shift: true,
                alt: false
              },
              {
                command: "outdent",
                key: "[",
                meta: true,
                shift: true,
                alt: false
              }
            ]
          },`

and the it only works for **bold**, _italic_ and underline. Is there anything I am missing out?
