### ISSUE TITLE
Support for font type/family?

### ISSUE THREAD

**Issue by sqzr1** [yabwe/medium-editor#805]
Medium editor is a great alternative to the regular editors out there. Are there any plugins/addons for changing the Font-Family of an element? Ie, like the Font-Size addon?

**Comment by j0k3r** [comment]
Nope, there is no such extension at the moment.
But feel free to provide this one ! You can take inspiration from fontSize extension and stuff in the wiki

**Comment by anilmaurya** [comment]
I think this issue should be closed now , @j0k3r is anything pending in this issue ?

**Comment by j0k3r** [comment]
@anilmaurya :+1: 

@sqzr1 You can now see the [Fond Name Extension](https://github.com/yabwe/medium-editor/blob/master/src/js/extensions/fontname.js).
