### ISSUE TITLE
Make toolbar work on mobile

### ISSUE THREAD

**Issue by pedronasser** [yabwe/medium-editor#81]
I've tested with my Galaxy Note and it didn't open.
It should work, right? What do you think?
I'll work something out.

**Comment by shyamal890** [comment]
Is there any updates to this? Is yabwe medium-editor going to support mobile browsers?

**Comment by wislem** [comment]
What an old issue! But hey, here's a quick and dirty solution to anyone interested:

Add this line
```this.on(this.document.documentElement, 'touchend', this.handleDocumentMouseup.bind(this));```
right after
```this.on(this.document.documentElement, 'mouseup', this.handleDocumentMouseup.bind(this));```
found on medium-editor.js:5994

@orthes plugin does not seem to work properly with the latest version of medium-editor and I don't know how to fix it. So skip including that in your list of js and use the above solution.

Cheers
