### ISSUE TITLE
Is it possible to add a class to the html element created by medium-editor?

### ISSUE THREAD

**Issue by superKalo** [yabwe/medium-editor#810]
Hello,

I need to "fake" H1 button, which applies an actual H2 tag in the HTML, but puts a class of ".h1". Is that possible?

Here's my configuration:
```
toolbar: {
    buttons: [
        {
            name: 'h1',
            contentDefault: 'H<small class="text-editor-small">1</small>',
            action: 'append-h2',
            aria: 'Header Type 1',
            tagNames: ['h2']
        }
    ]
}
```
All good, except I don't understand how I can apply a ".h1" class in the H2 element created by medium-editor? Is this possible via the configuration settings?

Thanks in Advance!
Kalo.

**Comment by nmielnik** [comment]
There isn't currently a built-in way to accomplish what you're describing.  However, it shouldn't be difficult to accomplish what you're trying to do with a very simple extension.

Checkout our [Button Tutorial/Walkthrough](https://github.com/yabwe/medium-editor/blob/master/src/js/extensions/WALKTHROUGH-BUTTON.md).  It shows how to create a simple button using rangy's classApplier, which would probably be the easiest way to accomplish what you're trying to do.

**Comment by superKalo** [comment]
Thanks for the swift reply, @nmielnik :)

**Comment by nmielnik** [comment]
:+1:
