### ISSUE TITLE
Auto-p behavior on multiple nested contenteditable="true"

### ISSUE THREAD

**Issue by damiansb** [yabwe/medium-editor#812]
Hello, guys.

I'm planning on using medium-editor.js on some hard html templates for an application, but i ran into a few doubts. Since I couldn't find another place to ask, I'd like to ask here.

Using only one instance of the editor, I can't make auto-p's inside a `div[contenteditable="false"] > div[contenteditable="true"]`. If we type inside it, it won't create the paragraph unless we press [return], in which case there'll be a lingering `<br>` before the `<p>` tag. I wonder if there is a way to make it work correctly wihout having to intance a nested editor inside the first one (it works, but seems messy, idk). 

This is my main doubt, but i'd like to also know if there is a way to prevent [return] in the same situation. it behaves just like the `<p>` issue, `data-disable-return="true"` only works in the root editor element. I could write a custom code that would prevent it, like for some specific class, but I wonder if there is something native on medium-editor.js for that.

**In fewer words, my doubts are:**

1. Is there a way to make `contenteditable="true"` inherit the parent editor behavior?
2. Is there a way to prevent [return] in specific elements inside the editor (via `data-attr` or something)?

**[This fiddle](http://jsfiddle.net/biasiolije/8xL6vakp/3/)** says it better.

I appreciate any help provided. Keep the great work!

**Comment by nmielnik** [comment]
@damiansb I'm not sure if I'm fully understanding what you're asking, but I'll take a stab at answering your questions.

1. The limited experience I've had with mixing `contenteditable=false` with `contenteditable=true` elements has led me to believe that the best way to make things behave you expect them to is to avoid the `contenteditable=false` attribute altogether.  I've recommended this to others as well, but I would explore if it's possible to have your static content/placeholders just as default content, and then specifically choose which elements in the page you'd like to have be editable.  You can pass an array of elements, or a selector that selects multiple elements as the first argument to `MediumEditor`.  This will allow you to have just one instance that covers multiple editable areas.

2. There is not currently a way to target which nested elements within an editor element prevent [return].  This could potentially be a useful feature, and I believe there may be an existing issue that requests this specific requirement.  However, if you are able to go with the implementation I suggested as the solution to your first question, you can just put the `data-disable-reture="true"` attribute on the specific editable fields where you want to prevent [return], and that should be sufficient for the problem you're describing.

Apologies if these aren't the answers you were hoping for.
