### ISSUE TITLE
Can i insert HTML inputs inside of anchor dialog box?

### ISSUE THREAD

**Issue by erickbelfy** [yabwe/medium-editor#816]
I was wondering insert a `<select>` tag inside of anchor dialog box which makes me capable to force user choose specific pages instead of leave a input type text and let user insert any external links. It is possible?

**Comment by erickbelfy** [comment]
Maybe we can implement like, pass an JSON value containing `{"value": "foo", "label": "bar"}` and if we pass this parameter internally the plugin creates the select input with all of my json values.

**Comment by litera** [comment]
You could create your own extension, copy majority of code from `anchorForm` extension and add your specific functionality. That shouldn't be too hard I guess as mostly everything is already implemented.

**Comment by erickbelfy** [comment]
I agree with you, thanks for it!

**Comment by prasannatm** [comment]
@erickbelfy : Hello, would like to know about any implementation based on adding HTML element would be helpful. Thanks!
