### ISSUE TITLE
pre and ENTER (CR / new line) event behaviour

### ISSUE THREAD

**Issue by csarven** [yabwe/medium-editor#818]
Creating this issue for future reference. It may require some enhancement on how <kbd>ENTER</kbd> is handled inside `pre` (preformatted text). Otherwise, it can be closed.

When <kbd>ENTER</kbd> is pressed inside `pre`, a new paragraph starts. There is a brief moment which can be observed, when after <kbd>ENTER</kbd> is fired, the text (after the caret location) appears as a new line in the `pre` block, but then continues to move itself to a new paragraph. The undo operation <kbd>CTRL</kbd>+<kbd>Z</kbd> takes the caret back inside `pre` at the second line. There may be an improvement here e.g., skipping stopover inside `pre`, and/or undoing back to original state before <kbd>ENTER</kbd> was fired.

In order to keep the caret as a new line in `pre`, <kbd>SHIFT</kbd>+<kbd>ENTER</kbd> should be pressed. A single <kbd>ENTER</kbd> allows escaping from the `pre` block.

**Comment by nmielnik** [comment]
Thanks for posting this, people will still be able to locate the issue via search while it's closed, so closing this for now.
