### ISSUE TITLE
Different return options

### ISSUE THREAD

**Issue by DylanPiercey** [yabwe/medium-editor#821]
I couldn't find any configuration options for how return works. Currently "enter" creates a `<p>` and "shift + enter" creates a `<br>`.

It would be nice to be able to configure this, or swap it around.
Ideally "enter" would be a `<br>` and two enters would be a `<p>`, however I'm not sure if that fits everyones use cases.

**Comment by nmielnik** [comment]
@DylanPiercey I believe this is a duplicate of #70 , would you mind looking at that issue and adding any feedback?  For now, I'll close this issue as I think it's a duplicate.  Feel free to open another issue if you disagree.
