### ISSUE TITLE
Extensions documentation is apparently invalid

### ISSUE THREAD

**Issue by litera** [yabwe/medium-editor#822]
I'm trying to make my own MediumEditor extension and I'm following your guide. First I'm myking the simplest possible plugin that doesn't do anything as desribed in [documented example](https://github.com/yabwe/medium-editor/blob/master/src/js/extensions/WALKTHROUGH-EXTENSION.md#1-define-the-extension)

My extension looks like this:
```js
	var MyPlugin = new MediumEditor.Extension.extend({
		name: "my-plugin"
	});
```
and when making the editor I register it as described in the same guide:
```js
new MediumEditor({
    autoLink: true,
    disableDoubleReturn: true,
    toolbar: {
        buttons: /* my buttons */
    },
    extensions: {
        "my-plugin": new MyPlugin()
    }
});
```
**The problem is that I'm getting an exception when creating my extension**
```
TypeError: parent.apply is not a function
    at new Extension.extend.child (http://localhost:82/Scripts/Plugins/medium-editor.js:1503:20)
    ...
```
This error is related to this code in MediumEditor
```js
Extension.extend = function (protoProps) {
	var parent = this,
		child;

	if (protoProps && protoProps.hasOwnProperty('constructor'))
	{
		child = protoProps.constructor;
	} else
	{
		child = function () {
			// *******************
			// THIS LINE BREAKS!!!
			// *******************
			return parent.apply(this, arguments);
		};
	}

	MediumEditor.util.extend(child, parent);

	// Set the prototype chain to inherit from `parent`, without calling
	// `parent`'s constructor function.
	var Surrogate = function () {
		this.constructor = child;
	};
	Surrogate.prototype = parent.prototype;
	child.prototype = new Surrogate();

	if (protoProps)
	{
		MediumEditor.util.extend(child.prototype, protoProps);
	}

	return child;
};
```
So your documentation is likely out of date and a different approach should be used when creating extensions or I'm doing something terribly wrong.

**Comment by nmielnik** [comment]
I'm not 100% this is the cause, but one thing that could be wrong here:

```
var MyPlugin = new MediumEditor.Extension.extend({
    name: "my-plugin"
});
```

So I think the `new` keyword here is incorrect.  You just want `MyPlugin` to be the constructor, so that later you can call `new MyPlugin()` when you pass it in to the extension.

```
var MyPlugin = MediumEditor.Extension.extend({
    name: "my-plugin"
});
```
Try using that instead (with the `new` keyword removed) and see if that fixes the problem.

**Comment by litera** [comment]
I can't believe I've made such a beginners mistake. :) I've been going through built-in extensions and indeed they used the same technique. But somehow the `new` keyword slipped into my own code.

Thanks Nate for spotting it!

**Comment by nmielnik** [comment]
No problem, it's always easier to help spot something like that then actually have to fix something :wink:
