### ISSUE TITLE
Embedded links allow trailing whitespaces

### ISSUE THREAD

**Issue by pranthiks** [yabwe/medium-editor#824]
When I embed links using the medium editor toolbar, I can create links that have trailing white spaces at the end. This becomes a problem when I'm pasting links that I've copied from somewhere else and I've unknowingly copied some trailing white spaces at the end.

I think it would be good to trim any trailing white spaces before and after any links entered into the url field. 

Are there plans to fix this? Also willing to submit a pull request for this.

<img width="665" alt="screen shot 2015-09-28 at 3 38 07 pm" src="https://cloud.githubusercontent.com/assets/7840137/10150932/80756092-65f7-11e5-89c2-4ad5762c9524.png">

**Comment by j0k3r** [comment]
Good point, feel free to submit a PR about that. It's a good candidate for an _easy first bug_. :)

**Comment by nmielnik** [comment]
Fixed via #838
