### ISSUE TITLE
Who's Using medium-editor?

### ISSUE THREAD

**Issue by nmielnik** [yabwe/medium-editor#828]
We're planning on launching a new landing page soon, and if your org is using medium-editor we'd love to include you in our site.

Please reply to this issue with your org and we'll give you a shout-out on our new page.

Don't forget to include **a svg or logo** and **a link to the website** for us to use :wink:

**Comment by steoo** [comment]
Here we are! Intertwine.it :)

**Comment by j0k3r** [comment]
@steoo great! Any logo?

**Comment by jesperbjerke** [comment]
Using it for an open source WordPress frontend editor. https://github.com/jesperbjerke/wa-fronted

**Comment by nmielnik** [comment]
PING! (Anyone else want us to throw their brand/group onto our landing page)?

**Comment by dcsaszar** [comment]
[Scrivito](https://scrivito.com) uses MediumEditor. Currently it's just an [add-on](https://github.com/kostia/scrivito-medium-editor/), but we're about to make it the default WYSIWYG editor.

![logo_green_trans](https://cloud.githubusercontent.com/assets/986170/10573022/725b2c74-764d-11e5-8440-389fab62b8a9.png)

**Comment by j0k3r** [comment]
http://www.lexpress.fr
![](http://static.lexpress.fr/min/images/logos/lexpress.svg)
_it's a svg file: http://static.lexpress.fr/min/images/logos/lexpress.svg_

**Comment by nmielnik** [comment]
Webs & Vistaprint are using medium-editor for building websites:

http://www.webs.com/
![webs-black-white](https://cloud.githubusercontent.com/assets/2444240/10583325/41852264-765a-11e5-94bb-0429ace50fbe.jpg)

http://www.vistaprint.com
![vistaprint-logo-text](https://cloud.githubusercontent.com/assets/2444240/10583333/56becc8e-765a-11e5-89ca-5d61a6a88073.png)

**Comment by litera** [comment]
**[Awesomi.com](http://www.awesomi.com)**
![awesomi-on-red](https://cloud.githubusercontent.com/assets/800583/10932293/fcb43d6e-82cf-11e5-9fad-be92def79139.png)
*Passion discovery and knowledge sharing network*

**Comment by ksavenkov** [comment]
Hmm, don't quite have a logo yet. I use it for Wandest, e.g. look here http://wandest.com/trip/6g

**Comment by nmielnik** [comment]
@steoo @jesperbjerke @dcsaszar @j0k3r @litera @ksavenkov Finally got the Who's using medium-editor section out on the landing page: https://yabwe.github.io/medium-editor/

**Comment by thetylerhayes** [comment]
Awesome! We use Medium Editor on PointPoint http://pointpoint.co and love it

![pointpoint logo transparent](https://cloud.githubusercontent.com/assets/344623/12625587/823db916-c4d8-11e5-94f6-43f106273cf1.png)

**Comment by SakyaStelios** [comment]
We use medium editor at Maytok

![site-logo](https://cloud.githubusercontent.com/assets/5711547/12647886/6dc678a6-c5a5-11e5-9a9f-50e2eb04992d.png)

**Comment by litera** [comment]
@nmielnik :+1: that's great that you added these logos to your page, but... I think they should be in colour as manipulating them to your own liking may not always be allowed. And Awesomi's link points to the wrong place... Just sayin'. :)

**Comment by j0k3r** [comment]
@litera fixed https://github.com/yabwe/medium-editor/commit/206dabb6692d42b824c5c5ad2b13ca63f2dc23e9

**Comment by daviferreira** [comment]
@litera if you have a problem with your logo color just let us know and we will remove the logo, we will use grayscale so we keep the harmony in the page :)

**Comment by GromNaN** [comment]
We use Medium Editor at Prisma Media too and we love it.

![prisma-media-logo-2015](https://cloud.githubusercontent.com/assets/400034/12712997/722335b8-c8cc-11e5-906a-e8f5c1755fc7.png)
http://www.prismamedia.com/

**Comment by nmielnik** [comment]
@thetylerhayes @SakyaStelios @GromNaN welcome to the [landing page](https://yabwe.github.io/medium-editor/#who-is-using-it) (thanks to @j0k3r)!

@litera sorry for screwing up the link to Awesomi's site, that was a pretty lame mistake to make on my part, no excuse there :disappointed:..are you ok with the grey scale logo or would you prefer we take it down?

**Comment by csarven** [comment]
https://github.com/linkeddata/dokieli uses MediumEditor. Logo is on the way.

**Comment by goldensunliu** [comment]
![drift](https://cloud.githubusercontent.com/assets/1348993/12967059/40f76d1c-d031-11e5-9943-093f6c8d3013.png)
![drift 2x](https://cloud.githubusercontent.com/assets/1348993/12967058/40f64df6-d031-11e5-929c-46d0bc212fd2.png)
We are using the code here at Drift! 
www.drift.com

**Comment by nmielnik** [comment]
@goldensunliu @csarven welcome to the [landing page](https://yabwe.github.io/medium-editor/#who-is-using-it)

**Comment by goldensunliu** [comment]
Thanks! So far so good.

**Comment by chasecoolman** [comment]
We use it and love it!

![butter logo full](https://cloud.githubusercontent.com/assets/17017356/13290823/f19d330a-dada-11e5-9918-140b2e77fb34.png)

[Butter CMS](https://buttercms.com) - Enterprise blogging platform built for developers

**Comment by j0k3r** [comment]
@chasecoolman you are now on our website :rocket: https://yabwe.github.io/medium-editor/#who-is-using-it

**Comment by chasecoolman** [comment]
:tada: :balloon: thanks! @j0k3r

**Comment by mgiambanco** [comment]
Just implemented it this last weekend! Great so far!

![logo_color](https://cloud.githubusercontent.com/assets/1078222/14139401/d08979d6-f640-11e5-9de2-b12c15bdf478.png)

**Comment by j0k3r** [comment]
@mgiambanco what's your url website?

**Comment by mgiambanco** [comment]
that might help, hah - https://ignitedds.com

**Comment by n1ckbren** [comment]
Great job! 
https://mozpi.com/press

**Comment by matikbird** [comment]
<h1 align="center">
  <br>
  <a href="https://matikbird.github.io/textiled/"><img src="https://matikbird.github.io/textiled/textile_logo_app.png" alt="Textile" width="200"></a>
</h1>
[https://matikbird.github.io/textiled/](https://matikbird.github.io/textiled/)

**Comment by BtM909** [comment]
We actually use it in one of our products: 
![prose](https://cloud.githubusercontent.com/assets/957242/17251955/04b9956e-55ab-11e6-89b0-815c86db14b8.png)
http://proseditor.com

and for some tools in our company:
![logo](https://cloud.githubusercontent.com/assets/957242/17252020/44d0136c-55ab-11e6-8c4b-322389aafb1e.png)
http://3Fiftynine.nl

**Comment by nmielnik** [comment]
@mgiambanco @n1ckbren @matikbird @BtM909 took a little while this time, but we've added all of you to the landing page [here](https://yabwe.github.io/medium-editor/#who-is-using-it).

Thanks!

**Comment by nmielnik** [comment]
Continuing this push in a new issue (#1191)

**Comment by fuseboard** [comment]
We just added the editor to our product! We customized the toolbar with some SVGs too. https://medium.com/@Fuseboard/hooray-for-easier-formatting-4acdd6ec0fad#.8aue16z3d

![Fuseboard Logo](https://fuseboardcdn.s3.amazonaws.com/Common/logo-color.svg)
[fuseboardapp.com ](http://fuseboardapp.com)

**Comment by j0k3r** [comment]
@fuseboard could please post your comment to the other issue https://github.com/yabwe/medium-editor/issues/1191 ? Thanks.
