### ISSUE TITLE
Bug: disableDoubleReturn prevents getting out of (un)ordered list

### ISSUE THREAD

**Issue by litera** [yabwe/medium-editor#831]
Medium Editor requirements:
* set `disableDoubleReturn: true`
* enable (un)ordered list toolbar buttons

Repro bug steps:
1. add a line of text and select it
2. toolbar pops up, select (un)ordered list
3. your line of text becomes a list item
4. go to the end of this line and press ENTER
5. a new list item is automatically created
6. press ENTER again
7. **nothing happens**

disableDoubleReturn should prevent double empty lines but **should allow getting out of lists**. Otherwise there's no viable way to continue typing text out of a list unless we write a dummy item and select it then clicking the *list toolbar button* to get last item off the list.

**Comment by rishijain** [comment]
Submitted a PR for this:
https://github.com/yabwe/medium-editor/pull/843

**Comment by nmielnik** [comment]
Fixed via #843
