### ISSUE TITLE
toolbar visible as inline HTML elements

### ISSUE THREAD

**Issue by jessegilbert** [yabwe/medium-editor#832]
Greetings all -  and thanks for this great tool.

I'm working on a project that embeds the Medium Editor into a a dynamically generated html page that displays variable annotation data in tables.  The editors are attached to two <TD> elements per table row, with each associated with a different instance of MediumEditor.  

Here's the relevant code:

```js
var noteEdit = new MediumEditor( '.note',
{
	imageDragging: false,
	toolbar: false
});
```

This is attached to the last TD element in each table row.  The information is being rendered using the Chromium Embedded Framework.

The editor is working but I'd like to set toolbar:true.  When I do this, the toolbar buttons render as visible on the page rather than popping up during a selection.  I'm not sure why this is happening, and would appreciate it if anyone could suggest a course of action here.

<img width="534" alt="issue" src="https://cloud.githubusercontent.com/assets/997577/10327125/75c4e5b6-6c58-11e5-86e2-d42f5b34d30e.png">

**Comment by nmielnik** [comment]
@jessegilbert I think the problem is passing `toolbar: true` as the option. Could you try just omitting the `toolbar` option altogether?  Something like:

```js
var noteEdit = new MediumEditor( '.note', {
    imageDragging: false,
});
```

The toolbar option is supposed to be an object which contains a bunch of nested options for controlling the toolbar.  You can see what the default values are [here][(https://github.com/yabwe/medium-editor#toolbar-options).

There is specific support for passing `toolbar:false` for turning off the toolbar altogether, but otherwise it should be an object with nested properties.  I had never actually tested having `toolbar:true` but it looks like it does something undesirable :stuck_out_tongue_winking_eye:

**Comment by jessegilbert** [comment]
Unfortunately omitting the toolbar option altogether results in the same display of the button icons in the rendered web page.  I'm not sure why that is.

Any other thoughts on why this might be happening?

**Comment by nmielnik** [comment]
Are you including the medium-editor css on the page?  If you are, would you be able to create a jsfiddle or codepen to recreate the issue?

**Comment by jessegilbert** [comment]
I have not been including the medium-editor css -  would that make a
difference?

It's not possible to recreate the issue using the jsfiddle or codepen tools
because the page is rendering data that is available through an embedded
CEF browser, and that data model is passed in from the host application via
a shared memory space.

I have tried several of the medium-editor examples in the CEF browser and
the toolbar behaves as expected.  The only difference that I can see is
that the HTML elements in the examples is pre-generated, while in my
application the table, row, and table document tags are generated
dynamically in response to the data that is passed in.

I have also defined several custom event handlers, and attached them via
the subscribe() method.  I didn't see an example of that so I'm not sure if
I'm doing that correctly.

Without sending you the raw script, which is quite long, I'll describe the
process in pseudo-code:

- HTML file has a single top-level DIV with id=container.

- in the JS script, for each timestamp/annotation pair in data model:

   - create new DIV (all create routines use document.createElement() )
   - create new table
   - create new row
   - create TD elements
      - timestamp element, class = time
      - annotation element, class = note
      - add TDs as children of row (all adds through element.appendChild() )
   - add row as child of table
   - add table as child of new DIV
   - add new DIV as child of container

- create new instance of MediumEditor, paired to class '.time'

- create new instance of MediumEditor, paired to class '.note'

- subscribe to events appropriate to each MediumEditor instance:

   - 'focus', 'editableInput' and 'editableKeydown' for timestamp editor
   - 'focus', 'editableKeydown' for note editor


I use a custom css file with styling guidelines for the classes 'tables',
'time', and 'note'.

Anything stand out that I should be doing differently?

**Comment by nmielnik** [comment]
Including the medium-editor css file will definitely make a difference, the hiding/showing of the toolbar and all of its appearance depends on the css being there.  Definitely try to include it and see if that fixes some or all of the issues.

**Comment by jessegilbert** [comment]
That solved it -  thanks!

**Comment by nmielnik** [comment]
no problem, apologies if the documentation wasn't clear.
