### ISSUE TITLE
Option for Default Styling

### ISSUE THREAD

**Issue by afang** [yabwe/medium-editor#837]
There should be an option when creating a new editor to start off with some buttons active. E.g. select `h2` instead of `p` text by default

**Comment by daviferreira** [comment]
Could you provide a use case for it? I'm not sure if I understand it.

**Comment by afang** [comment]
In order to make API calls I need a client_token and client_id, which I’m not sure how to get since I only have an integration token.


Andy

**Comment by afang** [comment]
An example would be Medium's native editor which has two fields: the first input is `h2` by default and the second input (the body) is `p` text.

**Comment by nmielnik** [comment]
@afang 2 ways I could see doing this:

### 1.
```html
<div class="editor">
    <h2>Default Title</h2>
    <p>Default Body</p>
</div>
```

### 2.
```html
<div class="editor">
    <h2>Default Title</h2>
</div>
<div class="editor">
    <p>Default Body</p>
</div>
```

In both cases you would initialize medium-editor like this:
```js
var editor = new MediumEditor('.editor', { /* options */ });
```

In both cases, you can have the content start out with an `<h2>` and a `<p>` as the default content.  Is there something else we're not understanding about the case?

**Comment by afang** [comment]
The second solution works but ideally it should be done with a placeholder in an empty field instead of default text.

Andy

**Comment by nmielnik** [comment]
That is supported as well:

```html
<div class="editor" data-placeholder="Type a title">
    <h2><br/></h2>
</div>
<div class="editor" data-placeholder="Type a body">
    <p><br/></p>
</div>
```

That should allow you to have placeholders instead of default content, would that work?

**Comment by afang** [comment]
Adding the break works. Thanks!
