### ISSUE TITLE
<ul> or <ol> are not created as direct children of the editor but are wrapped in a <p> tag

### ISSUE THREAD

**Issue by brijeshb42** [yabwe/medium-editor#841]
### Before (A normal paragraph)

<img width="1184" alt="screen shot 2015-10-12 at 3 06 01 pm" src="https://cloud.githubusercontent.com/assets/717550/10425152/eb6f8fde-70f2-11e5-985f-fe89e61b1e00.png">
### After (When I try to convert that to a list)

<img width="1229" alt="screen shot 2015-10-12 at 3 06 43 pm" src="https://cloud.githubusercontent.com/assets/717550/10425175/0f56fed2-70f3-11e5-9cdc-eb2e52c7adfd.png">

The `ul>li` is created inside that `p` tag. Also there are some `span`s created.

**Comment by litera** [comment]
@nmielnik Can you please tell me what the *html cleanup* label means? Does it mean that this is being addressed or just that it needs HTML cleanup? Should cleanup be done by apps using Medium Editor or should ME's code do the cleanup?

**Comment by j0k3r** [comment]
The html cleanup tag means: we need to take care of the html inserted because of the contenteditable madness. ME needs to cleanup the inserted code.
In that case, we should avoid list to be created inside a paragraph.

**Comment by litera** [comment]
@j0k3r but nobody's assigned to this issue. How do things work with this project? Who decides what gets developed and by who?

**Comment by j0k3r** [comment]
We don't often assign issue. We handle issue when we have time and when we know how to fix it

**Comment by nmielnik** [comment]
@litera things get developed whenever anyone decides they want to fix any open issue or add a new feature.  For bigger changes, it might be worth having a discussion via a github issue or gitter about exactly how to implement something, but in general we'll just give some code review feedback.

The less things in the way of enabling anyone to help improve medium-editor, the better :smile:

**Comment by heathcliff** [comment]
Hi everyone

Has any progress been made on this? I would love to use this editor for a new app I am working on, however I can't until this issue has been resolved. I really appreciate it!

**Comment by nmielnik** [comment]
It looks like @j0k3r took a crack at fixing this exactly issue as part of 7e12a24b14b46b44cce9e2422c9abcc1c81e706e.

If you're still seeing the issue, it might be worth stepping through the [`util.cleanListDOM()`](https://github.com/yabwe/medium-editor/blob/master/src/js/util.js#L604-L618) method to see why it's not working as expected.

As you can see [here](https://github.com/yabwe/medium-editor/blob/master/src/js/core.js#L838-L841) The `util.cleanListDOM()` method is automatically called each time either of the `insertunorderedlist` or `insertorderedlist` commands are executed via the toolbar.

@j0k3r any recollection of this?

**Comment by heathcliff** [comment]
Thanks @nmielnik, that's helpful. I noticed that this may be related to Chrome's ContentEditable span insertion bug. When I logged `element` from `util.cleanListDOM()` I kept getting a span tag with an inline style of `letter-spacing`. Removing the `letter-spacing property` from my CSS resolved this issue, so it's nice that there is at least a workaround.

Would it be worth implementing some sort of span detection to ensure this doesn't happen? This is an old article (and seems to rely on jQuery) but seems interesting: http://www.neotericdesign.com/blog/2013/3/working-around-chrome-s-contenteditable-span-bug

**Comment by j0k3r** [comment]
@heathcliff Yeah I've started working on that _span_ bug few months ago, here: https://github.com/yabwe/medium-editor/pull/801, but didn't found the time to finish it :confused:

**Comment by litera** [comment]
I'm using Medium editor in an Angular app and I've solved the `span` problem like this:
```javascript
function cleanupParser(value) {
	// remove all browser created spans (Webkit quirk) and inline styles
	this.find("span").contents().unwrap();
	this.find("[style]").removeAttr("style");

	// provide content HTML value when applicable
	return !!this.text().trim()
		? this.html()
		: "";
}
```

I added this *parser* in the `link` function like this:

```javascript
// add parsers
ngModelController.$parsers.push(angular.bind(element, cleanupParser));
```

And it does the trick. It immediately any `span` elements by unwrapping them (because I don't allow these elements anyway) and also removes any inline styles if set by whatever process...

You should be aware that for this to work in an Angular app you also need jQuery lib. If you don't use one (just use the jqLite that Angular lib comes with, you should change that to replace `span` element with its content by calling `span.replaceWith(span.children())`. This would accomplish the same thing.

**Comment by j0k3r** [comment]
@litera I'm aware that this kind of fix should be easy with jQuery but we don't want to use any jQuery alternative to achieve that. That's why I prefer to try using MutationObserver.

**Comment by litera** [comment]
@j0k3r That's why I said that if you're using an Angular app you can get away without jQuery just as well. And if you're using vanilla Javascript you can pull it off regardless... It's the code I'm using that works as expected that one can adopt for their own needs.

**Comment by photodialectic** [comment]
I feel like [util.cleanListDOM()](https://github.com/yabwe/medium-editor/blob/master/src/js/util.js#L604-L618) wouldn't work regardless of the span issue - the logic assumes the parentNode of an `<li/>` would be a `<p/>` and to clean up if that's the case but it would always be either a `<ol/>` or `<ul/>` wouldn't it?
