### ISSUE TITLE
[question] Modify contents from external js

### ISSUE THREAD

**Issue by ksavenkov** [yabwe/medium-editor#848]
I want to add simple html snippets to the contents edited in the Medium Editor from external js widgets. An example is to paste an `<img>` tag using some 'add image via link' button outside of the editor.

I know about http://linkesch.com/medium-editor-insert-plugin/, but it requires JQuery and is a way too advanced than I need. 

I suppose inserting `<img>` tag to the last focused place in the editor should be easy, but I can't find any example. What's the proper way to do that? My first guess is to trigger pasteHtml method outside of the editor - is this a right approach?

**Comment by litera** [comment]
Medium editor already has the ability (AFAIK) to simply insert images that are on the web. When you create ME instance include image button and then while you edit, you can paste a link to an image, highlight it and then simply click the image button. I think that's the way it's supposed to work with simple images.

For small (in storage size) you could also just drag and drop an image to your editable content where images will get inserted as base64-encoded data URLs... So they actually get embedded in the content itself. Mind that that can severely increase the size of your content.

**Comment by ksavenkov** [comment]
I see, but that's completely different UX from what I need. I've seen some comment here that image insert buttons (as they done on the original Medium) need to be in the separate js as the main toolbar is for working with selections. My question is how to add something to the ME content from that separate js.

**Comment by nmielnik** [comment]
@ksavenkov you can use [`pasteHTML()`](https://github.com/yabwe/medium-editor/blob/master/API.md#pastehtmlhtml-options), which will replace the currently selected text within the editor with whatever HTML you provided.  If it's just a cursor, the html should get inserted wherever the cursor is.  Hopefully that will work for your use case.

**Comment by ksavenkov** [comment]
thanks, will try
