### ISSUE TITLE
How to use it with textarea? 

### ISSUE THREAD

**Issue by mmuruev** [yabwe/medium-editor#849]
Doc says hide the textarea, but if I set hidden class then actually the editable div will be hidden to. Also for text area I have rows set, but new div just one line div. So is possible have this work without tinkering out of box. If not then will be nice have working example in the doc.

**Comment by j0k3r** [comment]
There is an example in the demo folder on how textarea are handled: https://github.com/yabwe/medium-editor/blob/master/demo/textarea.html

You don't have to manually hide the textarea, Medium Editor do that on its own. Also, if you want the Medium Editor div to have a min-height / min-width, you can do that using CSS.

**Comment by mmuruev** [comment]
No it doesn't... Text area are still showing. About sizes, why not use rows value for div height?

**Comment by j0k3r** [comment]
Could you please provide a jsfiddle for your problem?
I've created [this one](http://jsfiddle.net/xjcb45mh/) with textarea and the textarea isn't displaying.

About size, yes it could be an idea. Which calcul do you suggest for rows/cols conversion to pixel ?

**Comment by mmuruev** [comment]
I've found source of problem thanks to your example class="editable medium-editor-textarea" are required. Which is my opinion not pretty obvious thing we already passed element in constructor. About calculation. I think no need use actual pixels.. may be we can just use 'em' ?? or line height calculation like this 
           
       var fontSize = $(el).css('font-size');
       var lineHeight = Math.floor(parseInt(fontSize.replace('px','')) * 1.5);

**Comment by j0k3r** [comment]
It also works if you remove `medium-editor-textarea`.

Thanks for the calcul, we'll see what can we do about that. Could you open a different issue about that calculation? Thanks !

**Comment by amitxcelance** [comment]
tyrtyrtyrty
