### ISSUE TITLE
Is it possible enable/disable formatting?

### ISSUE THREAD

**Issue by mmuruev** [yabwe/medium-editor#851]
For example I if I need apply or remove format by state another field. then formatting ON apply everything.. if it of restore only original text without any tags. Is it possible?

**Comment by nmielnik** [comment]
I'm not quite sure what you're asking, could you provide an example of what you're attempting to accomplish?

We do have a `removeFormat` button you can enable in the keyboard, which allows the user to strip formatting and reset back to unformatted text.  You can see the button [here](https://github.com/yabwe/medium-editor#all-buttons)

There are some limitations to what the `removeFormat` command actually removes (it doesn't remove `<span>`, `<label>`, or `<br>` elements for example)

**Comment by litera** [comment]
@mmuruev Is this a kind of feature that other WYSIWYG editors have when you switch between rich text editor and plain old HTML text editor?

**Comment by mmuruev** [comment]
Well example. I have form which send messages for different receivers.. some of them do support tags some not. Easiest example email. It can be plain text or html. Will be nice if opportunity get 'just text' or apply with formating will exist.

**Comment by litera** [comment]
Ok so you want a rich text editor (MEdium Editor) but want the ability to either get HTML or text-only results in your code? That shouldn't be a problem either. Every HTML element has `textContent` property that returns concatenated text nodes so you can easily read text of your rich content.
