### ISSUE TITLE
Making empty tags on empty message.

### ISSUE THREAD

**Issue by mmuruev** [yabwe/medium-editor#853]
Seems sometimes for no message editor can generate something like this.
   

         <p><br></p><p><br></p><p><br></p>

 So for user it looks like empty and even show 'type your text here' but for backend validator this is actually the data. Probably the bug? I'm using the latest CDN version.

**Comment by rishijain** [comment]
If I am understanding this correct, this happens every time you press 'enter' ? On every enter key pressed, it adds a "<p><br></p>" tags. You can use 'disableDoubleEnter' option to not allow multiple 'enter' keypress events.

**Comment by nmielnik** [comment]
I'm not sure if rishijain's recommendation solved the issue, or what the desired behavior would be here, so closing this for now...definitely happy to re-open if there's some updates or clarification.

**Comment by clemsontiger** [comment]
this is happening to me too, even though the textarea box looks empty, there are underlying <p><br></p> that won't clear. these tags should be cleared if the box contains no user initiated content.
