### ISSUE TITLE
Add options parameter to extension init method?

### ISSUE THREAD

**Issue by pecuchet** [yabwe/medium-editor#860]
Or is there another way to configure an extension upon instantiation? Something like:

```
extensions: {
  plugin: new MediumExtension({ /* options here */ });
}
```

Thanks!

**Comment by nmielnik** [comment]
Yes, this is how you instantiate any custom extensions you're passing into MediumEditor.  After creating the instance and passing the instance in via the `extensions` property, MediumEditor will call `init()` on each extension.  

The built-in extensions that come with MediumEditor have their options passed in directly (ie `toolbar`, `anchorPreview`, etc)

**Comment by pecuchet** [comment]
Ok nice! And I see now that extensions can catch their options with `getEditorOption`.

Thanks
