### ISSUE TITLE
Option to retain allowed tags?

### ISSUE THREAD

**Issue by brijeshb42** [yabwe/medium-editor#868]
Is there any option to allow retention of certain tags that have been allowed in the toolbar buttons options
like h2, bold, anchor etc. when copied HTML from some website is pasted into the MediumEditor ?

**Comment by j0k3r** [comment]
Hum nope it's not possible at the moment. We can only remove some tag or attributes.
https://github.com/yabwe/medium-editor/blob/master/OPTIONS.md#paste-options

What is your use case? Which tag would you like to keep?

**Comment by brijeshb42** [comment]
There's no specific tag. I just wanted to know if there was any way to retain only the tags that were enabled in the toolbar.

In my editor, authors paste copied content from word docs or from other websites but they loose the formatting as I have `forcePlainText: true` for now as I don't want the copied content to mess up the final HTML because of other tags that I don't want when I set `cleanPastedHTML: true`.

**Comment by nmielnik** [comment]
This seems like an interesting enhancement, basically a set of filters that removes all non `contenteditable` tags from pasted text.  We have a bunch of built in filters for removing certain tags, perhaps there could be an additional paste option to enable another set of filters?

**Comment by hraynaud** [comment]
@nmielnik +1 on this.

**Comment by brijeshb42** [comment]
@nmielnik [http-janitor](https://github.com/guardian/html-janitor) is a good example.

**Comment by Dortamur** [comment]
I also need something similar - I'd like to _only_ keep specific tags (like the ones from the toolbar), and remove _all_ other tags, when HTML is pasted. That way, I can white-list innocuous stuff like p, i, b, em, div, a, and strip all other tags.

Similarly, I'd like to remove _all_ attributes _except_  white-listed ones. (Although I'd settle for just removing all)

As a simpler option, you could provide a hook to do the HTML cleaning. So any pasted HTML gets passed to the hook, which returns the cleaned/filtered output, becoming the content.

**Comment by nmielnik** [comment]
@Dortamur @spiderpug @thomasaull the paste-extension exists as an overridable extension to allow folks to customize the paste handling any way they want.

Based on what @Dortamur was describing, I believe you'd want to override the `cleanPaste(text)` method of the paste-extension, which is ultimately called during the paste-handling chain.  `cleanPaste()` is where all the regex's are executed for replacing the pasted html, and it ultimately calls `pasteHTML()` once the text has been cleaned up.

You can see the base implementation of `cleanPaste()` [here](https://github.com/yabwe/medium-editor/blob/5.22.2/src/js/extensions/paste.js#L383-L427).

At the end of the method, it will ultimately call `pasteHTML()` which is defined [here](https://github.com/yabwe/medium-editor/blob/5.22.2/src/js/extensions/paste.js#L429-L459).

You can build a complete paste-handling extension and pass it in via the extensions option while instantiating the editor (example [here](https://github.com/yabwe/medium-editor/tree/master/src/js/extensions#extension-interface)).

If you want to just override `cleanPaste()` and/or `pasteHTML()`, you can pass in your custom overrides individually when instantiating the editor:

```js
var editor = new MediumEditor('.editor', {
    paste: {
        cleanPaste: function (text) { // your custom code },
        pasteHTML: function (html, options) { // your custom code }
    }
});
```

**Comment by thomasaull** [comment]
@nmielnik Thanks a lot for your help! I actually tried your second approach, overwriting the pasteHTML function when initiation the editor, but this didnt't work at all, my function just doesn't gets called: 

```
paste: {
	cleanPaste: function (text) { console.log("clean paste"); },
	pasteHTML: function (html, options) { console.log("paste html"); }
},
```

**Just to make sure:** I can use this **without** creating an additional extension before, right?

**Comment by mauricekindermann** [comment]
Just adding my vote for this. Seems odd that you could enable "Bold", but then cannot cut/copy/paste bolded content. 

A function like `allowedTags: ['b', 'strong']` would do the trick. 

![image](https://i.imgur.com/eaLnr0I.png)

I'm doing my best to figure out if I can simply hack this out of the code, no luck yet. I will let everyone know if I get it working.

Update: These 3 functions are causing the tags to be stripped: `handlePaste, handlePasteBinPaste, createPasteBin`, or by commenting them out it prevents stripping from occuring.
