### ISSUE TITLE
Does this editor support tags other than div?

### ISSUE THREAD

**Issue by amirmohsen** [yabwe/medium-editor#871]
I'd like to instantiate the medium editor on a h1 tag and completely disable formatting for it, similar to [the inline mode on this other medium editor](http://jakiestfu.github.io/Medium.js/docs/#inline).

I figured that using the following three options should achieve my needs, but it seems like the options are completely ignored unless I instantiate the editor on a div tag, which is obviously not what I want. Essentially, what it comes down to is that in certain places, I have to limit the user to only editing the content of a certain tag in plain text without adding new lines, tags or any formatting.

```JS
{
    disableReturn: true,
    toolbar: false,
    keyboardCommands: false
}
```
Is this an expected behavior of the editor or a bug? If it's considered a bug, I can investigate and try to fix it. Just figured it's worth asking first.

**Comment by j0k3r** [comment]
First question that hit my mind: why do you want to enable MediumEditor on a tag where the user won't be able to format text and adding new line? Basically the user will only be able to write inside it. So why do you want to use MediumEditor for that .. ?

**Comment by amirmohsen** [comment]
I need certain tags to be editable only to the point that you can add plain text in them. Basically some parts of the template are restricted and tag type shouldn't change and there shouldn't be any formatting allowed for the user. Imagine an article template where the user can edit the article header and subheader, but not change their position or type.

As for why using MediumEditor or any other inline editor for that matter, that's a bit of an odd question. I either have to use an existing solution or build my own. As for building my own, it's not as easy as adding contenteditable to the tag. I have to capture the enter keycode as well as any other keyboard combination which is used for formatting (and is different across browsers/platforms). I also have to handle paste content to strip out tags. You see where I am going with this? I'm looking for a tested solution out there that does this. If I can't find any, I just build my own.

So far, only this other [Medium.js editor](http://jakiestfu.github.io/Medium.js) has the inline mode that I need. Unfortunately, the editor itself doesn't have all the other features that I need. Of course, I can use two different editors, one for rich text and the other for plain text, but I'm trying to avoid that if possible.

Anyway, you didn't really answer my question. All I was asking was if this editor is supposed to work only on divs. The three options specified above should actually do what I need, but it doesn't seem they work if I instantiate the editor on a h1 tag.

**Comment by nmielnik** [comment]
@amirmohsen so this issue has been discussed in other issues ( #833 is the most recent one I've found) but ultimately I don't have a lot of knowledge of how the browser handles putting `contenteditable` on elements other than `<div>`.

The example you are pointing to in Medium.js is actually using a `<div>` for the `contenteditable`, but is adding css classes to make it appear like a header or `<h1>`.  Have you considered this approach?

Another option is to start with this html:

```html
<div class="editor"><h1><br/></h1></div>
```

If you instantiated the editor here (with the 3 options you included above) the user should only be able to edit text within the h1, and shouldn't be able to add new lines.  They may be able to delete the `<h1>` completely, which is the downside of this approach (compared to the approach of just using css to make the editor `<div>` look like a `<h1>`).

Could either of these approaches work for you?

**Comment by dcsaszar** [comment]
#865 is another recent one, asking about SPAN

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Comment by shark0der** [comment]
I have a similar situation. I'm using the editor for titles - currently in the same manner as @amirmohsen did, paragraphs with toolbar, and the new use-case is allowing the user to edit lists.

Currently I just initiate the editor with `<ul><li>&nbsp;</li></ul>` and the user edits it directly. The edge case is when the user deletes all the content in the editor which leads to the `ul`/`li` tags being deleted and simple `p` tags added when user starts typing.

A setting to be able to specify allowed/whitelisted tags would be really useful.

**Comment by nmielnik** [comment]
@shark0der could you go into more detail about what feature you'd like to see for this?  Would a feature that prevents the editor from ever being empty work for this (ie if the user tries to delete everything, the editor inserts tags back in like your `<ul><li>&nbsp;</li></ul>`)?

If you wouldn't mind, could you open a separate issue outlining the feature request?  Perhaps just reference this one from there...

**Comment by shark0der** [comment]
@nmielnik until I open another issue, I'd like to shortly discuss it here to figure out if what is worth to open a new issue for.

There are 2 things that I currently would really like to have:

- A default/empty value (maybe not the better name). Looking at the API I've found [pasteHTML](https://github.com/yabwe/medium-editor/blob/master/API.md#pastehtmlhtml-options) and I think that just spying on the content and injecting html is enough (would love to hear your opinion on this matter though). As a side note, another issue which I've not tested yet outside of my project is that if I'm not adding the `&nbsp;` - the editor is not clickable (doesn't focus).

- A way to whiltelist/blacklist html tags - something similar to [tinymce's valid_elements](https://www.tinymce.com/docs/configure/content-filtering/#valid_elements). This is actually a pain-point since I noticed that the editor sometimes even adds `<p>` tags inside `<li>`s which in my case is totally not OK - the page builder handles the case when there's just text inside `<li>` but when adding paragraphs the line-height, margins, font-size is different and I am forced to handle both cases in CSS.

**Comment by nmielnik** [comment]
@shark0der many apologies for taking so long to get back to this, it doesn't take much for my days to be overflowing with activity 😄 

I think both 1 and 2 are perfectly good feature requests.

Regarding the issue you talked about in your 1st item, it's know that if the editor is completely empty it ends up with 0 height and you can no longer click into it.  Currently, the editor attempts to handle this by inserting `<p><br /></p>` (not `&nbsp;`) as I think at least one editor (maybe Firefox?) actually inserts that `<p><br /></p>` on its own in some cases.
