### ISSUE TITLE
Keeping the two objects in sync

### ISSUE THREAD

**Issue by scripting** [yabwe/medium-editor#872]
I read in the docs that medium-editor keeps the two objects, yours and mine, in sync, so I can just get the value of my object without having to fuss with the parallel object.

I've come across a situation where they apparently are not being kept in sync and have been trying to work around it by finding your object and just getting and setting the value directly, but this doesn't seem right. 

What causes a sync? How can it go wrong? Is there a way to trigger a sync event manually? I'd rather not have this workaround in my code.

**Comment by nmielnik** [comment]
Could you give some more context here?  When you say "two objects", what do you mean? What are you calling to get data?

**Comment by scripting** [comment]
Let's close this. I had to work around the problem because I had to ship. ;-)

If I encounter it again I'll try to get a simple test that illustrates.
