### ISSUE TITLE
Specify phone number on anchor select.

### ISSUE THREAD

**Issue by DylanPiercey** [yabwe/medium-editor#873]
Currently it looks like the anchor option will detect emails and automatically add mailto: however does not do the same for phone numbers. I am not sure if this has been resolved (although I couldn't see anything in the change logs) and I am using version 5.0.0

Is there something I am missing or can this be added?

**Comment by j0k3r** [comment]
No, we support `tel:` link in the previous release.
We only support `http(s)`, `ftp(s)`, `rtmp(t)` & `mailto`

:arrow_right: https://github.com/yabwe/medium-editor/blob/76164c997e2cb326ecf035aef63bfb8400ddb881/src/js/extensions/anchor.js#L235

Feel free to add it! :)

**Comment by ppoulsen** [comment]
I added `tel:` as a recognized scheme in #878.

As for @DylanPiercey's original question about automatically adding `mailto:` to emails, I don't believe medium-editor does anything to recognize emails in the anchor and add `mailto:` to them. It will only add `http://` when it doesn't find a matching scheme and `anchor.linkValidation === true`.

**Comment by nmielnik** [comment]
Yeah, if an email address is automatically being prefixed with `mailto:` I don't believe it's our code that's doing it (unless you're using the auto-link feature, but even then I'd be surprised if it was auto adding this).  Some browser may do this automatically, as I know IE had auto-linking built into it for a while.

I think there are 2 ways to think about this:
1. When user enters something into the anchor form that looks like an email or phone number, automatically adding `mailto:` or `tel:`
2. For the auto-link extension, automatically finding anything that looks like an email or phone number, and turning it into a link.

Option 2 would definitely be much trickier, but I still think Option 1 is a simple thing that someone could pick up easily, given they have some reliable regexs.

**Comment by rishijain** [comment]
I think somewhere between https://github.com/yabwe/medium-editor/pull/878 and https://github.com/yabwe/medium-editor/pull/877 this issue got resolved. Closing this. 🔒
