### ISSUE TITLE
Change in text size affects whole paragraph

### ISSUE THREAD

**Issue by lizraeli** [yabwe/medium-editor#874]
When I highlight a certain area of text and click on H2, H3, or blockquote, the entire paragraph that contains my selection changes size. I checked on both Chrome and Firefox.

**Comment by j0k3r** [comment]
Could you provide a jsfiddle to reproduce the bug? Thanks

**Comment by lizraeli** [comment]
http://jsfiddle.net/gh/get/library/pure/lizraeli/medium-editor/tree/master/demo

**Comment by j0k3r** [comment]
Oh I see. It has always worked like that. And medium.com has the same behavior.

When you select a part of a paragraph and change the _main_ tag to "block" element (like h1, h2, blockquote, ul, etc..) it converts the paragraph to the block element. Link, bold, italic, etc .. aren't block element.

This is something that won't be fixed I guess.

**Comment by nmielnik** [comment]
Agreed, this is behavior that is common not just in contenteditable or browser editors, but client editors as well.
