### ISSUE TITLE
Disable fileDragging

### ISSUE THREAD

**Issue by cblavier** [yabwe/medium-editor#876]
I'm using mediumEditor with a custom drag'n drop behavior but it seems that MediumEditor is catching all dragover / drop events.

I tried to disable this behavior with `imageDragging: false` and `fileDragging: false` but it's not working.

At the moment, the only solution I found out was to comment out this line
`extension = new MediumEditor.extensions.fileDragging(opts);`

Thanks for your help

**Comment by gpbmike** [comment]
The following appears to do what you want by returning the desired response (`false`) from the `shouldUseFileDraggingExtension` method (https://github.com/yabwe/medium-editor/blob/df8bde11dcbb48d9e394c3affb9524aaa4c9be49/src/js/core.js#L289-L294)

```javascript
    new MediumEditor(editorNode, {
      extensions: {
        'imageDragging': new YourCustomExtension(),
      },
    });
```

**Comment by anilmaurya** [comment]
Are you using custom imageDragging extension ? If yes than @gpbmike solution will work for you.

You should also checkout following cases:

       4 Cases for imageDragging + fileDragging extensons:
        
         1. ImageDragging ON + No Custom Image Dragging Extension:
            * Use fileDragging extension (default options)
         2. ImageDragging OFF + No Custom Image Dragging Extension:
            * Use fileDragging extension w/ images turned off
         3. ImageDragging ON + Custom Image Dragging Extension:
            * Don't use fileDragging (could interfere with custom image dragging extension)
         4. ImageDragging OFF + Custom Image Dragging:
            * Don't use fileDragging (could interfere with custom image dragging extension)

source: https://github.com/yabwe/medium-editor/blob/df8bde11dcbb48d9e394c3affb9524aaa4c9be49/src/js/core.js#L405-L414

**Comment by nmielnik** [comment]
Apologies for this being very confusing, but so is this concept of allowing custom file dragging extensions in a good way, while not breaking people who are depending on the deprecated image-dragging extension!

If I can remember correctly after re-reading the code, we still support a custom option for enabling/disabling drag & drop of images (the deprecated `imageDragging` option).  The new file-dragging extension allows you to override the default behavior (only allowing images to be drag & dropped in) and allow anything, nothing, or specific file types to be drag & dropped into medium-editor.

So, if you wanted to do some custom drag & drop behavior, I would recommend doing what @gpbmike suggested, and passing your own custom extension to handle this.  You can build off of the existing file-dragging extension by extending it before you pass it in, and overriding some of [these parts](https://github.com/yabwe/medium-editor/blob/master/src/js/extensions/file-dragging.js#L20-L60) which are what handling preventing drag & drop.

```js
var YourFileDraggingExtension = MediumEditor.extensions.fileDragging.extend({
   // override the things you want to change
});

new MediumEditor(editorNode, {
    extensions: {
        'imageDragging': new YourCustomExtension(),
    }
});
```

**Comment by cblavier** [comment]
Thanks for your help!
Fixed my problem by providing an empty imageDragging extension

```javascript
new MediumEditor(editorNode, {
    extensions: {
        'imageDragging': {}
    }
});
```
