### ISSUE TITLE
Paste options not working on master

### ISSUE THREAD

**Issue by brazorf** [yabwe/medium-editor#881]
Code
```javascript
new MediumEditor(".editor", {
	buttons: ['italic', 'bold', 'underline', 'anchor', 'unorderedlist', 'quote'],
	paste: {
		// This example includes the default options for paste, if nothing is passed this is what it used
		forcePlainText: false,
		cleanPastedHtml: true,
		cleanReplacements: [],
		cleanAttrs: ['id', 'style'],
		cleanTags: ['a', 'br']
	}
});
```

Expected behaviour
- [x] not convert into plain text
- [x] remove id, style attributes
- [x] remove a, br tags

Only the first one seems to behave properly.

Check this [plunker here](http://plnkr.co/edit/7YjurUuOr2hExUQuNltq?p=preview)
I didn't find any cdn so i used the latest minified on master.

**Comment by nmielnik** [comment]
You can find the latest CDN [here](https://github.com/yabwe/medium-editor#installation) in the README.md

**Comment by brazorf** [comment]
Ok i have updated the plunker with latest version from cdn, issue remains though.

**Comment by nmielnik** [comment]
@brazorf so I found the issue!

It's just a capitalization issue with the `cleanPatedHTML` option that's being passed in in your plunker:

You're passing `cleanPastedHtml` but the option is actually `cleanPastedHTML`.  Pretty easy mistake to make, I had to actually debug the code to even figure out that was the problem.

When I fixed that, everything seemed to work as expected, can you give it a shot?

**Comment by brazorf** [comment]
Ive tried with plunkr and the uppercase cleanPastedHTML everything seems to work now! 
Can't figure out how ive mispelled that, since ive copy/pasted from the docs.

Thank you!

**Comment by nmielnik** [comment]
Awesome, no problem.  Totally understandable.
