### ISSUE TITLE
Placeholder is overlapping the text.

### ISSUE THREAD

**Issue by fre2ak** [yabwe/medium-editor#883]
Hello,

I've stumbled upon a case where when you have a placeholder set up as an option and you also have text, the placeholder is overlapping the content until you click/focus on it.

![screen shot 2015-11-19 at 10 52 26 am](https://cloud.githubusercontent.com/assets/1614618/11266276/17d6efc8-8eac-11e5-9df9-4b03bb9279ef.png)

P.S: I'm using it with React wrapper, but I believe there isn't much difference.

Best regards

**Comment by j0k3r** [comment]
Hello,
Could you provide a jsfiddle to reproduce the bug?
Thanks

**Comment by fre2ak** [comment]
Hello,

Actually I cannot reproduce it in jsfiddle using pure JS without React, so maybe the error comes from the React wrapper that I'm using. Thank you anyway and sorry for the disturbance.

Best regards

**Comment by nmielnik** [comment]
No problem, if you find anything that could be helpful for others using react please update the issue. Thanks!

**Comment by fre2ak** [comment]
Hello again,

Actually I realised what's happening and here it is: http://jsfiddle.net/fretwoak/fwn9bjt9/
Because of the asynchronous DOM loading of React (and a few state updates afterwards) the content is loaded after the editor is instantiated and then this happens.

Best regards
