### ISSUE TITLE
Cannot press space when i'm with the cursor at the end of line

### ISSUE THREAD

**Issue by patrinhani-ciandt** [yabwe/medium-editor#886]
I think that is a bug added on release 5.10.0. Now i'm not be able to add a space when the cursor is on the end of line. This bug was added by this condition: 

if ((textContent[caretPositions.left - 1] === undefined) || (textContent[caretPositions.left - 1] === ' ') || (textContent[caretPositions.left] === undefined)) ...

on the function 'function handleDisableExtraSpaces(event)'

**Comment by j0k3r** [comment]
This functionality should be disabled by default (see https://github.com/yabwe/medium-editor/pull/855).
Could you provide a jsfiddle with your configuration so we can check that?

**Comment by patrinhani-ciandt** [comment]
I've enable the option o avoid extra spaces 'disableExtraSpaces: true', but the problem is that i cannot add any space ad the end of a sentence even if i didn't add any space before.

**Comment by j0k3r** [comment]
Hum right, I think this option should allow at least one space at the end a sentence. Otherwise you can't properly write something :confused:

**Comment by patrinhani-ciandt** [comment]
I've discovered the problem .. i'm pushing a PR for this bug !!!

**Comment by patrinhani-ciandt** [comment]
@j0k3r There is my PR .. please check if this solve the problem .. Worked here on my local tests
