### ISSUE TITLE
cleanReplacements option ignores <code> tag

### ISSUE THREAD

**Issue by hraynaud** [yabwe/medium-editor#888]
First off thanks for the excellent work on this plugin.  I'm overdue on contributing to open source and this is a project I hope to contribute to in the very near future.

I'm having a minor issue with the paste functionality. Instead of forcing plain text, I'm allowing users to paste a limited set of HTML using the following configuration:

     paste: {
            forcePlainText: false,
            cleanPastedHTML: true,
            cleanReplacements: [
              [new RegExp(/<div>/gi), '<p>'],
              [new RegExp(/<\/div>/gi), '</p>'],
              [new RegExp(/<strong>/gi), '<b>'],
              [new RegExp(/<\/strong>/gi), '</b>'],
              [new RegExp(/<font>/gi), ""],
              [new RegExp(/<\/font>/gi), ""],
              [new RegExp(/<code>/gi), '<pre>'],
              [new RegExp(/<\/code>/gi), '</pre>'],

            ],
            cleanAttrs: ['class', 'style', 'dir', 'color', 'face', 'size', 'align', "border"],
            cleanTags: ['meta', 'style', 'script', 'center', 'basefont', "frame", "iframe", "frameset" ]
          },

All of the other cleanReplacements work except for the one for the  **code** tag. It just ignores that part of the configuration.  However, add **code** to the cleanTags works as expected. Unfortunately, I lose the text inside the tag if I go that route.

Here is a link to a random stackexchange issue with some SQL code embedded in the question.  I extracted to the first few lines of content inside the code block and pasted here just for your reference.

http://dba.stackexchange.com/questions/121869/sql-server-uniqueidentifier-storage
    
    declare @guid_to_binary table
    (
        [id] int identity(1,1),
        [guid] uniqueidentifier,
        [binary_conversion] binary(16)
    );
    ....

Please let me know if I'm doing anything wrong. Thanks for your help.

**Comment by hraynaud** [comment]
hmm?  It seems like it's not just the **code** tag but other tags such as h1,h2 etc.  Any thoughts?

Thanks

**Comment by j0k3r** [comment]
For `code` tag, I use :

```js
[new RegExp(/<(em|code)/gi), '<i'],
[new RegExp(/<\/(em|code)>/gi), '</i>'],
```

Could you give a try?

About h1, h2, etc . I don't see a rule to remove them in your `cleanReplacements`.

**Comment by hraynaud** [comment]
@j0k3r thanks for the quick response.  I decided to just remove the code tag altogether since it's unlikely that my users will ever by copying and pasting code. However, they are likely to copy text with headers.

So it looks like the regex pattern you specified (without the closing **'>'**) works.

I don't mean to turn this into a regex lesson but why is the closing **'>'** fine the second regex but not the first?

    [new RegExp(/<h[1-6]/gi), '<p'],
    [new RegExp(/<\/h[1-6]>/gi), '</p>'],

**Comment by j0k3r** [comment]
Well, I've no idea. When I tested few regex to replace some tag I faced the same issue you got. I don't know why if we provide the `>` the regex doesn't work anymore.
At least, it solves your issue :wink:

**Comment by nmielnik** [comment]
@j0k3r @hraynaud the reason we wouldn't have the closing `>` tag is because a lot of these elements may have attributes that we may want to preserve (ie `<code id="some-id" style="...">`).
