### ISSUE TITLE
delay option breaks hidetoolbar()

### ISSUE THREAD

**Issue by nkalush** [yabwe/medium-editor#889]
The `delay` option causes the toolbar to pop back in when it is hidden with the hidetoolbar function in a custom extension.

Here is a jsfiddle that I was using:
https://jsfiddle.net/7nynqfo6/
(sorry for all of the possibly extra code, I was debugging my extension)

**Comment by nmielnik** [comment]
@nkalush are you sure this is the right jsfiddle?  It doesn't seem to be related to what you're describing in this issue...
