### ISSUE TITLE
using custom icons

### ISSUE THREAD

**Issue by nkalush** [yabwe/medium-editor#890]
I used to be able to use custom icons for the built in stuff via the buttonlabels option, but that no longer seems to work. Is there a new way to replace the button contents? Here's what I was doing to make it obvious what I'm asking about:

```js
    editor = new MediumEditor('.editable_region', {
        toolbar: {
            buttons: ['bold', 'italic', 'quote', 'h2', 'h3', 'unorderedlist', 'orderedlist']
        },
        buttonLabels: {
            'bold': '<i class="icon-bold"></i>',
            'italic': '<i class="icon-italic"></i>',
            'quote': '<i class="icon-quote"></i>',
            'unorderedlist': '<i class="icon-list-bullet"></i>',
            'orderedlist': '<i class="icon-list-numbered"></i>'
        }
    });
```

**Comment by nmielnik** [comment]
Now custom button labels are passed in as part of the list of buttons in the `toolbar.buttons` option, I believe this changed as part of 5.0.0.  Can you try this to see if it works?  

```js
    editor = new MediumEditor('.editable_region', {
        toolbar: {
            buttons: [{
                    name: 'bold',
                    contentDefault: '<i class="icon-bold"></i>'
                }, { 
                    name: 'italic',
                    contentDefault: '<i class="icon-italic"></i>'
                }, {
                    name: 'quote',
                    contentDefault: '<i class="icon-quote"></i>', 
                }, 'h2', 'h3',  {
                    name: 'unorderedlist',
                    contentDefault: '<i class="icon-list-bullet"></i>'
                }, {
                    name: 'orderedlist',
                    contentDefault: '<i class="icon-list-numbered"></i>'
                }
            ]
        }
    });
```

The things you can override on buttons via this method is outlined [here](https://github.com/yabwe/medium-editor#button-options) in the README.md.

You should be able to pass either just a string (ie `'h1'`, `'h2'`) or an object containing a name and overrides for the specific button (ie `{ name: `bold', contentDefault: '<i class="icon-bold"></i>' }`)
