### ISSUE TITLE
"child.querySelectorAll is not a function" when using autoLink in ember

### ISSUE THREAD

**Issue by whatthewhat** [yabwe/medium-editor#897]
Hey, first of all this is a very nice editor! :+1:

There is an error `child.querySelectorAll is not a function` when trying to use `autoLink` in ember.
The problem is somewhat specific to how ember currently works, but I think it's unlikely that this will change upstream any time soon, so I wonder if you're open for a small workaround in medium-editor?

**The problem**
Ember adds empty comments to the DOM to aid it's binding system. I think (could not find the reference right now) that due to a workaround for some browser bug this element is a little weird: it has nodeType 8 (text), but nodeName "#comment" (see screenshot below).

This basically means that a check [like this one](https://github.com/yabwe/medium-editor/blob/3aceea19919d6ac698fd9e53dd747b8de18dd379/src/js/util.js#L251) will return false and we get the error above.

The solution would be to add another check in these places: `element.nodeType === 3 || element.nodeName === '#comment'`.

Is this something you would accept a PR for (not sure how applicable this is outside of ember)?

Tested with ember 1.13 and 2.2.0 and medium-editor 5.10.0.

![](https://s3.amazonaws.com/f.cl.ly/items/0R1u3I1p1b0O3w2i0l0N/Image%202015-12-03%20at%2012.45.43%20AM.png)

**Comment by j0k3r** [comment]
Interesting.
There are multiple places where we use `element.nodeType === 3`, should we add this check on `#comment` everywhere? :confused:

**Comment by whatthewhat** [comment]
@j0k3r I'll do more testing, but at least 2 places were causing the error

**Comment by whatthewhat** [comment]
@j0k3r I submitted a failing spec with n empty comment.. the thing is that adding the  `element.nodeName === '#comment'`does not make the test pass, unfortunately :) (while it does fix the ember issue I'm having).

If do a debug output inside the `splitByBlockElements` during the test run the `child` is `[object Comment]` when the spec fails.

Any ideas? (I'm probably missing something + my knowledge of DOM elements is pretty limited)

**Comment by nmielnik** [comment]
@whatthewhat in the specific case of `splitByBlockElements()`, you'd want to add a special case to just filter out any elements that aren't text nodes or elements.  So something like this:

```js
splitByBlockElements: function (element) {
            var toRet = [],
                blockElementQuery = MediumEditor.util.blockContainerElementNames.join(',');

            if (element.nodeType !== 3 && element.dodeType !== 1)  {
                return toRet;
            }

            // ... rest of function
}
```

The goal of this function is to find all block elements that could have content within them that we'd want to auto-link.  We split everything so we can make sure we don't try to create links that span multiple block elements.  In this case, we just want to ignore any comments, cuz we'd obviously not want to create a link out of them :smile:

**Comment by whatthewhat** [comment]
@nmielnik thanks! I actually had my `nodeType` numbers mixed up, that's why the original confusion :smile: 

Updated the PR: https://github.com/yabwe/medium-editor/pull/900
