### ISSUE TITLE
Placeholder is overlapping the text when using the editor with React.js

### ISSUE THREAD

**Issue by fre2ak** [yabwe/medium-editor#905]
Hello,

I've stumbled upon a case where when you have a placeholder set up as an option and you also have text, the placeholder is overlapping the content until you click/focus on it.

![screen shot 2015-11-19 at 10 52 26 am](https://cloud.githubusercontent.com/assets/1614618/11266276/17d6efc8-8eac-11e5-9df9-4b03bb9279ef.png)

Here is the reproduced issue: http://jsfiddle.net/fretwoak/fwn9bjt9/

Because of the asynchronous DOM loading of React (and a few state updates afterwards) the content is loaded after the editor is instantiated and then this happens.

Best regards

**Comment by daviferreira** [comment]
You should use `ediotr.setContent`instead:

http://jsfiddle.net/ex95Lpr6/

**Comment by fre2ak** [comment]
Thank you @daviferreira ! It works now. I've been searching for this method for such a long time. :)
