### ISSUE TITLE
Troubles with toolbar in bootstrap modal after after fix on version 4.5.2

### ISSUE THREAD

**Issue by buga1234** [yabwe/medium-editor#911]
Hi, guys.

I have multiple editors in different bootstrap modals. 

For example I have div which has the same class name ".editable-content" in 3 different bootstrap modals. So in version 4.5.1 everything is ok. It's working. But after [fix](https://github.com/yabwe/medium-editor/blob/master/CHANGES.md#452--2015-04-14) in version 4.5.2 toolbar doesn't work anymore.

Why it happend?

Many thanks

**Comment by j0k3r** [comment]
Wow 4.5.2 is a pretty old release.
Did you have any chance to check with the latest 4.12.x release?

**Comment by buga1234** [comment]
I've checked all newer releases, 4.5.1 is ok, problem exist after fix in 4.5.2 in all of those

**Comment by nmielnik** [comment]
@buga1234 are these bootstrap modals involving iframes?  If they are, can you pass a reference to the correct `document` object via the [`ownerDocument` option](https://github.com/yabwe/medium-editor/blob/master/OPTIONS.md#ownerdocument) when you instantiate MediumEditor?

The toolbar attempts to detect mousedown on the `<body>` tag, but it might be looking at the wrong `<body>` element if the editor is inside an iframe...

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
