### ISSUE TITLE
A way to add a custom class to each block element when created

### ISSUE THREAD

**Issue by MarkNijhof** [yabwe/medium-editor#914]
Hi,

I realise this is most likely not functionality that you want in the code, but for the project I am working on I need to be able to track individual blocks that the editor creates, so I was wondering if I could automatically add f.ex. a class attribute to a P element once it is created and the same when they are converted into f.ex. H1? So this would mean that two sequential P tags would both have a different class name.

Would this be possible with an extention so I don't have to change the source and thus can keep upgrading to new versions of the medium editor?

Cheers,

-Mark

**Comment by nmielnik** [comment]
So, there should be ways to accomplish what you want here.  Regardless of how you implement it though, you definitely can use an extension to implement it!

As a starting point, I would just try attaching to the `editableInput` custom event, and each time it fires scan for all block elements and make sure they have a class name.  We have a selector you can use if you want to look for block elements using [`MediumEditor.util.blockContainerElementNames`](https://github.com/yabwe/medium-editor/blob/master/src/js/util.js#L105-L113).

One thing to look out for is how the browser treats these block elements once they have a class name on them.  It might just ignore it, but it also might never remove the element.  For instance, for the example you listed above where it would convert a `<p>` into a `<h1>`, if the `<p>` had a class name on it, I'm not sure what the browser will we call `document.execCommand('formatBlock', null, 'h1')`...

Good luck, and let us know how it goes!

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
