### ISSUE TITLE
Color option for placeholder text

### ISSUE THREAD

**Issue by anilmaurya** [yabwe/medium-editor#915]
Placeholder options https://github.com/yabwe/medium-editor#placeholder-options accept `text` argument only.

Text color is white by default, my editor does not have background color therefore I didn't saw placeholder working until I inspected editor css and saw that placeholder color is white  and removed color property.

Now I have overwritten `.medium-editor-placeholder:after` in my custom css, I think adding textColor option for placeholder text will be good.

**Comment by ChangJoo-Park** [comment]
:+1:

**Comment by rishijain** [comment]
@anilmaurya I think the best way to handle this is through what you have suggested by writing custom css. For something like this it is probably for the best not to mix `js` & `css` by introducing an option to handle this.

**Comment by nmielnik** [comment]
I think I agree with @rishijain on this one

**Comment by anilmaurya** [comment]
@rishijain If that's the case, would you mind adding a note in `Placeholder Options` docs for changing placeholder text color.

**Comment by Ayesh** [comment]
The placeholder is nothing more than an `:after` item, so you can theme as exactly as you want. 

```
.medium-editor-placeholder::after {
  color: red;
}
```

Ideally, you will need to inherit the color (of the element itself), and may be set opacity.
