### ISSUE TITLE
Links are not openable.

### ISSUE THREAD

**Issue by mgilson** [yabwe/medium-editor#918]
When I click a link (e.g. at https://yabwe.github.io/medium-editor/demo.html), the link doesn't open.  Clicking on the hover bubble doesn't open the link either.  In fact, there doesn't seem to be any way to click the link without right-click --> `Open Link in ...` which doesn't seem to be the intent (after all, there's an option to open the link in a new tab which probably wouldn't exist if the expectation was for users to right click where they can choose how to open the link).

**Comment by mgilson** [comment]
FWIW, I've asked about this on StackOverflow as well.  Here's the post:

http://stackoverflow.com/questions/34164196/how-to-use-links-in-medium-editor

**Comment by rishijain** [comment]
Trying this on Medium, this is the behaviour:
1. Upon hovering on the word with the link, the address does come up in tooltip and the link is clickable from there(this is where we are not doing the same, but yes, now there is no way to open the link). 
2. But now there is no way to edit the address. I have to select the word again, unlink it and then link it again with new address.

But I am wondering, when a viewer will see the post that you have written, I am guessing that he will see it in non-editable mode(i.e medium editor disabled) and the link would be clickable then(here also the option to open the links in new tab would come into play).

What do you think?

**Comment by j0k3r** [comment]
Well, link **are** openable. They are just not the way you want.

When the anchor extension was created there were no option to open the link at all. Now the preview display a real link and you can right + click or <kbd>ctrl</kbd> + click to open the link in a new tab. And when you click on the link we choose the option to add ability to edit the link. This is something you can't do on medium.com.

We can eventually add an option so you can choose if you want to edit the link when you click on the preview or edit it.

**Comment by mgilson** [comment]
I see.  I think there might be a fundamental misunderstanding of the way the medium editor is meant to be used on my part.

The way that I'm beginning to understand this is that the there are 2 modes of operation.  There's edit mode and publish mode.  For publish mode, I suppose I'm just not supposed to use the editor at all:

```javascript
if (editMode) {
    new MediumEditor('.editable');
} else {
  // publish mode.  Don't use MediumEditor
}
```

Is that correct?  Here, in publish mode, the link would behave normally, but in edit mode, you've chosen to make the links easier to edit.  If this is the intended use, I can see why you've chosen to make the links behave the way they do.  Somehow I was missing this as the intent before now . . .

There is another class of applications requiring editable elements where the distinction between edit and publish is a bit more blurry (which is the type of application that I'm building so my opinions in this regard are definitely going to be biased).  Consider editors like google docs -- The content is always editable (by the appropriate people), but it is also meant to be consumed in it's editable form.  For these cases, I like the way google docs handles links.  When you hover the link, you're given a popup that has 2 choices -- one for editing, one for following.  I think that would be a great option to add to the anchor extension.

**Comment by j0k3r** [comment]
Oh I see, you're right. Medium should be used only in edit mode.

Also, there is a "read only" feature on Google Doc (if you see [this doc](https://docs.google.com/document/d/16pJzHGC5tX3H3Ej-VDgaq-hgKeF7cHUDAR2gJAmTFhs/edit) while not being logged in).

About the two options when overriding a link, that's a good suggestion but I think we want to keep MediumEditor simple in a way that the less option we have, the less complex the editor is. But we'll discuss your suggestion :)

**Comment by nmielnik** [comment]
After thinking about it, I think we'd want to keep the current anchor-preview as-is, but I think making an anchor-preview tooltip that would have options for navigating, editing, and deleting would make a good external extension.  We could call out this extension and reference it in our documentation if anyone were to make it.

**Comment by mgilson** [comment]
I've created a plugin that seems to work.  It's still WIP (particularly because I haven't done any work on making it look good) -- https://github.com/PatternAI/MediumTools, but it seems to work and is relatively simple.

Any thoughts you guys have on whether the implementation is complete garbage is also welcome :-).

Cheers.

**Comment by nmielnik** [comment]
@mgilson this is awesome man, the implementation is clean and very readable (and _very_ far from garbage :wink:) great work dude!

If you don't mind, could you add your extension into the list of plugins/extensions in [Extensions Plugins Wiki Page](https://github.com/yabwe/medium-editor/wiki/Extensions-Plugins) and the [Examples of custom built external extensions](https://github.com/yabwe/medium-editor/blob/master/src/js/extensions/README.md#examples-of-custom-built-external-extensions) in `src/js/extensions/README.md`?

We can then add your extension into the [Extensions](https://yabwe.github.io/medium-editor/#extensions) part of the landing page...OR you can always open a PR against the `gh-pages` branch of the main medium-editor repo.  That's the branch that gets auto-deployed as our landing page.  You just need to add yourself into [`extensions.jade`](https://github.com/yabwe/medium-editor/blob/gh-pages/sections/extensions.jade).

Thanks again sir, you should probably add a link to this into your [stackoverflow issue](http://stackoverflow.com/questions/34164196/how-to-use-links-in-medium-editor) as well :smile:

I know it seems like a lot, but the more people that stumble upon your extension the better!
