### ISSUE TITLE
disableExtraSpaces option not working

### ISSUE THREAD

**Issue by ferdiemmen** [yabwe/medium-editor#922]
Adding a space to the end of the line of article.title adds a '\&nbsp;' although disableExtraSpaces is set to true.

```
<h3 medium-editor
       bind-options="{disableReturn: true, forcePlainText: true, disableExtraSpaces: true, toolbar: false}"
       ng-model="article.title"
       data-placeholder="Add title">
</h3>
```

medium-editor version: 5.12.0
angular-medium-editor version: 1.1.0

**Comment by rishijain** [comment]
Hi @ferdiemmen , can you provide a jsfiddle to play around?

**Comment by rishijain** [comment]
BTW, one space at the end of the line is allowed. See https://github.com/yabwe/medium-editor/issues/886

**Comment by ferdiemmen** [comment]
Yes, it should be allowed but not give back a &nbsp; to the actual value of the ng-model right? I shall provide a jsfiddle or plunkr.

**Comment by ferdiemmen** [comment]
https://jsfiddle.net/GlitchFF/vkudx9co/1/

**Comment by rishijain** [comment]
ah, I see. I am not entirely sure why it does what it does. But I don't think it has something to do with medium-editor. I tried the same thing on an angular app which does not use any editor. It also adds a ```&nbsp``` upon adding a space at end of line. But lets keep it open until we get a concrete answer.

**Comment by j0k3r** [comment]
On which browser are you testing guys?

**Comment by rishijain** [comment]
I tried it on safari 8.0 and chrome 47.0

**Comment by ferdiemmen** [comment]
I tried it on Chrome Canary 49.0.2612.0 and Chrome Version 47.0.2526.106 (64-bit)

**Comment by ferdiemmen** [comment]
It could be the way angularjs handles contenteditable.

**Comment by rishijain** [comment]
Dug a little deeper and found out this:

In `angular-medium-editor` under the directive, ng-model $setViewValue has been over riden by `ngModel.$setViewValue(editable.innerHTML.trim());`

This is probably the reason why it shows `&nbsp;` instead of a space. 
@ferdiemmen You can try by removing the `angular-medium-editor` in the fiddle and changing the `h3` to `input` field. and then try to add a space at end and it renders just fine.

**Comment by ferdiemmen** [comment]
Perfect! Thank you for the explanation. I will put this issue up with the angular-medium-edtior team.
