### ISSUE TITLE
Toolbars, and Anchor Previews

### ISSUE THREAD

**Issue by oyeanuj** [yabwe/medium-editor#923]
Hi folks! Thank you for your work on this library, it has been super helpful. I am using the React wrapper to the Editor and had a couple of questions about how to move forward with specific cases. 

Any tips, or pointers would be much appreciated. Apologies if they are very basic n00b questions but I tried to go through all the docs before asking :)

1. **Two fixed toolbars instead of one air toolbar**: For my use-case, I am looking to divide the options available on the toolbar into two separate fixed toolbars, each with a few buttons. My question is 
  * if the current toolbar supports it or should I instead build my two own custom extensions which replicate and replace the default toolbar but with the options I need. If I do that, would that work or is that frowned upon?

2. **Using buttons that don't depend on selection**: I am trying to add buttons which insert video, etc. My current thinking is that I need to use a custom button, attached to the toolbar to do that, and that it modifies the internal HTML with the correct tag. Is that correct? 
*(It seems that all the button implementations today depend on a selection from the editor, and performs an operation on that selection. I assume if the toolbar was visible, I could still use some of the buttons. In other words, can operations only be done on selected text from the editor?)*

3. **Anchor Preview in the Editor**: I am hoping to show Anchor previews in the Editor rather than the toolbar. Is the right way to do is build an extension like Anchor Preview and instead of inserting the preview in the tooltip, show it like the insert-embed plugin does by modifying the innerHTML?

4. **Extensions and React**: Can extension's innerHTML be React components or can the extensions themselves be React components? Not sure if this is relevant to this repository or to the react-medium-editor repository but figured I could just add it here. 

Thanks again, and apologies if it is a long list of questions!

**Comment by oyeanuj** [comment]
One more question to add to this: 

I am using the sticky version of the toolbar. I am wondering how can I make multiple instances of `medium-editor` on the page share the same toolbar (without replicating the markup for the toolbar or creating a new instance)?

**Comment by oyeanuj** [comment]
(_edited above to remove questions I figured out the answers for_)

One more question to add to this: 

I am using the sticky version of the toolbar. I am wondering how can I make multiple instances of `medium-editor` on the page share the same toolbar (without replicating the markup for the toolbar or creating a new instance)?

@daviferreira @nmielnik any thoughts or direction on the questions above would be really helpful! Thanks for all of your work on this library!

**Comment by oyeanuj** [comment]
(_edited above to remove questions on toolbar that I figured out the answers for_)

But one more question to add to this: 

I am using the sticky version of the toolbar. I am wondering how can I make multiple instances of `medium-editor` on the page share the same toolbar (without replicating the markup for the toolbar or creating a new instance)?

@daviferreira @nmielnik @j0k3r Any thoughts or direction on the questions above (in this comment and previous) would be really helpful! 

Thanks for all of your work on this library!

**Comment by nmielnik** [comment]
> if the current toolbar supports it or should I instead build my two own custom extensions which replicate and replace the default toolbar but with the options I need. If I do that, would that work or is that frowned upon?

The current toolbar does support a 'fixed' mode (the `toolbar.static` option).  If I were trying to have 2 different toolbar elements like what you're talking about, I would first try to pick the 1 toolbar that you want that behaves the most like the existing medium-editor toolbar.  You can try fiddling with it to get it working the way you wanted it with the buttons/options that you want.  If you're able to get that portion working, then there are 2 things you could try to get the 2nd toolbar working:

1. Modifying the current toolbar extension to support 2 different toolbars.  You can work through the main hooks for showing/hiding/positioning the toolbar, and see if it's possible to maintain 2 separate elements in a simple way.

2. Creating an additional extension which will act as the 2nd toolbar.  You could start by just copy and pasting the toolbar code into another extension, creating an instance, and passing it into the editor to see how it all works.

There might be other ways, but these 2 come to mind as good starting points

> (It seems that all the button implementations today depend on a selection from the editor, and performs an operation on that selection. I assume if the toolbar was visible, I could still use some of the buttons. In other words, can operations only be done on selected text from the editor?)

If you're using the `toolbar.static` option, you can also enable the [`toolbar.updateOnEmptySelection`](https://github.com/yabwe/medium-editor/blob/master/OPTIONS.md#updateonemptyselection) option.  This will make the toolbar appear whenever focus is inside the editor (even if there's no selection).

The caveat is that the toolbar will be positioned statically, the `updateOnEmptySelection` option won't work without the `toolbar.static` option.

Assuming you're ok with that, you'll be able to have buttons that can inject elements into the editor even when the selection is empty.  How the browser handles things like 'bold', 'italic', etc. when the selection is empty is not super clear, it'd be worth seeing what happens though.  Other block styling actions like 'h1', 'h2', 'pre', 'blockquote', etc. will work as you would expect them to (changing the styling of the block element the cursor is within)

>  I am hoping to show Anchor previews in the Editor rather than the toolbar. Is the right way to do is build an extension like Anchor Preview and instead of inserting the preview in the tooltip, show it like the insert-embed plugin does by modifying the innerHTML?

If you want to show any kind of customized anchor-preview extension, I would definitely start by modifying the existing extension in the way that you want and see if you can get the behavior you want without having to write everything from scratch:

```js
var MyAnchorPreview = MediumEditor.extensions.anchorPreview.extend({
	// Your custom overrides here
});

var editor = new MediumEditor('.editable', {
	extensions: {
		'anchor-preview': new MyAnchorPreview()
	}
})
```

You should be able to change the way the preview is rendered and not use a tooltip.

> Can extension's innerHTML be React components or can the extensions themselves be React components? Not sure if this is relevant to this repository or to the react-medium-editor repository but figured I could just add it here.

Extensions can be any type of component you want, they just need to implement some of the core api-contract methods/properties that are required of extensions passed into the editor.  Most extensions will just be hooking into different events that are triggered on the editor and then rendering something or updating the content somehow, and the ways you do that can really be using any javascript framework you want.

> I am using the sticky version of the toolbar. I am wondering how can I make multiple instances of medium-editor on the page share the same toolbar (without replicating the markup for the toolbar or creating a new instance)?

You can't have multiple instances share the same toolbar.  You _CAN_ make once instance of medium-editor monitor multiple elements however, by passing either a selector or an array of elements when creating the instance:

```js
// Using an array
var elements = [/* array of elements */];
var editor = new MediumEditor(elements);

// Using a selector
var editor = new MediumEditor('.editable, .editor');
```

Hope that helps, apologies for taking so long to get back to you, you asked a bunch of good questions!

**Comment by oyeanuj** [comment]
@nmielnik Thank you for the detailed, patient response. And sorry about the grouping of questions together. I was trying to not spam the issues list, but I totally see your point about smaller specific questions. Will do so next time :)

I am going to go try a few things and come back with more questions I am sure!
