### ISSUE TITLE
alt for <img>

### ISSUE THREAD

**Issue by psd-html** [yabwe/medium-editor#926]
Hello,
no alt for `<img>`

thx

**Comment by nmielnik** [comment]
@psd-html could you be more specific about what you're seeing and what you would expect?  Perhaps what the actual step-by-step flow is?

**Comment by psd-html** [comment]
When I use the icon <img>  with the image link is missing in my HTML code the alt

<img src="link.png"> not <img src="link.png" alt="text"> 

Thank you

**Comment by j0k3r** [comment]
You mean when you drop an image inside the editor and it is then converted as an image. This won't be fixed in MediumEditor since the support of image is really (really) basic. There is no huge management.
For that, you can check this plugin: https://github.com/orthes/medium-editor-insert-plugin
