### ISSUE TITLE
Modifying DOM through editableInput doesn't update the textarea. Is this intended? Is there a trigger to update the textarea?

### ISSUE THREAD

**Issue by Charlex** [yabwe/medium-editor#928]

**Comment by nmielnik** [comment]
If you're modifying the html content and want to be sure the textarea is updated as well as the `editableInput` event is fired, try using [`editor.setContent()`](https://github.com/yabwe/medium-editor/blob/master/API.md#setcontenthtml-index)

**Comment by Charlex** [comment]
Alright so I can't make direct modifications to the editable's DOM and rely on the events to trigger. 

I have to use a string and pass it in using editor.setContent() first. Gotcha.

**Comment by nmielnik** [comment]
Yeah, outside of polling (using some interval) or listen for mutation events (which we've tried to avoid thus far) we're not aware of an event we can listen to that will be triggered by manual changes to the innerHTML of the editor.  Thus, we exposed that `setContent()` helper as a way to accomplish this. 

If there's a viable alternative, we would definitely like to have these changes detected automatically instead of having to call a helper method.

**Comment by Charlex** [comment]
Do the pros of using a MutationObserver outweigh the cons of increased complexity, browser support, etc?

**Comment by Charlex** [comment]
Actually more important than that question. Is there someway besides setContent to trigger that textarea update?

**Comment by Charlex** [comment]
And I'm not sure setContent is actually trigging a textarea update. 

![screen shot 2016-01-11 at 3 04 58 pm](https://cloud.githubusercontent.com/assets/1542740/12249463/c5c9ac46-b874-11e5-99bb-c696e9a36466.png)

**Comment by nmielnik** [comment]
So MutationObserver does not exist in IE < 11, and the 'input' event does not work in a `contenteditable=true` element in any version of IE.  So, we found a way to mimic the 'input' event for IE, and just listen for 'input' in all other browsers.  I don't know that we wouldn't be willing to switch over to MutationObserver, but this is the first issue I recall where there has been a problem with the current system.

If you look at the code [here](https://github.com/yabwe/medium-editor/blob/master/src/js/core.js#L358-L365) there isn't a direct way to cause the `<textarea>` to be updated (it's just listening for the `editableInput` event and then updating the `<textarea>`).  However, you can manually trigger the `editableInput` event, which would cause the textarea to be updated with the current content. So you could do something like this (but I'm not sure this is much better than explicitly calling `setContent()`):

```js
var editor = /* reference to editor */;
var element = /* reference to <div> you're setting the content of */
editor.trigger('editableInput', { target: element, currentTarget: element }, element);
```

**Comment by Charlex** [comment]
Thanks Nate for taking the time to answer my question.

**Comment by nmielnik** [comment]
No problem, were you able to get things to work the way you needed them to?

**Comment by M4urice** [comment]
I just ran into the same problem and would have expected the textarea to update as I call `setContent`.

As I use the medium editor to implement an edit function, the editor is prepopulated with the existing content (via `setContent`). If the user doesn't change the content, the old data is completely lost (since the textarea is empty).

**Comment by nmielnik** [comment]
@M4urice would you be able to try setting the content of the `#textarea_id` first before you instantiate medium-editor?

Something like:
```js
$(`#textarea_id`).val(/* pre-populated existing content */);
var editor = new MediumEditor('#textarea_id');
```

When you instantiate MediumEditor on a text area, it creates a new `<div>` and sets its innerHTML to be whatever was in the `<textarea>` to start. If you know there will be pre-populated content before you instantiate MediumEditor, I think putting that content inside the `<textarea>` first should fix the issue you're running into.  

If not, can you give more description regarding the order that you're setting up the `<textarea>`, MediumEditor, and setting the initial pre-populated content?  Perhaps a jsfiddle / codepen if it's too hard to describe in a github comment?
