### ISSUE TITLE
How to integrate medium-editor with code syntax highlighter?

### ISSUE THREAD

**Issue by nwang57** [yabwe/medium-editor#932]
Thanks all the contributors. I am a fan of medium and playing with the django medium editor wrapper. I would like to allow user to insert code snippets and do some syntax highlight. I know it might be a minor use case but I will really appreciate if someone can give me some hints on how to make it work.

My thought would be that one can insert a code block where user type their "hello world" programs. When user clicks "save snippet", medium-editor will leave these code blocks styled by syntax highlighter like markdown2 with pygments or something. 

Thanks in advance.

**Comment by nmielnik** [comment]
So there is currently built in support for `<pre>` tags, which could be a good starting point for adding code snippets.  You can see how it work by default by adding it to the list of buttons available in the toolbar.  You could also customize the icon or text in the button for the `<pre>` tag:

```js
// enable the 'pre' button
var editor = new MediumEditor('.editor', {
    toolbar: {
        buttons: ['bold', 'italic', 'underline', 'h1', 'h2', 'pre']
    }
});

// enable the 'pre' button with custom content
var editor = new MediumEditor('.editor', {
    toolbar: {
        buttons: ['bold', 'italic', 'underline', 'h1', 'h2', {
            name: 'pre',
            contentDefault: 'code snippet', // default text
            contentFA: '<i class="fa fa-code"></i>' // custom icon if you're using font-awesome icons
        }]
    }
});
```

If you want to enable better syntax highlighting, you could:
1) Attach to the `editableInput` event, and each time the text changes, check for any `<pre>` tags and do whatever logic you need to enable the syntax highlighting
2) Make your own custom button for this by extending the default button and just changing the operation that happens to the button is clicked or 'unclicked'.  You can find a tutorial on creating a button [here](https://github.com/yabwe/medium-editor/blob/master/src/js/extensions/WALKTHROUGH-BUTTON.md).

**Comment by ahmadalukah** [comment]
Hello @nmielnik , Thank you for this tutorial , This button will add a code wrapped by <pre></pre>.
is there a way to make it wrapped by <pre><code></code></pre> ?
because the most popular highlighting libraries are using this tag to detect languages and highlight them.

**Comment by ahmadalukah** [comment]
I managed to get through this by adding this script to the view:
```
window.onload = function() {

            var h = document.getElementsByTagName('pre');
            // No fancy forEach
            for (var i = 0; i < h.length; i++) {
                if (h[i].classList.length === 0) {
                    h[i].classList.add("language-*");
                }
            }
        };
        $("pre").wrapInner('<code class="language-php"></code>');
```
the first code will add the class `'language-*'` to each `pre` code and the second jquery will wrap the content inside the `pre` with `<code class="language-php"></code>`

**Comment by thomMar** [comment]
|hbhzebEHF

**Comment by thomMar** [comment]
[coucou c'est moi](url)
c'était mon code

**Comment by DmitrySkripkin** [comment]
You can wrap your selection in multiple tags with https://github.com/arcs-/medium-button#syntax-highlighting.

+ There is kind a solution for "code snippet" with MediumButton plugin https://github.com/arcs-/medium-button#syntax-highlighting .

**Comment by pancodia** [comment]
Medium.com allows to use ``` to add code snippets, is it possible to add this functionality in MediumEditor?
