### ISSUE TITLE
Medium Editor Highlight Button tutorial doesn't update textarea when clicked

### ISSUE THREAD

**Issue by ewagstaff** [yabwe/medium-editor#942]
Followed the highlighter code shown in the button building example here: https://github.com/yabwe/medium-editor/blob/master/src/js/extensions/WALKTHROUGH-BUTTON.md

While the \<mark> tag does appear in the .editable div, it does not immediately appear in the invisible .editable textbox the way default buttons (bold, underline, etc) do. It appears in the textbox on the next input, but since I'm building a Backbone app, it's important for the changes to reflect right away. Is there any special trick to get extension buttons to trigger the update on click?

I've tried using .trigger() in the handleClick event of the extension, but that doesn't seem to work either.

**Comment by nmielnik** [comment]
Ah, this is an excellent point, thanks @ewagstaff!

So the code relies on the `editableInput` event to be triggered on the editor for it to update the content of the hidden `<textarea>` (I'm assuming you meant `<textarea>` and not textbox, right?).

However, this event will not actually trigger if you manually change the HTML within the editor (it relies on some user invoked `input` event, or executing some built-in contenteditable command like 'bold', 'italic', etc.).

So, a simple workaround would be to do something like what you were attempting (manually trigger the 'editableInput' event).  Using the highlighter button example, you would change this line:

```js
handleClick: function (event) {
    this.classApplier.toggleSelection();
}
```

to have this additional code:

```js
handleClick: function (event) {
    this.classApplier.toggleSelection();

    // get a reference to the active editor element for correctly triggering the event
    var activeElement = MediumEditor.selection.getSelectionElement(this.window);

    // tell medium-editor to check for changes to the html via `events.updateInput()`
    // which is the same way 'editableInput' is triggered when manually changing the editor content
    // via a call to editor.setContent()
    this.base.events.updateInput(activeElement, { target: activeElement, currentTarget: activeElement });
}
```

As I referenced in the example code, there is a helper function [`setContent()`](https://github.com/yabwe/medium-editor/blob/master/API.md#setcontenthtml-index) exposed as a way for users to manually set the html of the editor, but still have the editor respond as if the user had made changes (including updating toolbar, synchronizing content with hidden `<textarea>`, etc.).  You can see the code that makes that work [here](https://github.com/yabwe/medium-editor/blob/master/src/js/core.js#L1078-L1086), which is very similar to the example above.

Thanks again for pointing this out.  If this allows you to workaround your issue, would you be willing to open a PR to update the Highlight Button example to make sure the `editableInput` event fires correctly?

**Comment by tenshis** [comment]
This is perfect, thank you **nmielnik**!

**Comment by nmielnik** [comment]
np @tenshis !

I've opened a PR to expose a helper for triggering the `editableInput` event, and I've updated the tutorial and example button to use this helper.  Using the `.events` property of the editor is not a great idea as this could change in the future without a major release, so it would be best to use the new `checkContentChanged` helper once #1077 is merged and released.
