### ISSUE TITLE
Cursor not in right place with padding on editable element

### ISSUE THREAD

**Issue by Preau** [yabwe/medium-editor#943]
I'm using Medium editor to edit the contents of a span, but when that span has padding the cursor will appear all the way at the top of the element instead of in the right place in the text.

I have attached an image where the problem is visible
![capture](https://cloud.githubusercontent.com/assets/1175735/12555584/24fa0a68-c382-11e5-9948-3ce713a68343.JPG)

**Comment by Preau** [comment]
This seems to only happen when the contenteditable element is a span. 

Fixes itself when I change it to a div or set the display to inline-block.

**Comment by nmielnik** [comment]
Yeah, other users have run into issues when using block elements other than a `<div>` as the editable element (ie `<pre>`, `<p>`, etc.).  So it's not too surprising that things are a little wonky when using an inline element as the editable (ie `<span>`).

Was there a specific use case where you needed a `<span>` as the editable?  Perhaps there's another way to accomplish your functionality without using an inline element?

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
