### ISSUE TITLE
Unordered lists generate invalid HTML 

### ISSUE THREAD

**Issue by brazorf** [yabwe/medium-editor#945]
Try this to reproduce:

- write some text
- hit enter
- write second line
- hit enter
- write third line
- hit enter
- select second and third line
- select unordered list

The resulting html code insert the `ul` inside a `p`, which is not allowed.
[Reference] (https://www.w3.org/TR/html5/grouping-content.html#the-p-element)

This issue cause undesired browser behaviour and unpredictable elements rendering.

EDIT: i've seen that in order to reproduce this it's enough to type one single word and apply the unordered list on it.

**Comment by heathcliff** [comment]
I am also seeing this issue. Looks like a duplicate of #841, I would recommend closing this issue and regrouping on that one.

**Comment by nmielnik** [comment]
@brazorf as @heathcliff pointed out, this is a duplicate of #841 so I'll be closing this in favor of this one, could you add your repro steps to that issue?

Also, nice to see you back opening issues @brazorf!
