### ISSUE TITLE
Toolbar covers text

### ISSUE THREAD

**Issue by ConnorMcF** [yabwe/medium-editor#946]
Issue from Product Hunt
![GIF of issue](https://camo.producthunt.com/8bf21012511e5dee7f1a49b36e689286ac098394/687474703a2f2f64756d702e636f6e6e6f726d63662e636f6d2f313435333930393037322e676966)
I am using Chrome 47.0.2526.111 m on Windows 10

**Comment by nmielnik** [comment]
Thanks for finding this @ConnorMcF 

I want to link this to #944 just in case @adriendlph attempts to implement this and figure out a fix for our problem on the landing page :stuck_out_tongue_winking_eye:

**Comment by nmielnik** [comment]
Looks like the gif no longer works, and we didn't actually write a description for what the issue was, so this one is kind of lost forever...unless @ConnorMcF you can remember what the issue was here?

**Comment by ConnorMcF** [comment]
I've got no idea, link is dead.
