### ISSUE TITLE
Change without inserting paragraph tags

### ISSUE THREAD

**Issue by JasonTheAdams** [yabwe/medium-editor#958]
Greetings!

I'm new with this lib, so bare with me. It's awesome, but I'm figuring it out. :)

I want the user to be able to change the contents of an H2, but when anything is change a paragraph tag is inserted into the H2. Is it possible to have it as single-line only wherein just the immediate text is changed?

**Comment by nmielnik** [comment]
How are you initializing medium-editor and what does your HTML look like?

This may not be what you're doing, but if I was attempting what you're describing I would start with this:

```html
<div class="editor">
    <h2>Enter your text here</h2>
</div>
```

```js
var editor = new MediumEditor('.editor', {
    disableReturn: true,
    toolbar: {
        buttons: ['bold', 'italic', 'underline', ... // any other buttons that won't change the h2 to something else]
    }
});
```

I've heard people mention inconsistencies when they try to initialize medium-editor on elements that aren't `<div>`s, so in case you aren't already, first try to see if you get things working using a `<div>` that contains a `<h2>`.

**Comment by JasonTheAdams** [comment]
@nmielnik Thanks for the quick response!

Ah, I see, I was thinking about this the wrong way. It looks like the editor always prefers to reside within a div, and then the user would be changing text within the header. I was doing this:
```HTML
<h2 class="editor">My Text</h2>
```

But your solution makes perfect sense. It may be worth a  thought for the editor to be cable of being text-only within an element, but I think that misses the point of how the editor works and probably causes needless extra complexity.

Thanks again!
