### ISSUE TITLE
How do I allow selection of contenteditable=false elements?

### ISSUE THREAD

**Issue by davideanderson** [yabwe/medium-editor#960]
I am in the process of writing an extension which allows the insertion of custom elements (images, videos, embeds, etc.) within the editor.  I would like the toolbar to actually display when I select these elements, but I don't want to have to enable contenteditable for the elements themselves (ie. I want the user to specify changes to the elements via toolbar buttons like justifyLeft, justifyCenter, justifyRight, but not via typing).

However, if contenteditable is set to false for the elements, the toolbar will never display, as it makes a call to:  Selection.selectionInContentEditableFalse() which returns true in my case.

How would you recommend I either prevent that check, or override that check?
If I figure out how to completely prevent the check, what consequences will I expect (since the code is obviously there for a reason) to see with it prevented?  Obviously, if the consequences are significant, I would be back to needing a way to override the check, rather than simply disable it.

Alternatively, is there a way I can choose to display the toolbar myself, as I select the custom elements, rather than relying on the toolbar being displayed as a result of my call to 'checkSelection()'?

Thanks for any input you can provide.

**Comment by orthes** [comment]
Checking if `contenteditable` is set to `false` before displaying toolbar makes sense. But in your case you skip this by calling `editor.getExtensionByName('toolbar').showAndUpdateToolbar()` function directly. But keep in mind that the toolbar is positioned according to the current selection (https://github.com/yabwe/medium-editor/blob/5.14.1/src/js/extensions/toolbar.js#L354). So if you don't have any text selected, you'll get an error.

With this approach you'll also run into another problem: there is no way to have 2 different toolbars - one for text (with bold, italics, etc.) and one for your custom elements (probably without bold, but with justifyLeft, right, link, etc.).

But there is a solution to this: create your own toolbar extension and pass it to [`extensions`](https://github.com/yabwe/medium-editor/blob/5.14.1/OPTIONS.md#extensions) option. You can either name it `toolbar` and this way the default toolbar will be overridden by your custom one, or you can give it another name and both the default one and yours will be used.

**Comment by davideanderson** [comment]
Thanks for the response.  I am actually in the process of creating an extension that would allow different, context sensitive, toolbar buttons sets to be displayed (#797).  I'll give the showAndUpdateToolbar() a shot and see what I can get done.  Will respond here with my results.

**Comment by davideanderson** [comment]
I was unable to get `showAndUpdateToolbar()` on its own to work, due to the issue with placing the toolbar, as you indicated.  I tried a few different things, and the closest I have so far is this:

I created a click event handler which calls `this.base.selectElement()` on the clicked element.
I then made a modification to `Selection.selectionInContentEditableFalse()` to allow an override (looking for the attribute data-enable-toolbar) even if the selection is indeed inside a contenteditable="false" tag:

```
        selectionInContentEditableFalse: function (contentWindow) {
            // determine if the current selection is exclusively inside
            // a contenteditable="false", though treat the case of an
            // explicit contenteditable="true" inside a "false" as false.
            var sawtrue,
                sawfalse = this.findMatchingSelectionParent(function (el) {
                    var ce = el && el.getAttribute('contenteditable'),
						et = el && el.getAttribute('data-enable-toolbar');
                    if (ce === 'true' || et === 'true') {
                        sawtrue = true;
                    }
                    return el.nodeName !== '#text' && ce === 'false';
                }, contentWindow);

            return !sawtrue && sawfalse;
        },
```

I made that modification so that the `Toolbar.checkState()` wouldn't immediately hide the toolbar.
Then I added this code a little lower down in the `Toolbar.checkState()` function:

```
			var enableToolbar = MediumEditor.selection.findMatchingSelectionParent(function (el) {
				var et = el && el.getAttribute('data-enable-toolbar');
				return et === 'true';
			}, this.window);

            // If the updateOnEmptySelection option is true, show the toolbar
            if (enableToolbar || (this.updateOnEmptySelection && this.static)) {
				console.debug('showing toolbar');
                return this.showAndUpdateToolbar();
            }
```

Doing all 3 of those things makes it so that I can indeed show the toolbar for my custom element.  Then when I add in the extension I am writing for #797, then I am getting closer to the behavior I want.

However, this is not just extension code, but actual changes to the medium-editor itself.  I was wondering if you have any suggestions of how I might be able to do something like this in such a way that I could make a pull request that would include my modifications.  I know that my modifications don't add any value to the editor on its own, and I'm not sure using the attribute 'data-enable-toolbar' is the best way of enabling the toolbar.  Perhaps an optional configurable callback that the toolbar could make during the execution of `checkState()` might be sufficient.

Any thoughts/feedback/suggestions?

**Comment by orthes** [comment]
I would try duplicating default `Toolbar` extension and naming it something else - e.g. `CustomToolbar`. And in this `CustomToolbar` extension I would change positioning functions to position the toolbar according to a selected element (you can add some class to clicked elements) and not according to selected text.

**Comment by nmielnik** [comment]
yeah, like @orthes pointed out, the toolbar itself is an extension, so you always override via `MediumEditor.extensions.toolbar.extend()`, create a new instance of your custom toolbar, and then pass it in via the `extensions` option when instantiating MediumEditor.
