### ISSUE TITLE
Lost current section after blur and focus back.

### ISSUE THREAD

**Issue by LeiZeng** [yabwe/medium-editor#963]
When a user edit and interactive with other tools UI, and get back to continue editing, the current section is lost.

It could be great if the user can get back to the section where is the latest modified.

**Comment by nmielnik** [comment]
There are helper methods exposed that could make this fairly easy to implement externally.

You can have the editor save the user's selection and restore the saved selection at any time by calling [`.saveSelection()`](https://github.com/yabwe/medium-editor/blob/master/API.md#saveselection) and [`.restoreSelection()`](https://github.com/yabwe/medium-editor/blob/master/API.md#restoreselection).

You can also subscribe to the [`blur`](https://github.com/yabwe/medium-editor/blob/master/CUSTOM-EVENTS.md#blur) and [`focus`](https://github.com/yabwe/medium-editor/blob/master/CUSTOM-EVENTS.md#focus) events to know when the user has left and returned, and make the calls then.

So something like:
```js
var editor = new MediumEditor('.editor');

// save selection when editor is blurred
editor.subscribe('blur', function () {
    editor.saveSelection();
});
// restore selection when editor is focused
editor.subscribe('focus', function () {
    editor.restoreSelection();
});
```

If you have one instance of editor managing multiple elements, this user experience could be a bit weird (where click on one element might result in selection and focus being restored in a different element) but that could be worked through.

Is this sufficient?

**Comment by LeiZeng** [comment]
@nmielnik Thank you so much for your response.

I tried saveSelection and restoreSlection, it works very well, but only when I select some content.
Wonder if we could have a method to get back to where the cursor was after blurred.

**Comment by nmielnik** [comment]
@LeiZeng so I got a chance to actually play around with this, and I apologize for providing some code that didn't work.  Looks like the `blur` event is too late for the selection to be saved, so I modified my previous code sample to save selection on `click` instead which seems to work ok.

I played around with it a bit, and I was able to get the selection to be restored correctly (even if it's a collapsed range) by using `setTimeout` to delay restoring the range by 1 ms.  This is the code I was able to get working to (hopefully) accomplish what you were asking about:

```js
// save selection
// might be work attaching to both click and keyup, since you can change selection via keyboard too
editor.subscribe('editableClick', function () {
    editor.saveSelection();
});
        
// restore selection when editor is focused
editor.subscribe('focus', function () {
    setTimeout(editor.restoreSelection.bind(editor), 1);
});
```

Does that help?

**Comment by LeiZeng** [comment]
It totally resolve this issue. Many thanks.

**Comment by LeiZeng** [comment]
Plus, I add this in case when I add some content and trigger `blur` and `focus` again.

`medium.subscribe('editableInput', medium.saveSelection)`

**Comment by goldensunliu** [comment]
@LeiZeng 
don't forget to bind
`medium.subscribe('editableInput', medium.saveSelection.bind(this))`
