### ISSUE TITLE
Loses <p></p> tags after undoing dotted list

### ISSUE THREAD

**Issue by adeelraza** [yabwe/medium-editor#964]
I came across a small bug where if you highlight a paragraph and change it into a dotted list, and then while it's highlighted you click the dotted list icon again to undo the action, the text is no longer wrapped in `<p></p>` tags. It works fine for headings and other tools. (Update: This happens in **Firefox**, not Chrome)

Also, had a quick question: Is it possible to switch the behavior of enter and shift+enter?
```
Enter = Shift+Enter
Double Enter = Enter
```

Thanks for the great project guys!

**Comment by nmielnik** [comment]
The issue about Enter and Double Enter behavior has been brought up in a few issues (#70, #34 and #251).  It's worth reading through those, as there's been a bunch of discussion but not a whole lot of progress made I believe.

For the ordered/unordered list issue, I know there was code added to ensure that the create `<ol>`\`<ul>` element are not contained within a `<p>`, and this issue with removing the `<ol>`\`<ul>` could be related to that.

It might be worth trying to comment out [this code](https://github.com/yabwe/medium-editor/blob/master/src/js/core.js#L838-L841) and see if the issues still happens.

If the issue still persists, then this might be yet another problem where browsers are doing inconsistent things with the html within a contenteditable element.

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
