### ISSUE TITLE
Paste html does not work in Firefox (43.0.1)

### ISSUE THREAD

**Issue by daxhns** [yabwe/medium-editor#972]
In Firefox (43.0.1, windows ) when pasting html formatted text into the contenteditable div, all formatting is stripped out and only plain text is pasted, even if using paste extension, and disabling forcePlainText option.

			var comment_editor = new MediumEditor(js_element,  {
				buttonLabels: 'fontawesome',
				targetBlank: true,
				toolbar: {
					buttons: ['bold', 'italic', 'underline', 'quote', 'anchor', 'orderedlist', 'unorderedlist']
				},
				anchor: {
					linkValidation: true,
					placeholderText: 'Paste or type a link..',
				},
				paste: {
			        forcePlainText: false,
			        cleanPastedHTML: true,
			        cleanReplacements: [],
			        cleanAttrs: ['class', 'style', 'dir'],
			        cleanTags: ['meta', 'img']
			    },
				anchorPreview: false,
				autoLink: true,
				placeholder: false	
			});

Works fine on Chrome (formatted text is pasted).

**Comment by j0k3r** [comment]
Yep this is a known bug (even if I can't find a related issue).

Firefox remove all html no matter how do you configure the paste extension. On the other hand it works great on Chrome.

I've started something 8 months ago to handle it like every other editor does:
- catch the paste event
- move cursor in a non `contenteditable` node (like an hidden `div` in the page) BEFORE the even is finalized
- the even is dispatched and the html content is in the non `contenteditable` node
- move this content to the MediumEditor node

But can't find the time to finalize it.

**Comment by daxhns** [comment]
I have just found out that it actually works if you COPY html content FROM Firefox and than paste it in Firefox.

It does not work if you copy html content from Chrome, and then paste it in Firefox.

Madness!

**Comment by j0k3r** [comment]
Yeah I ran into that too and it doesn't _always_ work :confused:
