### ISSUE TITLE
padding/margin inherit causing placeholder misalignment

### ISSUE THREAD

**Issue by billsworld** [yabwe/medium-editor#977]
I am referring to these lines https://github.com/yabwe/medium-editor/blob/master/src/sass/components/_placeholder.scss#L11-L12

Which were added in this commit https://github.com/yabwe/medium-editor/commit/ee9c13660522c3e09a0e3ed579e008a080045faf

For me if my ```<h1>``` or whatever element is editable has a margin, then the placeholder also gets a margin causing it to be misaligned.

**Comment by nmielnik** [comment]
Any recommendation for a fix? I don't know if I have all the context for why the commit was added so we'd just want to be sure to not cause any regression...

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
