### ISSUE TITLE
How to execute extensions programmatically at specific parts of the content?

### ISSUE THREAD

**Issue by romelperez** [yabwe/medium-editor#979]
Hi!

I have an extension called "highlighter" that wraps a selection in the tag `<mark>` and I would like to programmatically execute it at an specific part of the content editable.

For example, If I have:

```html
<p id="editor">This is the <i>content</i> of the editor. I want from (1) here until
<b>this part (2)</b> to be highlighted.</p>
```

And I want to execute the extension "highlighter" in the content editable `#editor` from the position `(1)` until `(2)`. At the end I want to have:

```html
<p id="editor">This is the <i>content</i> of the editor. I want from <mark>(1) here until
<b>this part (2)</b></mark> to be highlighted.</p>
```

Is there a way to achieve this?

Thanks in advanced!

**Comment by nmielnik** [comment]
@romelperez have you seen the [Walkthrough - Building a Button](https://github.com/yabwe/medium-editor/blob/master/src/js/extensions/WALKTHROUGH-BUTTON.md) which is a tutorial on how to build a highlight button?  That examples uses rangy since there currently isn't built-in support for wrapping a selection in an element in medium-editor.

**Comment by romelperez** [comment]
@nmielnik yes! I created a really similar extension with that tutorial. So if I want to modify the content editable DOM I have to do it manually with that library? Thanks!

**Comment by nmielnik** [comment]
Yeah, currently we don't have any built-in support for wrapping a selection inside of a DOM element (though we would definitely love to have that kind of functionality).  So you'd need something like rangy, or another library, or you'd have to built it yourself :disappointed:

**Comment by romelperez** [comment]
@nmielnik okay! Thank you very much! :+1:

**Comment by nmielnik** [comment]
np
