### ISSUE TITLE
ImageDragging should drop file at the end of dropping target

### ISSUE THREAD

**Issue by goldensunliu** [yabwe/medium-editor#980]
Currently, on drag and drop of an image, the content is inserted on the editor's selection. example:
This produces two undesired behavior:

### 1. when there is an active selection in the editor, dropping a file will replace the selection. 
example:
![](http://g.recordit.co/ykO4epQFCX.gif)
### 2. current logic highlights the dropping target and make users believe that the image will be inserted behind where it is highlighted, when it is not. 
example:
![](http://g.recordit.co/Ik1QA1hDa5.gif)

### Ideally, the behavior should be on drop of an image, it is then inserted at the end of the element it was dropped upon
example:
![](http://g.recordit.co/750lZR8oOy.gif)

**Comment by goldensunliu** [comment]
I got a PR open here. Let me know https://github.com/yabwe/medium-editor/pull/981

**Comment by nmielnik** [comment]
Thanks for the great issue details, this was easy to understand thanks to all your details and the great animations
