### ISSUE TITLE
When dragging image into editor, `editableInput` fires before image src is set

### ISSUE THREAD

**Issue by nmielnik** [yabwe/medium-editor#985]
@kaave attempted to fix this with #938 but the fix had gone stale.

The issue is that when dragging an image into the editor, the file-dragging extension first inserts an image tag, then waits for the file to download before it updates the `src` of the `<img>` tag.

Since it inserts the `<img>` first, the `editableInput` event will fire BEFORE the `<img>` actually has a source and contains the actual image contents.  Ideally, the `<img>` wouldn't be inserted until it actually has a source so the `editableInput` gets triggered at a point where the image is valid.

**Comment by LeeKevin** [comment]
All fixed.

**Comment by nmielnik** [comment]
Fixed by #990 (thanks @LeeKevin).

The fix should is available in v5.14.4 (https://github.com/yabwe/medium-editor/releases/tag/5.14.4)
